### ISSUE TITLE
Any plans to make Ruby a first class citizen (like PHP)?

### ISSUE THREAD

**Issue by jpwynn** [rollbar/rollbar-gem#1000]
The PHP version supports a couple of useful features the Ruby version does not... `check_ignore` and `raise_on_error` being two very usefuol ones that Ruby users do not have the benefit of.

Wondering why the disparity, and when it might be addressed?

**Comment by waltjones** [comment]
Rollbar-gem does support `raise_on_error`, but it looks like it was missing from the config reference doc. I've just updated the doc to include it.

The `before_process` hook in rollbar-gem includes ignore functionality. See the Ignoring Items section here for more detail. https://docs.rollbar.com/docs/ruby#ignoring-items

**Comment by demimismo** [comment]
Just wanted to add that the documentation for the Ruby `before_process` hook is not great. At the very least, it's missing some examples.

I can see in the documentation that this hook receives a Hash with a few keys, but I needed to dig into the gem codebase to understand basic stuff such as that those keys are symbols.

I'm trying to ignore certain instances of `ActionController::RoutingError` and I can't really see if the request is part of this Hash. I can't find an easy way to make this hook run with RSpec either, so in general, this is not a great development experience.
