### ISSUE TITLE
Any way to redirect Rollbar.error() to the log or stderror, or stdout in certain environments like Test?

### ISSUE THREAD

**Issue by jpwynn** [rollbar/rollbar-gem#1001]
In the Test environment, and sometimes in Development as well, Rollbar.error(x)  notifications going to the online dashboard is probably pointless. 

There ought to be a mechanism to redirect Rollbar.error(x) and Rollbar.warning(x) to an alternate handler so app developers can observe the exceptions locally, right there, as they are testing and developing.

The wrong approach is to disable the gem on Test and/or Development becasue that simply __hides__ the exceptions form the very people who needs them most (developers while they develop).

Is there currently _any_ way (even monkey patching) that in the test and development environments all calls to Rollbar.error(e) can _not_ report to the project dashboard and instead simply output to, for example, the _local_ logger that the developer is watching as they develop?

**Comment by waltjones** [comment]
Setting `transmit` to false and `log_payload` to true should do what you want. These were missing from the configuration reference and I've just added them.
