### ISSUE TITLE
Provide way to show more of top of stack trace

### ISSUE THREAD

**Issue by mehagar** [rollbar/rollbar-gem#1007]
Currently rollbar only shows up to 100 lines of the stack in the case that the payload sent to Rollbar is too large, and there are more than 100 lines. It will also show only the top 50 and bottom 50 lines of the stack trace, which makes debugging `SystemStackErrors` more difficult in the case that the recursion doesn't show up in the top 50 lines of the call stack. 

I would like a configuration option you can set that will let you customize the portion of stack frames that show up at the top of the trace.

**Comment by brianr** [comment]
Another tack here may be to tweak the algorithms used to trim the payload when it's too large - i.e. maybe we can start by trying to keep more than 100 stack frames, or have options to prioritize the stack trace ahead of other parts of the payload.
