### ISSUE TITLE
Ability to specify project via Item's access_token

### ISSUE THREAD

**Issue by jimmypitts** [rollbar/rollbar-gem#1011]
With previous implementation of the rollbar gem, we were able to specify the project an `Item` would go to be modifying the `Item.payload['access_token']` value.

With this change (https://github.com/rollbar/rollbar-gem/commit/e26b2e9be55c4d522c9c0188bbd322d8b7ead3d1#diff-fd6b24824d824a40b57acc4ef68a36b12c4b67f33aa197d4a1414decfcb6c00cL518-R520), the project is now inferred from the top-level `configuration.access_token`.

We have a single application where we'd like to send items to different projects, depending on different cases.  Is there a preferred way to achieve this?  We are currently using a transform hook to intercept the payload.

**Comment by waltjones** [comment]
Starting in v3.1.0, set `config.use_payload_access_token = true` to send the payload using only the payload data key and not the HTTP header. The override in the transform hook should then work. If you're using a job queue sender, the config flag should be set in both the originating process and the job handler process.

**Comment by jimmypitts** [comment]
Thanks for the quick reply @waltjones
