### ISSUE TITLE
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by kmarsh** [rollbar/rollbar-gem#1017]
I've been trying to track down an error that has been constantly showing up in our Rollbar for awhile now:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/100/100921323-647e1000-34aa-11eb-9f05-14c48e99cdbc.png">

It shows `Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8` but throughout all my digging I can't seem to see where this character originates from or create a request that triggers it. It seems to be all from Facebook's browser, but visiting the request.url doesn't re-trigger the error and occurrence details don't provide any helpful information. The traceback seems to indicate an issue with JSON encoding, possibly related to session but I can't verify:

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/100/100921375-7a8bd080-34aa-11eb-8981-ae28ffe7182b.png">

This small snippet `data = ["\xE2\x9C\x89 Hello".force_encoding(Encoding::ASCII_8BIT)]` also triggers the same error.

In my research I found a similar issue with Senty, that was reported [here](https://github.com/getsentry/sentry-ruby/issues/689) and fixed [here](https://github.com/getsentry/sentry-ruby/pull/696). Perhaps there is a similar issue with Rollbar?

**Comment by waltjones** [comment]
@kmarsh Thanks for a test case. I'll see if I can repro.

**Comment by kmarsh** [comment]
@waltjones I have some more specifics about this as I dug into our production Rails logs:

This line also shows up:

```
E, [2021-01-12T21:19:30.877157 #1] ERROR -- : [4fffdcca-8fd4-45b1-b509-87fd3f9bbe7e] [Rollbar] There was an error scrubbing the url: URI must be ascii only "https://vintageaerial.com/photos/pennsylvania/dauphin/search?utf8=\xE2\x9C\x93&type=address&lat=40.29037&lng=-76.68191&q=Union+Deposit%2C+PA+17033%2C+USA&commit=Show+Nearby+Photos", options: {:url=>"https://vintageaerial.com/photos/pennsylvania/dauphin/search?utf8=\xE2\x9C\x93&type=address&lat=40.29037&lng=-76.68191&q=Union+Deposit%2C+PA+17033%2C+USA&commit=Show+Nearby+Photos", :scrub_fields=>[:passwd, :password, :password_confirmation, :secret, :confirm_password, :password_confirmation, :secret_token, :api_key, :access_token, :accessToken, :session_id, :password, :number, :year, :month, :verification_value], :scrub_user=>true, :scrub_password=>true, :randomize_scrub_length=>false, :whitelist=>[]}
```

Making me think something in the `utf8` param is tripping this up? `\xE2\x9C\x93` is of course, not ASCII, it's the checkmark symbol Rails apps add to force UTF8 encoding in older browsers. (Now that I think about it... it might not even be necessary anymore...)

**Comment by waltjones** [comment]
@kmarsh Thank you for these examples.

That error comes from here:
https://github.com/rollbar/rollbar-gem/blob/v3.1.1/lib/rollbar/scrubbers/url.rb#L26

And I'm able to repro the error by passing a URL containing true utf-8 without % encoding.

**Comment by waltjones** [comment]
The linked PR should address the issue from the Rails log. I'm still looking at the first issue, but the stack trace looks like it might not be rollbar-gem related.

**Comment by waltjones** [comment]
Released in v3.1.2.

**Comment by kmarsh** [comment]
@waltjones Thanks for the fix. After upgrading to 3.1.2 I'm still seeing these errors... 😢

**Comment by waltjones** [comment]
The error in the Rails log? Or the stack trace originally posted?
