### ISSUE TITLE
Update rollbar.js to v2.21.0

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#1029]
I'm using rollbar js in this way: 
```
<% rollbar_gem_dir = Gem::Specification.find_by_name("rollbar").gem_dir %>
<%= raw File.read("#{rollbar_gem_dir}/data/rollbar.snippet.js") %>
```
The new version of rollbar.js is available but not updated in the gem: https://github.com/rollbar/rollbar.js/releases https://github.com/rollbar/rollbar-gem/tree/master/data

Can we have an update?

**Comment by waltjones** [comment]
v2.21.1 is nearly released. It'll be updated then.

**Comment by morgoth** [comment]
@waltjones are there any news about the new release with updated js?

**Comment by waltjones** [comment]
@morgoth 2.22.0 is coming out today, and I'll open a PR to update it immediately after. No kidding this time, and apologies for the delay.

**Comment by morgoth** [comment]
thank you
