### ISSUE TITLE
Use `.scoped` block in sidekiq plugin?

### ISSUE THREAD

**Issue by etipton** [rollbar/rollbar-gem#1036]
Question: Is there any reason not to do:

```ruby
Rollbar.scoped(scope) do
  yield
end
```

in `Rollbar::Sidekiq#call` ?

The problem: I have worker code that catches errors and calls `Rollbar.log`, but the resulting payload has none of the job information provided by the `Rollbar::Sidekiq` middleware

**Comment by waltjones** [comment]
It looks safe and reasonable to do if enabled via a config option, keeping the current default behavior.

**Comment by etipton** [comment]
hoping to work on this today
