### ISSUE TITLE
Logging errors fails using Capistrano 2

### ISSUE THREAD

**Issue by mehagar** [rollbar/rollbar-gem#1039]
We're using the rollbar `3.1.2` and capistrano `2.15.9` gems. When a deploy fails, `logger.error` is called. However, the capistrano 2 logger does not have a `error` method (see [here](https://github.com/capistrano/capistrano/blob/v2.15.9/lib/capistrano/logger.rb)), so this call also fails, and there is no way to see what the error actually was.

**Comment by waltjones** [comment]
@mehagar Thank you for the report. A fix for this is scheduled for the next rollbar-gem release.
