### ISSUE TITLE
Errors tracking from Karafka

### ISSUE THREAD

**Issue by n-n1ks** [rollbar/rollbar-gem#1040]
Hello!
I'd like to log all errors from [karafka](https://github.com/karafka/karafka) with a custom framework, and I do something like this:
```
Karafka.monitor.subscribe("app.initialized") do
  Rollbar.configure do |config|
    config.framework = "Karafka"
  end
end
```
I can see the valid framework in the item payload, but in Rollbar UI I can't see my framework, and Rollbar sets `Ruby` framework for all errors from karafka.

What I do wrong?
<img width="1162" alt="CleanShot 2021-04-26 at 16 34 18@2x" src="https://user-images.githubusercontent.com/2771642/116091212-4ad5a300-a6ad-11eb-9720-9b4c47d5616f.png">

**Comment by waltjones** [comment]
All Rollbar capabilities should work as expected. The dashboard doesn't have the glyph for Karafka yet, which is why you see the Ruby glyph.

I'll pass along the info to the design team and see if Karafka can be added.

**Comment by n-n1ks** [comment]
So how can I filter right now? Via RQL only?

**Comment by waltjones** [comment]
That looks like a bug, as the framework list should be based on the available frameworks, not the available icons. I'll pass this along as well to the appropriate team.

**Comment by n-n1ks** [comment]
Ok, thank you!

**Comment by n-n1ks** [comment]
@waltjones hello! I'm sorry for disturbing you, but do you have any updates?

**Comment by waltjones** [comment]
I've submitted the issue to the appropriate internal team. This issue tracker is really just for rollbar-gem. If you want to track this request, the best way is through Rollbar support. https://rollbar.com/support/ You can mention this is referencing ch83936

**Comment by waltjones** [comment]
@n-n1ks I'm told the Karafka framework is supported in the dashboard now. Can you confirm?

**Comment by n-n1ks** [comment]
@waltjones thanks! I'll let you know soon.
