### ISSUE TITLE
Failsafe from rollbar-gem. Net::ReadTimeout (again)

### ISSUE THREAD

**Issue by patsplat** [rollbar/rollbar-gem#1067]
Am seeing errors logged like this show up in our rollbar account:

> Failsafe from rollbar-gem. Net::ReadTimeout: "Net::ReadTimeout with #<TCPSocket:(closed)>" in /usr/local/lib/ruby/2.7.0/net/protocol.rb:217:in `rbuf_fill': error in process_item

This error looks like #950 #951 #952 #953, however am using 3.2.0 which contains the fix presumably.

How might I investigate more closely?

**Comment by drkelly58** [comment]
We're seeing this issue too, also on 3.2.0 but on ruby 3.0.2
 

> Failsafe from rollbar-gem. Net::ReadTimeout: "Net::ReadTimeout with #<TCPSocket:(closed)>" in /usr/local/lib/ruby/3.0.0/net/protocol.rb:219:in `rbuf_fill': error in process_item

**Comment by waltjones** [comment]
You will see this when the API can't be reached for any reason. I'm guessing the ones you saw were during yesterday's API related incident: https://status.rollbar.com/incidents/8xzyzh0dmhz2

**Comment by patsplat** [comment]
Thank you @waltjones that is helpful.
