### ISSUE TITLE
Guidance on how to reduce rollbar internals logging

### ISSUE THREAD

**Issue by hlascelles** [rollbar/rollbar-gem#1071]
This may be an easy one, but I can't see it in the docs.

Can we limit the logs that Rollbar makes internally? ie these:

![image](https://user-images.githubusercontent.com/299102/140912370-3f3c5bcf-fa38-40c3-b169-67c96d6a5c06.png)

Thanks!

**Comment by waltjones** [comment]
Setting `logger_level` in the Rollbar configuration should do it. Those shown above are info level, and setting `config.logger_level = :warn`, or `:error`, will filter them. This can also be set to `nil` to disable all log messages.

**Comment by hlascelles** [comment]
Great, thank you!
