### ISSUE TITLE
Documentation correction for ignoring items

### ISSUE THREAD

**Issue by wasaylor** [rollbar/rollbar-gem#1104]
[Ignoring items](https://docs.rollbar.com/docs/ruby#ignoring-items) mentions you can return `"ignored"` as an alternative to raising `Rollbar::Ignore`, but `return` inside the proc raises a `LocalJumpError`.  I would suggest to use `next "ignored"` instead.

**Comment by wasaylor** [comment]
using your docs suggestion thing instead

**Comment by brianr** [comment]
Fixed (accepted your docs suggestion). Thank you!
