### ISSUE TITLE
Use The new Rails error reporter

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#1105]
The built-in error reporter is now available in Rails.
https://edgeguides.rubyonrails.org/error_reporting.html

It should simplify and cleanup the integration for the rollbar gem.
There is already an error tracker that is integrated with it, vide https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/error_subscriber.rb

**Comment by waltjones** [comment]
@morgoth thank you! Support for this is published in v3.6.0. https://github.com/rollbar/rollbar-gem/releases/tag/v3.6.0

Docs will be updated. See the PR for config.
