### ISSUE TITLE
rake rollbar:test does not work outside of Rails

### ISSUE THREAD

**Issue by billywatson** [rollbar/rollbar-gem#111]
I saw that the gem now works for Rails without ActiveRecord, but what about for Ruby projects without Rails? I'm not sure at the breadth of this issue, but I have at least one instance where I can't use Rollbar without Rails. 

After setting up Rollbar and doing some hackery to get `rake rollbar:test` to at least kick off, I get the following error since the task depends on Rails:

{code}
$ rake rollbar:test --trace
WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.9.0
** Invoke rollbar:test (first_time)
** Invoke environment (first_time)
** Execute environment
Using local default.yml file
configuring mandrill with API Key 5cUQGgYelCI6ruSVBITN6w in the development environment
** Execute rollbar:test
rake aborted!
uninitialized constant Rails
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rollbar-0.12.17/lib/rollbar/rake_tasks.rb:6:in `block (2 levels) in <top (required)>'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/task.rb:228:in `call'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/task.rb:228:in `block in execute'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/task.rb:223:in `each'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/task.rb:223:in `execute'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/Users/williamrwatson/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/task.rb:159:in `invoke_with_call_chain'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/task.rb:152:in `invoke'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:143:in `invoke_task'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:101:in `each'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:101:in `block in top_level'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:110:in `run_with_threads'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:95:in `top_level'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:73:in `block in run'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/lib/rake/application.rb:70:in `run'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/gems/rake-0.9.6/bin/rake:37:in `<top (required)>'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/bin/rake:23:in `load'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/bin/rake:23:in `<main>'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/bin/ruby_executable_hooks:15:in `eval'
/Users/williamrwatson/.rvm/gems/ruby-1.9.3-p194@o2o/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => rollbar:test
{code}

**Comment by benja83** [comment]
Hi,

I'm using Sinatra:

I reached to import the rake_tasks in my Rakefile and create an Environment task setting up my app.

The following problem is that the task look for Rails:
https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/rake_tasks.rb#L6

May be it could be possible to create a new logger going to $stdout or using a lower abstraction level and using rack.

**Comment by jondeandres** [comment]
Hi @benja83,

that task depends on Rails yes. For Rails we add automatically a middleware to the chain, so we wanted to test that.

That task builds a new action that will fail and adds the route to the app, then it tests that route just calling it.

For Sinatra you need to use manually the middleware for Sinatra, `Rollbar::Middleware::Sinatra`. And it may be difficult add new routes to your app just for testing it.

I think we should have a task `rollbar:test:rails` similar to the current one, and another `rollbar:test` that also depends on `:environment`. So you can define your environment task and we can just call `Rollbar.error` to test that configuration.

This task should be something like this:

```ruby
require 'rollbar'

namespace :rollbar do
  desc "Verify your gem installation by sending a test exception to Rollbar"
  task :test => [:environment] do
    begin
      this = will_fail
    rescue => e
      Rollbar.error(e)
    end
  end
end
```

**Comment by benja83** [comment]
Hi @jondeandres 

Sounds good, I will try it later, thanks for responding so fast!

May it could be fine to update the documentation with this.

**Comment by jondeandres** [comment]
fixed with https://github.com/rollbar/rollbar-gem/pull/489
