### ISSUE TITLE
Load rollbar.min.js as local asset instead of CDN

### ISSUE THREAD

**Issue by goulvench** [rollbar/rollbar-gem#1123]
Hi,

Rollbar tries to include the script from cdn.rollbar.com, which is blocked by my app's CSP config.

Would it be possible to add rollbar.min.js to the asset pipeline instead, so that it is served locally?
Otherwise, it should be documented that one needs to add `https://cdn.rollbar.com` to the list of authorized `script-src` in content-security-policy.

**Comment by waltjones** [comment]
Hi @goulvench ,

If you copy rollbar.min.js to your assets, you can add a `rollbarJsUrl` key to your Rollbar config:
```js
var _rollbarConfig = {
  // ...
  rollbarJsUrl: 'http://example.com/path/to/rollbar.js'
}
```

As you noted, the CSP config can be updated instead.

Good point about the doc update. Thank you.
