### ISSUE TITLE
DEPRECATION: Sidekiq exception handlers now take three arguments

### ISSUE THREAD

**Issue by devaniljr** [rollbar/rollbar-gem#1131]
worker | 2023-10-04T10:02:00.510Z pid=253522 tid=4yc6 INFO: DEPRECATION: Sidekiq exception handlers now take three arguments, see #<Proc:0x00007f07be656108 /home/devanil/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rollbar-3.4.0/lib/rollbar/plugins/sidekiq.rb:15>
worker | 2023-10-04T10:02:00.510Z pid=253522 tid=4y76 ERROR: Error fetching job: Waited 3.0 seconds

```rb
      config.error_handlers << proc do |e, context|
        Rollbar::Sidekiq.handle_exception(context, e)
      end
```

**Comment by bf4** [comment]
I'm always surprised by the lack of Ruby support for this product we pay for.. when simple maintenance tasks like this grow stale, I begin to wonder if we should switch to something else

@waltjones is Ruby still supported?

**Comment by rollbar-bborsits** [comment]
Hey @devaniljr @bf4, We scheduled working on the Ruby SDK after Thanksgiving. Our Ruby dev is currently headed down on another crucial initiative, but I want to assure you we still remember this one. I was informed that the Sidekiq update will probably require a breaking change; hence expect a major version bump.
