### ISSUE TITLE
Deprecation warning in Rack 3

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#1134]
On 404 responses, I'm getting deprecation warning in logs:
```
ActionController::RoutingError (No route matches [GET] "/login.html"):
  
/usr/local/bundle/ruby/3.2.0/gems/rollbar-3.4.1/lib/rollbar/middleware/rails/show_exceptions.rb:10: warning: Request#[] is deprecated and will be removed in a future version of Rack. Please use request.params[] instead
```

Rails 7.1.1
rack 3.0.8

**Comment by jonmchan** [comment]
I confirm this issue on Rails 7.1.2. Same error.

rails (7.1.2)
rack (3.0.8)

**Comment by rollbar-bborsits** [comment]
Hey @morgoth @jonmchan, Thanks for reporting this issue. I opened an internal bug ticket for this issue (131090). I'll get back to you after we schedule it.

**Comment by rollbar-bborsits** [comment]
Hey @morgoth @jonmchan, We scheduled work on the Ruby SDK after Thanksgiving. Our Ruby dev is currently headed down on another crucial initiative. I was informed that another fix will probably require a breaking change; hence expect a major version bump.

**Comment by jonmchan** [comment]
Thanks for the update and thanks for addressing this! Will be on the look out for the new version.
