### ISSUE TITLE
Multiple notifier and one Sidekiq worker

### ISSUE THREAD

**Issue by tim37021** [rollbar/rollbar-gem#1141]
We have more than one Rollbar token in one project and create `Rollbar::Notifier` for each token.
Is it possible to allow `Rollbar::Delay::Sidekiq` in worker pod knowing which token to use?

**Comment by waltjones** [comment]
@tim37021 Setting the config option `use_payload_access_token = true` will allow the access_token in each payload to be used, rather than the one in the Sidekiq worker config.
