### ISSUE TITLE
NameError: undefined local variable or method `arguments' for an instance of xxxMailer

### ISSUE THREAD

**Issue by nov** [rollbar/rollbar-gem#1145]
https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/active_job.rb is expecting `ActionMailer::Base` children have `arguments`, but actually not.
thus causing the error in title

**Comment by womanonrails** [comment]
I have the same problem `rollbar-gem` version `3.5.0`.

**Comment by waltjones** [comment]
Thank you for the reports. Working to get a fix out today.

**Comment by waltjones** [comment]
Released in 3.5.1. https://github.com/rollbar/rollbar-gem/releases/tag/v3.5.1

**Comment by isaacbowen** [comment]
Thanks @waltjones! :)
