### ISSUE TITLE
Rollbar::Logger not working well with the newest logger gem

### ISSUE THREAD

**Issue by randypuro** [rollbar/rollbar-gem#1156]
Rollbar::Logger inherits from ::Logger, but [doesn't call it's constructor](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/logger.rb#L25).

logger gem v1.6.0 (which, for instance, comes with ruby 3.3.1) [initializes other parameters in that constructor](https://github.com/ruby/logger/blob/master/lib/logger.rb#L587) which are used in other methods (like [the level accessor](https://github.com/ruby/logger/blob/master/lib/logger.rb#L384)).

It means accessing the `level` in Rollbar::Logger raises an exception. Rollbar::Logger should probably also use the level accessor (instead of the instance variable) to be more resilient to these kinds of improvements/changes to the base ::Logger.

And while I understand the point of raising exceptions on formatter, etc; it means the Logger doesn't play well with the newer Rails logger broadcast functionality which tries to copy formatters down to any new broadcast children.

**Comment by waltjones** [comment]
@randypuro Thank you for the report!

Published in v3.6.0. https://github.com/rollbar/rollbar-gem/releases/tag/v3.6.0
