### ISSUE TITLE
Gather local variables for exceptions

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-gem#117]
Like we do in Python: https://rollbar.com/blog/post/2014/06/05/local-variable-values-in-stack-traces

**Comment by albertyw** [comment]
+1

**Comment by chenatuc** [comment]
+1 for this critical feature! This will save the engineers tremendous amount of time trouble-shooting issues.

**Comment by waltjones** [comment]
Recently documented here: https://docs.rollbar.com/docs/ruby#section-enabling-local-variables-in-stack-traces
