### ISSUE TITLE
Split rollbar.rb into rollbar.rb, notifier.rb and item.rb

### ISSUE THREAD

**Issue by jondeandres** [rollbar/rollbar-gem#141]
We need to organize something more the gem. Actually the `Rollbar` module has all the methods instead those in `Rollbar::Util`.

We can split it into:

* `Rollbar`, lib/rollbar.rb. Contain the main public API for the users. Some methods are delegated to a `Rollbar::Notifier` instance by thread.
* `Rollbar::Notifier`, lib/rollbar/notifier.rb. Contain the different methods to send all the item levels that the Rollbar API support. Users can instantiate it by hand.
* `Rollbar::Item`, lib/rollbar/item.rb. Represents a item to be sent to the Rollbar API. All the payload related methods are here.

We can split spec/rollbar_spec.rb to different unit files and use spec/rollbar_spec.rb more for integration specs for example.

**Comment by dlsteuer** [comment]
This has been completed.
