### ISSUE TITLE
Remove Rack::Builder monkey patch

### ISSUE THREAD

**Issue by jondeandres** [rollbar/rollbar-gem#157]
We are monkey patching `Rack::Builder` in https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/middleware/rack/builder.rb.

I'd remove these kind of practises and just would provide a middleware for the users. The most common approach is just provide a middleware that will work for all Rack applications and probably for Sinatra too.

The correct steps can be:
1. Phase 1
   1. Provide the Rack middleware
   2. Monkey patch by default but allow users to disable monkey patch
   3. Warn the users about the monkey patch option if it's enabled and suggest using the middleware.
2. Phase 2
   1. Remove monkey patch and monkey patching option.

The Phase 2 could be avoided and just offer the users a way to disable the monkey patch, so Phase 1 could be enough.

**Comment by coryvirok** [comment]
@jondeandres the PR was merged and released. Can we close this out?

**Comment by jondeandres** [comment]
Sure
