### ISSUE TITLE
rollbar is a "slow require"

### ISSUE THREAD

**Issue by exterm** [rollbar/rollbar-gem#163]
Hi there,

using rollbar for two days, really impressed. One thing that bothers me though is that requiring rollbar slows our application startup by 240ms (according to http://rubygems.org/gems/bumbler).
It is the second slowest require in our project (beaten only by authlogic with 285 ms).

Any ideas how the rollbar gem could be made faster?

**Comment by jondeandres** [comment]
I've tested this locally:

```ruby
irb(main):001:0> require 'benchmark'; Benchmark.measure { require 'rollbar' }.real                                                                                        
=> 0.04584424699714873
```

I think this is not too much time. If anyone detects it's taking a long time, please share your loading results and we can figure out what is happening.
