### ISSUE TITLE
Rollbar can quietly ignores errors outside of web processes.

### ISSUE THREAD

**Issue by jonah-williams** [rollbar/rollbar-gem#183]
I was recently surprised to discover that Rollbar (using rollbar-resque) was not reporting errors for failing Resque jobs. Digging further I found that there are a number of cases where the Rollbar gem could surprisingly fail to report errors to the service. In a Rails web process Rollbar avoids this issue thanks to `RollbarMiddleware` making a call to `Rollbar.reset_notifier!`. However background job processes (Resque, Sidekiq), rake tasks, console sessions, or any other process which loads the Rails environment but does not run middleware can fail to report errors throughout its life.

I see two paths to get into this state:
1. Something makes a call to `Rollbar.log` prior to the Rollbar initializer calling `Rollbar.configure`. In my case this was an `info` level warning in another initializer.
2. A new thread is created prior to the Rollbar initializer calling `Rollbar.configure`. In my case an app had a call to segment.io's `AnalyticsRuby.init` which eventually calls `Thread.new`.

In the first case `Rollbar.log` delegates to `Rollbar.notifier` which returns `Thread.current[:_rollbar_notifier] ||= Notifier.new(self)` ([rollbar.rb#L705](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L705)). In the second case `Thread.initialize_with_rollbar` calls `Rollbar.notifier.scope`. Either way we have a call to `Rollbar.notifier` which sets `Thread.current[:_rollbar_notifier]`.

The `Notifier` instance created for the thread is passed the `Rollbar` class as its `parent_notifier`. The `Notifier` then calls `parent_notifier.configuration.clone` ([rollbar.rb#L42](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L42)) where `configuration` is implemented as `@configuration ||= Configuration.new` ([rollbar.rb#L683](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L683)). Now we have a `Notifier` for the current thread configured with a new `Configuration`. Since this `Configuration` has not yet been enabled `Notifier.log` will abort due to `return 'disabled' unless configuration.enabled` ([rollbar.rb#L112](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L112)).

In a Rails web process the Rollbar initializer would overwrite any existing `Configuration` when it calls `Rollbar.configure do ...`. If a `Notifier` has already been created as above then it remains disabled and missing any configuration changes from the initializer. That's ok because `RollbarMiddleware` eventually calls `Rollbar.reset_notifier!` ([rollbar.rb#L16](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/middleware/rails/rollbar.rb#L16)) which calls `self.notifier = nil` which leads to `Thread.current[:_rollbar_notifier] = notifier` and the unconfigured `Notifier` is removed. The next calls to `Rollbar.notifier` will then create a new `Notifier` and inherit the `Rollbar.configuration` set in the initializer.

A similar call to `reset_notifier!` exists in the Rollbar Rack `Builder` and Sinatra middleware.

Is there a better hook we could use to trigger these `reset_notifier!` calls? Would it be reasonable to always reset the current thread's notifier in `Rollbar.configure` so that every integration does not need to repeat this setup?

As is it seems easy for users of rollbar-resque to miss error reports. At a glance I don't see a call to `reset_notifier!` in https://github.com/allenwei/sidekiq-rollbar either but I'm not familiar with the forking model in use there so maybe it isn't an issue in that case. having added a Rollbar initializer I expected any environment which loads that initializer to be able to successfully report errors to Rollbar. Does that seem like a reasonable expectation, if not maybe we can at least make a readme update?

**Comment by pcasaretto** [comment]
This might be related.
When on the heroku console, Rollbar seems to ignore any exceptions raised.
I'm on 1.5.0.

**Comment by jondeandres** [comment]
@pcasaretto is your environment being loaded correctly? Did you check `config.enabled` option? How are you trying it? Just `Rollbar.error(exception)` ?

**Comment by pcasaretto** [comment]
I ran a piece of code that raised an exception, and also tried a `raise/fail` manually.
```
> Rollbar.configure { |c| p c.enabled }
true
```
Using `Rollbar.error` worked normally.

**Comment by jondeandres** [comment]
@pcasaretto can you paste that code?

I think you are expecting that any exception in the console will be reported. That automatic reports are only done in the middleware, so when there is a request. Exceptions in the console are not reported unless you report them manually.

So you should wrap your code with:
```ruby
begin
  # your code
rescue => e
  Rollbar.error(e)
end
```

**Comment by pcasaretto** [comment]
AH, I see. Thanks for clarifying that.

**Comment by jondeandres** [comment]
Thanks to you @pcasaretto!!
