### ISSUE TITLE
Configuration option to disable Rails support

### ISSUE THREAD

**Issue by bhh** [rollbar/rollbar-gem#193]
i know its just lame to still have 2.3 applications but i got this "new" old application i have to take care of and first thing is i want to log errors nicely.
is there a way to disable the default rails stuff per config?

the only problem i have is  that it wants to autoload railtie and active_record_extension
if i could disable it per config everything would work fine and i could just have to rescue the errors and stuff i want to and send it with the gem (this part seems to work perfectly because there is not rails integration)

if you think wtf he is crazy wanting rails 2.3 support just delete it ;)
i dont really need support for it just a method to disable rails support
would it be a problem if i try to get it into the config with a PR?

**Comment by bhh** [comment]
ok new approach. 
what do u think of the idea of spliting the rails features.

so we have a rollbar-gem and rollbar-rails with rollbar dependecy of course. like rspec-rails and stuff.
additionally we could implement the javascript client side integration also in the rails gem

**Comment by guzart** [comment]
I think environment flag is probably the easiest way to go, and best practices ATM suggest your app gets the configuration from environment variables (running context).

**Comment by bhh** [comment]
easy definitly but i like the idea of extracting the rails part way more. and if the owners approve, i have no problem of doing a bit more work to keep everything clean.

for me it feels nicer to have a core gem with just the rollbar api in it

**Comment by jondeandres** [comment]
@bhh feel free to open a PR with your solution, we'll be looking at this at soon as possible

**Comment by ianheggie** [comment]
I have just added rollbar into a rails 2.3.18 LTS project (ruby 1.9.7, capistranio v3) - suggestions on how to improve it welcome.

I disable the require in Gemfile so I can be sure it is initialised if it has been loaded.

**Gemfile**:
```
gem 'rollbar', require: false
```

**config/initializers/rollbar.rb**:
```
require 'rollbar'

rollbar_enabled = (Rails.env.test? || Rails.env.development?)

Rollbar.configure do |config|
require 'rollbar'

rollbar_enabled = (Rails.env.test? || Rails.env.development?)

Rollbar.configure do |config|
  # Without configuration, Rollbar is enabled in all environments.
  # To disable in specific environments, set config.enabled=false.
  config.enabled = rollbar_enabled

  # ... etc etc ...
end

if rollbar_enabled
  require 'rollbar/rails23/notifier'
  class ActionController::Base
    include Rollbar::Rails23::Notifier

    def rescue_action_with_rollbar(exception)
      notify_rollbar_from_within_controller(exception)
      rescue_action_without_rollbar exception
    end

    alias_method_chain :rescue_action, :rollbar
  end
end
```

**lib/rollbar/rails23/notifier.rb**:
```
module Rollbar
  module Rails23
    module Notifier
      include Rollbar::ExceptionReporter
      include Rollbar::RequestDataExtractor

      def notify_rollbar_from_within_controller(exception)

        env = @_request.env
        request_data = extract_request_data_from_rack(env)
        request_data[:route] = {
                    controller: params[:controller],
                    action: params[:action],
                    format: params[:format]
                }
        scope = {
            request: request_data,
            #context: { vertical: @vertical } # FIXME: Work out how to pass context
        }
        if current_user
          scope[:person]=  {:id => current_user.id, :username => current_user.screenname, :email => current_user.email}
          scope[:person][:username] =  current_user.screenname if !current_user.screenname.blank? && current_user.screenname != 'anonymous'
        end

        Rollbar.scoped(scope) do
          Rollbar.error(exception)
        end
      rescue Exception => exception2  # report if we stuffed up reporting with details
        Rollbar.error(exception)
        Rollbar.error(exception2)
      end
    end
  end
end
```

**Comment by bhh** [comment]
i'm so sorry i totally forgot about that topic. i think will look into it again upcoming week and maybe start a rollbar-rails project

**Comment by ianheggie** [comment]
Two of my clients are on https://railslts.com/ - rails 2.3 LTS (and 3.2) is worthwhile supporting.

**Comment by jondeandres** [comment]
Hey @ianheggie, have you taken a look at https://github.com/rollbar/rollbar-gem/blob/master/docs/plugins.md?

It's the architecture for the plugins system. We are wondering if that rails 2.3 support could be rewriten using the new plugins interface.

BTW, nice work so far on that.

**Comment by ianheggie** [comment]
Thanks for the input @jondeandres - I will have a look at the plugin support - I have a few further things I need to do (missing action is being caught earlier in the process and thus is not reporting controller). Also in my project I am disabling router errors unless a user is logged in - I get way to many bots submitting mangled urls.

**Comment by dgilperez** [comment]
Superb job @ianheggie! Did you eventually get a running solution? I also have a new old rails 2 app to maintain :)

**Comment by ianheggie** [comment]
Yes, it works well enough (A few little niggles, but I am happy to share the code) - and re new/old rails 2 - I have two clients on 2.3.18 LTS - and I can see them staying on it because the cost to upgrade and keep upgrading would be too much.

**Comment by dgilperez** [comment]
I'd love to see that final code if I may 😄

**Comment by bhh** [comment]
wondering if people are still interested in this. 

had some time to kill today and removed everything rails related as i suggested. as far as i can tell everything is still working. tests + some examples i tried. 

https://github.com/rubberandglue/rollbar-gem 

i copied every piece of removed code and tests into another repository (i guess this one will be a bit more tricky)
i still missed out on the documentation for now. and i'm not sure if i did everything right for travis because rails tests aren't necessary anymore for this repository if the solution is accepted. there are still some "rails" strings but they should all be just string matching (not really rails related as far as i can see)

i really like the solution so far. splitting everything up really contributes to nice replaceable modules. we wont be able to just turn rails support on/off with the new gem we also could make multiple versions for rails 2,3,4,5

hope you guys like it too

**Comment by rokob** [comment]
I like the idea, but I'm still not sure about the benefit of doing a full split into two repos versus trying to do this via the plugin mechanism. I need to look at the code a bit more. I think the split into two repos is actually probably easier, just not sure if it is better from a maintenance perspective going forward.

**Comment by bhh** [comment]
as i discovered the chronlogy is seems to be weird. thats why i came up with a solution i like most

* railtie loading
* getting config
* deciding to disable rails
* how not to load rails!? everything loaded/crashed already

with the plugin mechanism and railtie you always have to load everything first then get the config and the decide to disable!? but the crash already happens during loading. why load it in the first place when i want to disable a specific part(not efficient anyway) and thats fine because i dont think it should be there anyway

imo maintaining the rollbar part seperate from the rails part means you dont have to handle multiple rails versions in the rollbar plugin. no more RAILS_VERSION compare stuff
and its even easier to handle different rails versions because you even can remove all the rails version if/switch statements and just use different rollbar-rails versions.
