### ISSUE TITLE
Add stacktrace when reporting exception manually

### ISSUE THREAD

**Issue by manuelmeurer** [rollbar/rollbar-gem#205]
I wondered why I never saw a backtrace in Rollbar when I reported an error with `Rollbar.error MyError.new`. I mailed your support and @jondeandres explained that errors created with `.new` do not have a backtrace. (Thanks, Jon!)
However, it's quite easy to add:

```ruby
e = Exception.new
e.set_backtrace caller
```

What do you guys think about adding a backtrace to any error that is being reported automatically if it doesn't have one yet?

**Comment by jondeandres** [comment]
@manuelmeurer it's a good idea, but I'm not sure if this should be done by the gem.

Take account that then the backtrace will have lines from our own code. So perhaps this is responsibility of the projects.

@brianr do you have any opinion about this?

**Comment by manuelmeurer** [comment]
The lines from the gem itself could easily be filtered out using something like `caller.reject { |line| line =~ /rollbar/ }`. Also, this could be a configuration option and turned off by default.

**Comment by jondeandres** [comment]
Yah, we can use `Gem::Specification.find_by_name('rollbar').gem_dir` to reject our own backtrace lines.

IMHO when you are using `Rollbar.error(ExceptionClass.new)` you could be using `Rollbar.report('some-message-you-know-where-is-it'). But it's true that more people have asked us for this.

**Comment by manuelmeurer** [comment]
Yep, that's how I'm using it now. But having the backtrace, even when just reporting "some-message-you-know-where-is-it", would be really nice.

Another thing is the exception cause which I heavily rely on since I like to use nested exceptions. This unfortunately cannot be set explicitly. My solution for now is this:

```ruby
begin
  something_that_might_raise_exception
rescue => e
  raise MyError.new('descriptive message') rescue Rollbar.error $1
end
```

This will set the backtrace properly and set `e` as the cause of `MyError.new`.

**Comment by jondeandres** [comment]
@manuelmeurer I've opened a PR for this, https://github.com/rollbar/rollbar-gem/pull/206/files.

Let's wait for @brianr to give us him opinion.

**Comment by manuelmeurer** [comment]
Awesome, thanks Jon!
