### ISSUE TITLE
Disabling reporting for errors generated by bots

### ISSUE THREAD

**Issue by florrain** [rollbar/rollbar-gem#211]
Hello,

We have a lot of our rollbars generated by bingbot, facebookbot, ... I'm mostly thinking of routing errors but I think it might be interesting to filter on all requests.

Is there a way to filter these errors in the configuration of the gem?

Thanks

**Comment by brianr** [comment]
Hi @florrain --

There might be... if you have enough information in the exception object itself, then you can accomplish this with a callablce in `exception_level_filters`. Here's the example from the initializer template:

https://github.com/rollbar/rollbar-gem/blob/master/lib/generators/rollbar/templates/initializer.rb#L37-L42

Will that work?

**Comment by florrain** [comment]
Nice, Fast and furious answer.

What about this code? I'm not sure if I can keep the existing level of the error and just override it for some user agents. 
How can I get the level of the `e` like `.rollbar_level` ? Is that an exception object or a rollbar exception with extra parameters from where I could get it ?

```ruby
config.exception_level_filters.merge!('ActionController::RoutingError' => lambda { |e| 
  if is_bot?(request.user_agent)
    "ignore"
  else
    e.rollbar_level
  end
  }
)```

**Comment by jondeandres** [comment]
@florrain the exception object doesn't have any info about the request or extracted data from it. And we only pass that exception to the callable object to set in the configuration. We could change this behaviour to start passing the notifier itself in the future.

@brianr our change should be something like this in  https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L213

```ruby
if filter.respond_to?(:call)
      filter.call(exception, self)
    else
      filter
    end
end
```

But this change isn't compatible backwards and we should check the arity of the callable object:

```ruby
if filter.arity == 2
  filter.call(exception, self)
# ...
```

We can give a thought to this in the future.

**Comment by florrain** [comment]
That would indeed be very very appreciated. I hope it'll part of upcoming releases.

I'm closing the issue then. Would you mind posting here when you have a release plan? 

Thanks!

**Comment by grosser** [comment]
see https://github.com/rollbar/rollbar-gem/issues/249
