### ISSUE TITLE
Rollbar can't catch gems' exceptions such as doorkeeper or devise

### ISSUE THREAD

**Issue by zeitnot** [rollbar/rollbar-gem#214]

**Comment by jondeandres** [comment]
@zeitnot could you explain in more detail this issue?

**Comment by zeitnot** [comment]
I was using `airbrake`. With it can inject exception catcher libs to doorkeeper's controllers. So I can get doorkeepers's exceptions.

```ruby
require 'airbrake'
require 'airbrake/rails/controller_methods'
require 'airbrake/rails/action_controller_catcher'
require 'airbrake/rails/error_lookup'
require 'airbrake/rails/javascript_notifier'

Doorkeeper::TokensController.send(:include, Airbrake::Rails::ActionControllerCatcher)
Doorkeeper::TokensController.send(:include, Airbrake::Rails::ErrorLookup)
Doorkeeper::TokensController.send(:include, Airbrake::Rails::ControllerMethods)
```

The question is is there any to listen and catch gems' exceptions or errors with rollbar?

**Comment by jondeandres** [comment]
@zeitnot I'm not sure if you need anytihng of that for airbrake or rollbar.

We add our middleware in https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/railtie.rb#L10-L28 and include the controller methods in https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/railtie.rb#L39-L44. I think that's enough.

Could you give us a case of use of this?

**Comment by zeitnot** [comment]
@jondeandres I wonder that if rollbar listens gems' exceptions. If you say this is ok then I trust in you.
