### ISSUE TITLE
Rollbar can't be used when loading actionmailer 4.2 outside of a Rails project

### ISSUE THREAD

**Issue by YorickPeterse** [rollbar/rollbar-gem#220]
ActionMailer depends on ActionPack, which since version 4.2 depends on https://github.com/rails/rails-html-sanitizer which in turn defines `Rails` in the global scope. This then breaks the following check: https://github.com/rollbar/rollbar-gem/blob/2254a85fa424a98b23d1fd2b31b1b703dd15b095/lib/rollbar.rb#L19

Rollbar should probably check for `Rails::VERSION` here instead.

**Comment by YorickPeterse** [comment]
Rails considers this not their problem:

* https://github.com/rails/rails-html-sanitizer/issues/26
* https://github.com/rails/rails-html-sanitizer/issues/25

**Comment by jondeandres** [comment]
@YorickPeterse thank you for this report!

 are you having the problem with a non-Rails project then?

**Comment by YorickPeterse** [comment]
@jondeandres Yes, I use Rollbar in quite a few non Rails projects. In general this works fine, except this one particular project uses ActionMailer, causing the above problem.

**Comment by YorickPeterse** [comment]
Thanks for fixing this!
