### ISSUE TITLE
Exceptions are not reported from rails runner

### ISSUE THREAD

**Issue by AntonZh** [rollbar/rollbar-gem#225]
Rollbar 1.4.4, Rails 4.2.0

```ruby
# app/services/rollbar_runner_tester.rb
class RollbarRunnerTester
  class << self
    def test1
      raise 'Some error'
    end

    def test2
      begin
        raise 'Some other error'
      rescue Exception => e
        Rollbar.error(e)
      end
    end
  end
end
```

```bash
bin/rails runner "RollbarRunnerTester.test1"
# Will not be reported

bin/rails runner "RollbarRunnerTester.test2"
# Will be reported
```

**Comment by jondeandres** [comment]
@AntonZh we don't wrap Rails runner so exceptions there are not automatically reported to our API. Probably we can do something with this, but it's not clear. I think Rails doesn't offer a middlewares stack for the runner or anything.

We'll take a look at this. If we can do something we'll notice you.

**Comment by AntonZh** [comment]
I think that it is really unexpected behavior - rake tasks are wrapped, but runners are not.

**Comment by jondeandres** [comment]
@AntonZh 

I've been looking at the rails runner code, https://github.com/rails/rails/blob/master/railties/lib/rails/commands/runner.rb.

I think we cannot do anything there, we should redefine `eval` or something like that, and that it's a little crazy. What we could do is try to provide a new command that will execute the runner code but it's wrapped by Rollbar. But then users cannot use `rails runner` command and that's all.

**Comment by AntonZh** [comment]
A new command would be fine. Also you may mention the fact that runners are not reporting errors in the documentation.

**Comment by jondeandres** [comment]
We'll do! Thanks @AntonZh!

**Comment by jjb** [comment]
`at_exit` can achieve this

http://ruby-doc.org/core-2.5.0/Kernel.html#method-i-at_exit

```ruby
at_exit do
  if $!
    Rollbar.critical($!)
  end
end
```

**Comment by jjb** [comment]
here's a recipe i came up with. put this somewhere such as /lib or /app/lib:

```ruby
class RunnerErrorReporter < Rails::Railtie
  runner do
    at_exit do
      if $!
        Rollbar.critical($!)
      end
    end
  end
end
```

Then include it from application.rb.

It doesn't work in an initializer -- I guess the railtie hooks are done being brought in at that point.
