### ISSUE TITLE
Russian message become blank when reported to server

### ISSUE THREAD

**Issue by phuongnd08** [rollbar/rollbar-gem#226]
I'm trying to report this message to rollbar server:

"5 Изменение курса заявки не произведено. Старое и новое занчения курса одинаковы."

But once get the Rollbar server it become this "1  -      .             ,         10 .".

I think it become that way when rollbar try to normalize the payload.

**Comment by jondeandres** [comment]
@phuongnd08 we'll take a look at this

thanks for the report!
