### ISSUE TITLE
Duplicated method definition, differing method bodies.

### ISSUE THREAD

**Issue by shanemcd** [rollbar/rollbar-gem#230]
I was digging around and noticed that the `schedule_payload` method is defined both [here](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L453) and [here](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L594) in the same file.

**Comment by brianr** [comment]
Huh, indeed it is.

@jondeandres , any idea how this happened? We want the... second one, right?

**Comment by jondeandres** [comment]
@brianr seems that the old method was added in https://github.com/rollbar/rollbar-gem/pull/142, when we  changed to the new interface.

We want the second one yes, so this is not having impact. I'll open a PR removing the first one.

@shanemcd thanks for warn us of this :-)

**Comment by brianr** [comment]
Merged, thanks @jondeandres and @shanemcd !
