### ISSUE TITLE
Rollbar connection behind proxy

### ISSUE THREAD

**Issue by bighoax** [rollbar/rollbar-gem#232]
Hello,

My app is currently running in the secure environment behind a firewall. Almost all inbound/outbound requests are blocked. And you have to be on the VPN to access that app.

My suggestion to the corporate business team was to try the rollbar because I use it successfully in my hobby projects. However because the rollbar.com is unreachable from my server this is an issue. 

I use roll bar like this, where `e` is the Error:

```
Rollbar.error(e)  
```

1. What host/port/methods or what else do I need to enable on the firewall to make this connection possible? 
2. Do I need to do any changes in the code/config of this gem? 

I'm using rails `3.2.18` not sure if that is relevant or not.

**Comment by brianr** [comment]
Hi @bighoax,

If you can open up the firewall to `api.rollbar.com` on port 443, that should be all that you need. Would that work?

**Comment by bighoax** [comment]
@brianr 

Thanks for the response. We don't use `https` in this app, because anyone accessing the app has to be on the VPN. Is that still the case, that we need to open port 443?

**Comment by brianr** [comment]
@bighoax Yes, even if your app isn't serving on HTTPS, it (presumably) will be making outbound connections to Rollbar over https.

If for some reason that's not possible, you'll want to set the `config.endpoint` to use regular http, like this:

```ruby
Rollbar.configure do |config|
  config.endpoint = 'http://api.rollbar.com/api/1/item/'
end
```

If that's the case then you would want to open up `api.rollbar.com` on port 80.

**Comment by buggle** [comment]
Is there any other way to configure rollbar to use a http[s] proxy? 

I am working in a very strict environment where all outgoing connections *must* go through a proxy and there is no way to open up firewall ports. We would love to try and use rollbar, yet I have not figured out how this would be possible. 
(Using ruby and JS rollbar)

**Comment by jondeandres** [comment]
@buggle you can change the Rollbar endpoint to be your proxy, and configure your proxy to make requests to our API.

Would this work for you?

In order to change Rollbar endpoint:

```ruby
Rollbar.configure do |config|
  config.endpoint = your_proxy_url
end
```

**Comment by buggle** [comment]
Thanks for that impressively quick reply! 
We'll go and check with our Sysads if we can arrange it that way.
