### ISSUE TITLE
custom_data_method controller context

### ISSUE THREAD

**Issue by bhh** [rollbar/rollbar-gem#237]
maybe its just me but how do u guys use the custom_data_method because it seems i dont have any controller access. in which context is custom_data_method called? i only can find the notifier class.

maybe i use it awfully wrong but atm it seems it can only be filled with static data. cant find any dynamic examples

**Comment by jondeandres** [comment]
@bhh you are right. that method doesn't receive actually any request or context. it can however useful if you need some dynamic data from the host or something.

we have in our roadmap improve that so the defined method receives the current scope, where you will be able to get the request or other data.

Thanks for remind us this :smile:

**Comment by fabn** [comment]
@jondeandres additionally to scope it would be nice to have access (and it should be easier to do) to current exception. For instance I'm dealing with `RestClient::UnprocessableEntity` exceptions and the actual error message is attached to body. Currently I'm sending the error with this code but it's pretty ugly and not thread safe:

```ruby
  config.custom_data_method = lambda do
    if RestClient::Exception === $!
      {
          status_code: $!.http_code,
          errors: (JSON.parse($!.http_body) rescue $!.http_body),
      }
    end
  end
```

**Comment by jondeandres** [comment]
Good point @fab, I agree with you. We'll notice you when we progress on this.

Thanks both!

**Comment by fab** [comment]
Wrong @fab. I think you meant @fabn

**Comment by jondeandres** [comment]
Yah, sorry @fab :smile:

**Comment by fab** [comment]
No worries. It happens every now and then. Probably also because I've contributed to this gem in the past :)

**Comment by saulcosta18** [comment]
Has work been done on this, or do you have a few files you can point me to so I can get started with it?

**Comment by jondeandres** [comment]
@saulcosta18 we know having access to the request in order to send custom data is a very requested and we have plans to do this soon.

The idea would be set a new key in the scope generated by the middleware, for ex in `rollbar-gem/lib/rollbar/middleware/rails/rollbar.rb` and evaluate that value, that should be a `Proc` in `lib/rollbar.rb`, on `#build_payload` method.

We plan to do as soon as we can. Sorry for the inconveniences.

**Comment by ajsharp** [comment]
Any movement on this? It would be good if we could just pass a symbol of a controller method name that would get called.

**Comment by ArturMoczulski** [comment]
@ajsharp I am working on implementing this right now. Should have a pull request ready sometime this week.

**Comment by siav92** [comment]
Does this solution only work for caught exceptions that are reported manually. Is there a way to include additional controller data for exceptions that get reported automatically?

**Comment by waltjones** [comment]
@siav92  `e.rollbar_context` may do what you need: https://docs.rollbar.com/docs/ruby#error-contexts

This assumes you have access to the error object at some point while you also have the controller data. For example, you are raising the exception, or you are rescuing and re-raising it.

Also, it doesn't get sent to `custom_data_method`, but is added to the payload as is. (It is merged with the result of `custom_data_method` and any other custom data.)
