### ISSUE TITLE
Rollbar not scrubbing params in the URL

### ISSUE THREAD

**Issue by petelacey** [rollbar/rollbar-gem#239]
I am forcing an exception in my app with a URL such as this: https://example.com/boom?password=sekret (this example is contrived from a real world use case).  When I view the resulting rollbar item, the password is very visible in the URL, though it is in fact scrubbed from the params listed in the occurrences page.  But even then, if the URL was malformed in some way, for instance `?foo=bar?password=sekret` (two question marks), the password _is_ visible in the params listed on the occurrences page.

I'm happy to provide any assistance in getting this fixed.  Just let me know what you might need

**Comment by jondeandres** [comment]
@petelacey that's in a Rails app? Sinatra? Could you paste here how look the `params` object in the controller? 

I'll take a look at this.

Thanks!

**Comment by petelacey** [comment]
Yes, Rails 3.2.21. And Rollbar gem 1.5.1

Here's the dummy URL I tested with locally: `http://127.0.0.1:3000/boom?password=foo&bar=qux?passwd=bad-query-string`

The resulting rollbar page shows:
`URL	GET http://127.0.0.1:3000/boom?password=foo&bar=qux?passwd=bad-query-string` 
```
Params	

action     index
bar        qux?passwd=bad-query-string
controller boom
password   ***
```
Notice how the password is starred out in the params list, but not for the badly formed bit and not in the URL displayed.  It's also visible wherever the URL is displayed; in the curl replay command, the raw JSON, etc.

The actual Rails params look like this:
```
{"password"=>"foo",
 "bar"=>"qux?passwd=bad-query-string",
 "action"=>"index",
 "controller"=>"boom"}
```

**Comment by jondeandres** [comment]
So yo would like to obfuscate the whole value in `bar`? Or just `bad-query-string` in there?

We'll think about this and add it to our TODO.

Thanks @petelacey :smile:

**Comment by petelacey** [comment]
@jondeandres Don't get me wrong, the issue of sensitive data not being scrubbed in the params list if the query string is malformed is an edge case.  There are lots of ways of screwing up a URL that could end up leaking data.  Ideally, it should be addressed, but it's not the main issue.

The main issue is that sensitive data is not scrubbed from the URL _when it is well formed_.  And that URL is visible in the Rollbar UI and stored in your servers and logs.  In other words, what I would like to see is that before the URL leaves our servers, it is scrubbed to look like this: `http://example.com/boom?password=[FILTERED]&bar=qux`

**Comment by jondeandres** [comment]
Ah @petelacey, I understood wrongly. I'll test that and fix it soon.

Thanks!

**Comment by plehoux** [comment]
@jondeandres  when should we expect a fix?

**Comment by jondeandres** [comment]
@plehoux we'll try to prioritize this, but I can tell you a fixed date for it.

Thinking on a the problem itself, I'm not sure if this is a responsability of the rollbar gem. I mean that it may difficult detect when a URL is malformed or not, since that could depend on the project. And probably any solution will fit everybody needs.

**Comment by rafBM** [comment]
@jondeandres Just making sure you remember the main issue is not about malformed URL but well-formed ones:

> The main issue is that sensitive data is not scrubbed from the URL *when it is well formed*. And that URL is visible in the Rollbar UI and stored in your servers and logs. In other words, what I would like to see is that before the URL leaves our servers, it is scrubbed to look like this: `http://example.com/boom?password=[FILTERED]&bar=qux`

**Comment by jondeandres** [comment]
Mmmm, ok, re-read the issue and thought thi was just for URLs with two question marks.

We'll try to prioritize this, although seems we'll need to rebuild the URL in some way having filtered params before.

Thanks @rafBM.
