### ISSUE TITLE
Implicitly reporting extra data for certain exception classes?

### ISSUE THREAD

**Issue by DMA57361** [rollbar/rollbar-gem#241]
We have a exception raised in one of our apps when making a call to another of our app's APIs whenever the return indicates the call was invalid for some reason. The exception is a custom class that takes a few extra bits of data - about the type of call been made and the params being passed - and stores them internally. Currently, these are appended to the exception message, which is pretty ugly.

What I'd like to do is pass that extra data as a hash into a `Rollbar.warning` call and remove it from the exception message. However, we don't want to issue a report to Rollbar at the point where the exception is raised and the exception could potentially be rescued in many different places (or even left uncaught if something has gone seriously wrong), so adding special handling for this type of exception to each possible rescue location isn't feasible.

Ideally, Rollbar should know to report certain bits of extra data whenever classes of this type are reported. Is there currently a way to achieve this?

**Comment by jondeandres** [comment]
@DMA57361 cannot you avoid raising the exception and just send the report to Rollbar?

We have in our roadmap change the configuration option `custom_data_method` so it receives the request and the exception. This should be enough in the future to send whatever data you want.

I cannot tell you when this feature will be done, but you may consider just send a report to rollbar instead of raising it?

Thanks for the suggestion @DMA57361!

**Comment by DMA57361** [comment]
We probably could change to not using an exception here, but it's the single point of entry (exit?) from this app to the API and is used in _a lot_ of places. It's useful to have an exception raised on invalid calls as it prevents accidentally trying to use a duff response and having unexpected stuff happen elsewhere. We don't want all cases reporting to Rollbar though; some get caught and handled. However, all this is really our problem. What we've got now works, it's just ugly; don't worry about it.

It does sound like `custom_data_method` getting passed the exception could effectively do what I'd hoped, will look forward to it appearing sometime in the future.

**Comment by jondeandres** [comment]
@DMA57361 yah, probably you have some clean options to do that in your side.

But definitely, having a vitamined `custom_data_method` will be the best for everybody. We'll work on this soon.

**Comment by jondeandres** [comment]
This can be resolved with https://github.com/rollbar/rollbar-gem#transform-hook.
