### ISSUE TITLE
99% of my logs are "Empty Message"

### ISSUE THREAD

**Issue by Fabs** [rollbar/rollbar-gem#247]
I just made the default installation of the lastest version of rollbar-gem on my rails api, and 99% of my errors are uncaught exceptions of wrong coding. I though that if I turned rollbar on I would get those errors nicely grouped on the dashboard, but instead I get 99% of then as being "Empty Message". 

If I open then on the Ocurrences tab, I can see their diferences, but that is not quite what i was expecting. 

Is there a way i can configure the gem to give me a string representation of the error message, like the first line that preceds a stack trace: 

`NoMethodError - undefined method iDoNotExist ` for instance.

I do net to be the default behaviour of the gem, but to be able to set it.

I have
```
config.populate_empty_backtraces = true

ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

Rails 4.2.1

/Users/fabsn/.rvm/gems/ruby-2.2.0@dentaloffice/gems/rollbar-1.5.3

```

**Comment by jondeandres** [comment]
@Fabs how are using the gem? Are you reporting manually messages to our API?

`Empty message` is the title for send messages that doesn't have a message value.

**Comment by Fabs** [comment]
I am not reporting anything manually. I just plugged the gem on the rails app.

Maybe I am not the usual usecase. My problems are legacy errors that throw unhandled exceptions over the application. When this happens, I get empty message. I was wondering if I could tweak somewhere so instead of this "Empty Message" I could get, lets say, the Exception as string, or the url of where it happend, or the line of code. Something that on the dashboard would allow me to better trial and solve those mistakes.

**Comment by jondeandres** [comment]
@Fabs the normal behavior is just how you've explained it. The title is the exception message, you can see the backtrace, url, controller, action etc...

I can't understand why you are sending thos empty messages. Could you add a debugger in https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar.rb#L121 and paste as the backtrace and that point?

**Comment by lastobelus** [comment]
@Fabs, did you resolve this? I am having a similar issue in a rails app to which I just added rollbar.

**Comment by lastobelus** [comment]
I put in some log statements at the suggested point and quickly realized the problem was an interaction with the gem better_errors.

I can see that the gem has code intended to work with better_errors; perhaps that gem has changed recently?

After disabling better_errors, rollbar notifications were as expected with class, message, backtrace. Before all errors raised app classes had no class and Empty Message.

**Comment by jondeandres** [comment]
@lastobelus did you find exactly which problem between rollbar and beter_errors exists? could you give me some idea about how to reproduce this?

Thanks

**Comment by lastobelus** [comment]
@jondeandres Unfortunately I didn't dig deeper since with better_errors in the :development gem group, Rollbar error notification works correctly on staging/production.

**Comment by jondeandres** [comment]
@lastobelus that could be useful for us. we'll try to reproduce this soon.

sorry for the inconveniences. we'll contact you.

**Comment by erichaase** [comment]
I was also getting the `Empty message` Rollbar entries in development. I was able to resolve this by disabling/removing the `better_errors` gem as @lastobelus suggested, thanks!

**Comment by antek-drzewiecki** [comment]
I can verify that the `better_errors` hook would send my errors twice.
