### ISSUE TITLE
`report_validation_errors_to_rollbar` should be mixed into ActiveModel, not ActiveRecord

### ISSUE THREAD

**Issue by rmm5t** [rollbar/rollbar-gem#248]
Currently, `report_validation_errors_to_rollbar` is mixed into `ActiveRecord` only. Instead, it should be mixed into `ActiveModel`, since validations are tied directly to `ActiveModel`, and this would allow validation reporting to other `ActiveModel` compatible ORM/ODMs like Mongoid, etc.

**Comment by jondeandres** [comment]
Good point @rmm5t, we'll fix this soon.

Thanks!

**Comment by jondeandres** [comment]
This is fixed in https://github.com/rollbar/rollbar-gem/pull/503.
