### ISSUE TITLE
Ability to ignore/set level based on request data

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-gem#249]
For example, it could be useful to ignore errors coming from a particular IP address or user agent.

This would probably look similar to `exception_level_filters`, or maybe to rollbar.js's `checkIgnore`.

**Comment by nicolaracco** [comment]
+1 for this. I'm having a lot of routingerror events and I cannot determine whether to ignore or notify them using the request url.

**Comment by joshminnie** [comment]
+1, I need this exact thing.

**Comment by jondeandres** [comment]
@joshminnie we expect to add this pretty soon. Thanks for the +1.

**Comment by grosser** [comment]
```Ruby
# https://github.com/rollbar/rollbar-gem/issues/249
# ignore bot requests
module Rollbar::IgnoreBots
  def call(env)
    if env['HTTP_USER_AGENT'] =~ /MJ12bot/
      @app.call(env)
    else
      super
    end
  end
end

Rollbar::Middleware::Rails::RollbarMiddleware.prepend Rollbar::IgnoreBots
```

**Comment by jondeandres** [comment]
@grosser thanks for the tip, that'd be a solution for that. We'd like having a configuration option for this, so users don't need to monkey patch anything.

We'll work on this soon. Thanks.

**Comment by Crisfole** [comment]
This is solved by the recent release of the `transform` and `before_process` configuration methods.

**Comment by grosser** [comment]
this solution is a bit brittle (lots of nested hash accesses ... and a block call)
and it introduces overhead by raising and rescuing ...
ideally the hook should just return false and that's it ... not sure what else it would be useful for ...


```Ruby
  ignore_bots = lambda do |options|
    agent = options.fetch(:scope).fetch(:request).call.fetch(:headers)['User-Agent']
    raise Rollbar::Ignore if agent =~ OurBucketList::BOT_AGENTS
  end
  config.before_process << ignore_bots
```

**Comment by metaskills** [comment]
Thanks for that feedback @grosser - always good to find you around with top advice :)

I do agree that the nested hashes are kind of dirty, but it looks clean when using Hash#dig for those on later versions of Ruby. Same agreement on the usage of exceptions for control flow. That said, I am going to use that interface vs the sweet freedom patch you suggested with the idea being that this processing happens in the background when `use_async` is true? Can someone confirm that?

```ruby
 config.before_process << lambda do |options|
  agent = options.dig :scope, :request, :headers, 'User-Agent'
  raise Rollbar::Ignore if agent =~ /FatBot/i
end
```

**Comment by grosser** [comment]
looks about right ... but prefer a `throw` ... or a `return Rollbar::Ignore` or a `return false` to make this cheaper

**Comment by grosser** [comment]
.... misread your comment ...

exception_level_filters would be nice ... but could be as simple as allowing `return false` from before_process ... 

it should happen no matter what the use_async setting is, not sure why that is important
