### ISSUE TITLE
Retired EOL'd Ruby

### ISSUE THREAD

**Issue by joneslee85** [rollbar/rollbar-gem#255]
*What*: 1.8.7, 1.9.2 and 1.9.3 have reaches their EOL. Is there any plan to drop support for those Ruby?
*Why*: It is to me for the sake of gem maintenance. 

Please treat this issue just as a question.

**Comment by jondeandres** [comment]
Hey @joneslee85,

thanks for the proposal/question.

I think we'll still support those versions for now since we have customers still using those Ruby versions. But I agree with you in the "Why".

We'll discuss this internally. Thanks!
