### ISSUE TITLE
Framework-agnostic rake rollbar:test

### ISSUE THREAD

**Issue by joneslee85** [rollbar/rollbar-gem#262]
The implementation of `rollbar:test` is very Railsy, it does not take into consideration if the app is Sinatra or other Rack-based framework.

What should we do about it?

1) Perform extra check to ensure the app is Rails, else just say test raketask is not supported the platform
2) Having extra implementation for Sinatra and for Rack-based app
3) Just have one Rack-based app test code

**Comment by joneslee85** [comment]
cc @jondeandres @brianr

**Comment by jondeandres** [comment]
@joneslee85 the problem of a rack and sinatra rake task, is that there is not a standard way to configure the gems, like initializers in Rails. So each customer could have the Rollbar initialization in a different file, or in general, having booting process quite different.

Do you find a common way that will work for everybody?

Thanks.

**Comment by joneslee85** [comment]
@jondeandres I see. I think for the time being, we should only enable this rake task if the app is Rails only. I'll have a look into how we could do about with other framework.

**Comment by jondeandres** [comment]
@joneslee85 :+1:
