### ISSUE TITLE
Add ability to pass in access_token when logging

### ISSUE THREAD

**Issue by ptrln** [rollbar/rollbar-gem#275]
We would like the ability to optionally pass in an access_token when calling Rollbar.error(...) etc. We have many projects, and this would allow us to have better control of where the rollbars end up. We have monkey patched this internally, but it would be great if the gem could support this.

**Comment by randome** [comment]
:+1: For this

**Comment by brianr** [comment]
Thanks all - for reference, see the related discussion on this PR (which was merged and then reverted): https://github.com/rollbar/rollbar-gem/pull/276

**Comment by jondeandres** [comment]
@ptrln there is something you can do yourself in a clean way.

If you call `Rollbar.scope` you will receive a `Rollbar::Notifier` instance with its own configuration.

You can then configure that notifier in a independent way, ex:

```ruby
notifier_project1 = Rollbar.scope
notifier_project1.configure do |config|
  config.access_token = token_for_project_1
end

# And then you use that notifier instead of Rollbar constant:

notifier_project1.error(e)

```

This can be useful for manual reports. For automatic Rails reports then you can find a solution in https://github.com/rollbar/rollbar-gem/pull/276 as Brian suggested.

**Comment by jondeandres** [comment]
This can be done now easily with https://github.com/rollbar/rollbar-gem#override-configuration. Closing the issue.
