### ISSUE TITLE
Use 'default' Sidekiq queue

### ISSUE THREAD

**Issue by 1337807** [rollbar/rollbar-gem#281]
Is it possible to set the default queue for Sidekiq integration to the Sidekiq default queue 'default'? In the present state people have to either configure Sidekiq to pay attention to the 'rollbar' queue or tell Rollbar to use 'default'. Given that it's an officially supported method of async reporting it seems like it should 'just work' out of the box.

**Comment by brianr** [comment]
Seems reasonable to me. Is the standard sidekiq setup to just run a single queue called 'default'?

**Comment by 1337807** [comment]
Exactly. You can configure more of course and then use those with Rollbar if you'd like so you don't really lose anything with this change.

**Comment by jondeandres** [comment]
@1337807 we'll try to change this in a gem refactor we are thinking about.

Thanks

**Comment by daniely** [comment]
:+1: for this. I spent a few hours troubleshooting rollbar only to find it was because of the wrong queue name :(
