### ISSUE TITLE
Writing an application without an env causes misleading exceptions.

### ISSUE THREAD

**Issue by Senjai** [rollbar/rollbar-gem#294]
Given: https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/exception_reporter.rb#L10. An env must be passed in here which is then mutated by the function, otherwise we get an exception saying there was an exception while sending an exception to rollbar, even if the exception was posted successfully.

We now pass in just an empty hash so we dont get this warning, this makes working with the interface poor, should this just be a returned value? The exception that occurs here is misleading when caught below.

**Comment by jondeandres** [comment]
@Senjai what use case is this exactly?

You can just report to rollbar with `Rollbar.error`, or any other level: `info`, `warning`, `debug`, `critical`.

So you can avoid use that module or your purpose.

**Comment by brianr** [comment]
@jondeandres: the problem was that @Senjai was using `exception_reporter` in a plain ruby app, and was passing in a string as the `env`. But that method expects it to be a hash.

Could be a docs problem, or we could fix by making `exception_reporter` recover from the case where env is not a hash.

**Comment by Senjai** [comment]
Aye, I had hoped to use the exception reporter which looked to be made to handle unhandled exceptions by default. I went with that after looking at the other middleware implementations.

**Comment by jondeandres** [comment]
@Senjai 

At first moment we didn't thought `ExceptionReporter` to be part of our public interface, that's the reason cause it is not documented.

You can always use rollbar in this way:

```ruby
begin
  do_job
rescue => e
  rollbar_result = Rollbar.error(e)
  # do something with rollbar_result
end
```
This is enough to send rollbar reports in your own implementation.

Apart of this, you are probably right analyzing the interface of that module. Probably it'd be better with this signature:

```ruby
def report_exception_to_rollbar(exception, env = {})
```

So you have a default value for env. We'll analyze this change and the impact it can have for other customers.

**Comment by Senjai** [comment]
It's not documented, but it is the best way (IMO) to wrap an entry point by default. I would support the interface you suggested, perhaps by deprecating the old method, making a new method with a new name, and calling that with the old method. It might be better than some funky type checking.

**Comment by jondeandres** [comment]
@Senjai did you find any solution you are comfortable with? We think, if you want to use this module, just pass `{}` as the env. This module was thought to be used in our Rack based middlewares.

**Comment by Senjai** [comment]
@jondeandres The env should just be the last argument, as with most exception reporting libraries. The only thing actually required is the exception itself and the configuration to associate the acception with the rollbar account.

I do think there is value in makine the exception reporter a supported interface. The way you can fix this if you choose to is to deprectate the method, write a new method say `def rollbar` and use that internally with env as the last argument.

```ruby
def report_exception_to_rollbar(env, exception)
  ActiveSupport::Deprecation.warn("Method deprecated, blah, blah use rollbar instead")
  rollbar!(exception, env ||= {})
end

def rollbar!(exception, env = {})
  # old logic from previous method
end
```

Having this available as a mixin for anyone needing to use a custom reporting scenario is very helpful.
