### ISSUE TITLE
uninitialized constant Rollbar::Delay::GirlFriday error

### ISSUE THREAD

**Issue by longkt90** [rollbar/rollbar-gem#299]
Hi all,

I'm trying upgrade rollbar-gem version 1.5.2 to 2.2.1 and this config (from master readme, https://github.com/rollbar/rollbar-gem/blob/master/README.md)  will cause name error:
`config.failover_handlers = [Rollbar::Delay::GirlFriday, Rollbar::Delay::Thread]`

config/initializers/rollbar.rb:51:in `block in <top (required)>': uninitialized constant Rollbar::Delay::GirlFriday (NameError) 

remove Rollbar::Delay::GirlFriday like this works

`config.failover_handlers = [Rollbar::Delay::Thread]`

I'm using sidekiq: `config.use_sidekiq 'queue' => 'low'`
Any idea to fix?

**Comment by jondeandres** [comment]
@longkt90 have you required `rollbar/delay/girl_friday` and `rollbar/delay/thread` ?

Thanks

**Comment by longkt90** [comment]
Not yet, the only thing I require is `require 'rollbar/rails'` It seems work with old version 1.5.2.

Version  2.2.1 is OK with Rollbar::Delay::Thread but not Rollbar::Delay::GirlFriday
After I add require 'rollbar/delay/girl_friday', it works.

 Consider to add it to the document?

**Comment by jondeandres** [comment]
@longkt90 probably yes. We'll add that to the docs :smile:

Thanks!
