### ISSUE TITLE
Rollbar gem forces Oj

### ISSUE THREAD

**Issue by d4rky-pl** [rollbar/rollbar-gem#311]
Commit c5de06 added forced loading of Oj gem to handle JSON. This can cause unexpected problems with other gems like MultiJson that rely on autodetecting which JSON version to use. Unfortunately current version of Oj is broken (ohler55/oj#263) and is not able to serialize ActiveRecord relations properly.

Please consider using MultiJson instead and add disclaimer to README saying you prefer Oj instead.

**Comment by jondeandres** [comment]
Hi @d4rky-pl,

we have a PR for this, https://github.com/rollbar/rollbar-gem/pull/304. It'll be merge in next days. Our idea is try to use Oj when is available, if not just use the adapter detected by MultiJson.

**Comment by d4rky-pl** [comment]
@jondeandres oh, sorry for duplicate then :) Closing it now.

**Comment by jondeandres** [comment]
no problem @d4rky-pl, thanks!
