### ISSUE TITLE
Body params are skipped for Accept header

### ISSUE THREAD

**Issue by jingweno** [rollbar/rollbar-gem#314]
The code [here](https://github.com/rollbar/rollbar-gem/blob/4ef7656c463b2a13d38d4c2fd95b456e74d199c3/lib/rollbar/request_data_extractor.rb#L124) only parses the body if content type is "application/json", while typically the "Accept" header is used instead. For example, Accept=application/vnd.heroku+json; version=3. The current implementation causes a wide range of JSON request body not to be reported.

**Comment by jondeandres** [comment]
@jingweno good point, we'll change this later.

thanks for the tip!

**Comment by jondeandres** [comment]
Closed by https://github.com/rollbar/rollbar-gem/issues/322
