### ISSUE TITLE
Sidekiq report threshold

### ISSUE THREAD

**Issue by pacoguzman** [rollbar/rollbar-gem#318]
Rollbar extensions includes some configuration parameters to report error since a specific job attempt when using delayed job, but not when using Sidekiq.

Would you accept a PR that solve that?

**Comment by jondeandres** [comment]
@pacoguzman sure, feel free to open a new PR and we can then discuss over the code.

Thanks!

**Comment by pacoguzman** [comment]
@jondeandres I just created one #319

**Comment by jondeandres** [comment]
awesome :smile:

**Comment by aselder** [comment]
There is a big issue with this PR: https://github.com/rollbar/rollbar-gem/issues/345

**Comment by jondeandres** [comment]
This can be closed.
