### ISSUE TITLE
Stack level too deep when username is not defined in User model

### ISSUE THREAD

**Issue by MaicolBen** [rollbar/rollbar-gem#327]
Rollbar throws stack level too deep when a user a is logged and try to retrieve the username of the User model in [controller_methods.rb](https://github.com/rollbar/rollbar-gem/blob/1f8e8cb7454aa8080bb1d4d314411859da99896d/lib/rollbar/rails/controller_methods.rb#L14)

Reproduced with 1.4.5 and 2.3.0 versions

**Comment by jondeandres** [comment]
@MaicolBen do your `User` instances respond to `username`? Can you paste the backtrace?

Thanks.

**Comment by MaicolBen** [comment]
No, I added a method that responds with null to fix this(if you see this solution suitable, you can close this ). Also I tried to change the rollbar config for `config.person_username_method` and it doesn't work. The backtrace is a infinite prints of `log writing failed. stack level too deep`

**Comment by jondeandres** [comment]
@MaicolBen thanks for the details. Can you tell us which rails version are you using?

Thanks.

**Comment by MaicolBen** [comment]
@jondeandres Rails 3.2.11

**Comment by jondeandres** [comment]
@MaicolBen the logic we use to extract that date comes from:

```ruby
user = send(Rollbar.configuration.person_method)
        # include id, username, email if non-empty
        if user
          {
            :id => (user.send(Rollbar.configuration.person_id_method) rescue nil),
            :username => (user.send(Rollbar.configuration.person_username_method) rescue nil),
            :email => (user.send(Rollbar.configuration.person_email_method) rescue nil)
          }
        else
          {}
        end
      rescue NoMethodError, NameError
        {}
      end
```

It should't give problems since we rescue the exceptions. Could you investigate farther what is happening in your side?
