### ISSUE TITLE
build_payload triggers URI::InvalidURIError

### ISSUE THREAD

**Issue by fabn** [rollbar/rollbar-gem#330]
Getting a lot of these errors in the wild

```
Failsafe from rollbar-gem. URI::InvalidURIError in .../1.9.1/uri/common.rb:176:in `split': build_payload in exception_data
```

I think the cause might be [this line](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/scrubbers/url.rb#L24) but I don't have any clue on how to reproduce this because request data are not reported in rollbar and I can't find them in any log.

This is very annoying and I want to prevent this error to remove some noise from my RB account.

**Comment by jondeandres** [comment]
@fabn any idea about the URL you are trying to parse?

This is Ruby 1.9.1?

**Comment by fabn** [comment]
> @fabn any idea about the URL you are trying to parse?

No, it's a report from a high traffic app, I get this few times per day. I think that is caused by some misbehaving bot that sends out bad UTF-8 data in some header or query param.
 
> This is Ruby 1.9.1?

No, current code is running on latest 1.9.3 MRI that 1.9.1 is part of library path created by rvm, full path is this
```
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/uri/common.rb:176
```

This is specific to my app however I think the point here is that you should provide the option to save a full dump of the report data somewhere in the filesystem in [these lines](https://github.com/rollbar/rollbar-gem/blob/574b14717aa37728c22e1e66c600cb3e119280e0/lib/rollbar.rb#L143-L149) in order to diagnose this kind of issues.

**Comment by jondeandres** [comment]
@fab thanks for the info. we will rescue from `URI::InvalidURIError` which is probably the best idea since  `URI` behavior changes with different Ruby versions. About logging the dump, you are totally right. We'll try to improve this.

I'll close this issue once we merge a fix for this.

Thanks Again

**Comment by fabn** [comment]
Another issue I'm getting (partially related to this issue) is this

```
Failsafe from rollbar-gem. NoMethodError in rollbar-2.5.1/lib/rollbar/util.rb:69:in `block in deep_merge': build_payload in exception_data
```

Also in this report I'm completely losing context of the error and it's hard to diagnose.

In my opinion you should really add exception message in [this code](https://github.com/rollbar/rollbar-gem/blob/574b14717aa37728c22e1e66c600cb3e119280e0/lib/rollbar.rb#L626-L633), in this way at least some info are preserved in error messages. 

Assuming the above error is generated from something like a nil value, i.e. `nil.some_method` you should report instead of exception class only

``` 
Failsafe from rollbar-gem. NoMethodError: undefined method `some_method' for nil:NilClass in ...whatever
```

**Comment by jondeandres** [comment]
@fab we've fixed your issue, we'll release a new version soon. we will probably improve the logging quality so it's easier for everybody figure out what happens in some cases.

Thanks for everything.

**Comment by fab** [comment]
@jondeandres wrong Fab. You probably mean @fabn

**Comment by jondeandres** [comment]
Oh yes, sorry @fab!!
