### ISSUE TITLE
Allow scoping request data

### ISSUE THREAD

**Issue by marktermaat** [rollbar/rollbar-gem#334]
With scopes it's possible to customize the payload. However, it's not possible to customize the person, request and context data, because this data is added after the scope is applied. This is because in lib/rollbar.rb#build_payload the following line:

    Rollbar::Util.deep_merge(data, configuration.payload_options)

is before the following lines:

    data[:person] = data[:person].call if data[:person].respond_to?(:call)
    data[:request] = data[:request].call if data[:request].respond_to?(:call)
    data[:context] = data[:context].call if data[:context].respond_to?(:call)

Is it possible to change the order of these lines, so that scopes can actually modify the content of the person, request and context data? Or is there a good reason not to?

**Comment by marktermaat** [comment]
Another solution would be to make it possible to scrub fields for a certain notifier. Something like this:

    Rollbar.notifier.configuration.scrub_fields |= [:updates]

However, this doesn't work because lib/rollbar/request_data_extractor#sensitive_params_list uses 'Rollbar.configuration.scrub_fields', instead of 'Rollbar.notifier.configuration.scrub_fields'. This might be an interesting addition too, so it's possible to scrubs additional fields for a certain notifier.

**Comment by jondeandres** [comment]
@marktermaat our middleware use `Rollbar.scoped` to set the person and request information. Have you tried that?

https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/middleware/rails/rollbar.rb#L22-L47

**Comment by jondeandres** [comment]
This is fixed now and users should be able to customize the scope since now it's merged at once.
