### ISSUE TITLE
nil value for Rollbar::Util.deep_merge first argument

### ISSUE THREAD

**Issue by fabn** [rollbar/rollbar-gem#358]
With release 2.7.0 I got the actual error message for the issued described in #354 that is

```
Failsafe from rollbar-gem. NoMethodError: "undefined method `[]' for nil:NilClass" in lib/rollbar/util.rb:70:in `block in deep_merge': build_payload in exception_data
```

So instead of the patch discussed [here](https://github.com/rollbar/rollbar-gem/pull/354#discussion-diff-46841517L69) the right fix should check if `hash1` is nil.

However I don't know how to handle that case because I don't know the semantic of that method.

Looking at the code a simple `hash1 ||= {}` before the `each_key` loop may fix the issue but I don't know what consequences may have on the other code, so I won't submit a PR for that.

**Comment by jondeandres** [comment]
Thanks for this investigation @fabn. We'll try to reproduce this and fix this soon.

Your solution may work, but we will need to check exactly what is happening.

Thanks for this!
