### ISSUE TITLE
Separate ActionController::RoutingError

### ISSUE THREAD

**Issue by ngelx** [rollbar/rollbar-gem#360]
Hi, there is any way to separate distinct ActionController::RoutingError depending on the route failing as different items? 

Thanks

**Comment by jondeandres** [comment]
Hi @ngelx, we are looking for a solution for this. We'll contact you then we figure out the easiest way to do this.

**Comment by ngelx** [comment]
Thanks @jondeandres . any luck so far?

**Comment by brianr** [comment]
Hi @ngelx - this is actually possible to set up via the Rollbar UI, using Custom Grouping. Here's a blog post with an example that I think is exactly what you want to do: https://rollbar.com/blog/post/2014/06/10/More-Powerful-Custom-Grouping

Let us know if this works :)

**Comment by ngelx** [comment]
Sorry guys, it workd like a charm adding this rule to group

```
[
  {
    "title": "{{ body.trace.exception.class }} {{ body.trace.exception.message }}",
    "fingerprint": "{{ body.trace.exception.class }}-{{ body.trace.exception.message }}",
    "condition": {
      "path": "body.trace.exception.class",
      "eq": "ActionController::RoutingError"
    }
  }  
```

Thanks!
@ngel
