### ISSUE TITLE
Rollbar.js via asset pipeline?

### ISSUE THREAD

**Issue by hakunin** [rollbar/rollbar-gem#365]
Hi,
it would be nice if we could require Rollbar.js via asset pipeline from this gem.

Some people may prefer to have it in the body itself, I always serve it from application.js so it would be super easy to keep it up to date if it was just required from the gem itslef.

**Comment by jondeandres** [comment]
@hakunin sounds like a good idea, let's see if we can do this soon. We'll contact you.

Cheers!

**Comment by hakunin** [comment]
Sorry to bother you here guys, but as of this morning (7hrs ago), I am unable to access my account and it says its not even there (password reset). I've contacted you via email and twitter but no one responded to me. 

My account's email is `michal.hantl@gmail.com` and is tied to this github account.

**Comment by jondeandres** [comment]
@hakunin this was released in previous versions of the gem. just upgrade to the latests one and you'll have it.

take a look at the documentation in https://github.com/rollbar/rollbar-gem#integration-with-rollbarjs

Thanks!
