### ISSUE TITLE
Don't explicitly rely on rails

### ISSUE THREAD

**Issue by Crisfole** [rollbar/rollbar-gem#370]
https://github.com/rollbar/rollbar-gem/blob/master/Gemfile#L13

Remove the explicit rails dependency

**Comment by jondeandres** [comment]
@Crisfole what is the purpose of this?

**Comment by brianr** [comment]
I think the confusion is that there is a Gemfile in the main repo, which has 'rails' in it, even though Rails isn't actually a runtime dependency (since the gemspec is what really matters).

@jondeandres Do we need that Gemfile for anything? If not, let's remove it.

**Comment by jondeandres** [comment]
We use on travis the gemfiles in `gemfiles/` folder. But in general is suitable and common having a Gemfile.

If not we need always, on development to use `BUNDLE_GEMFILE=path-to-gemfile-in-gemfiles-folder bundle install` for ex.

For fast development and easier workflow, I think it's better having the Gemfile. Also, for users that want to open a PR they will expect that `bundle install` works without any environment variable. The Gemfile is here for development, it's not part of the gem itself.

**Comment by Crisfole** [comment]
This was a misunderstanding
