### ISSUE TITLE
#145 Failsafe from rollbar-gem. ArgumentError: "invalid byte sequence in UTF-8" in /usr/local/rvm/gems/ruby-2.2.1/gems/rollbar-2.7.1/lib/rollbar/request_data_extractor.rb:197:in `=~': build_payload in exception_data

### ISSUE THREAD

**Issue by codem4ster** [rollbar/rollbar-gem#389]
We are getting this error so much. Once every 20 minute. What is the reason of this error, how can we avoid this?

**Comment by jondeandres** [comment]
@codem4ster can you send us an email to support@rollbar.com and tell us your account name and project?

Do you have any chance to start a debugger before that line and inspect the variables there?

**Comment by codem4ster** [comment]
@jondeandres I found the problem. '=~' operator doesn't work on non UTF-8 encodings. We try sending data to rollbar which we get from an external service. This service sends us ISO-8859-9 encoded data. I solved my problem by force_encode('ISO-8859-9').encode('UTF-8'). 

If you want to solve this globally, you can reproduce the error by doing these;
- create a file in text editor
- write into it 'ŞşĞğİıÇçÜü' and save as ISO-8859-9 (Turkish) encoded
- in a ruby script File.read() this file
- try to use '=~' operator on taken string

If you can solve this, can you share with me? I would be very appreciate.

**Comment by jondeandres** [comment]
@codem4ster awesome, thank you very much for the details. We'll will work on a fix as soon as possible and we'll contact you, ok?

Thank you very much!
