### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Crisfole** [rollbar/rollbar-gem#415]
Our documentation currently states that the exception level filters should be set to `ignore`, but the code uses `ignored` in some places instead:

 * https://github.com/rollbar/rollbar-gem/blob/1f8e8cb7454aa8080bb1d4d314411859da99896d/lib/rollbar/exception_reporter.rb#L14
 * https://github.com/rollbar/rollbar-gem/blob/8dea6218527b0b2fbbb6e042f4aca407c746d9cd/lib/rollbar.rb#L129

We should be consistent and stick with just one of them.

**Comment by jondeandres** [comment]
The docs are ok, we return `'ignored'` when the report is ignored by the library but the `exception_level_filters` option expects `'ignore'` in the configuration `Hash`.
