### ISSUE TITLE
Sidekiq 4.x scope side effects

### ISSUE THREAD

**Issue by ryansch** [rollbar/rollbar-gem#416]
I was doing a code review of this gem before adoption and I noticed that there isn't any code to clear thread locals between sidekiq jobs.  Since sidekiq 4.x (and maybe earlier?) reuse `Processor` threads to run more than one job (https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L66-L68), if I use `Rollbar.scope!` to mutate the current scope I think there may be side effects for the next job.  I would expect to see sidekiq middleware that calls `Rollbar.reset_notifier!` before calling `yield`.

Note that the easiest way to test this would be to run sidekiq with only one `Processor` thread.

**Comment by jondeandres** [comment]
Hey @ryansch, thanks for creating the issue, we'll take a look at this. Will `Rollbar.scoped` help you with your issues? You can always create a new notifier with `Rollbar.scope` and use the returned object instead of using `Rollbar`.

**Comment by ryansch** [comment]
We have a multi-tenant app.  I'd much rather be able to create a piece of sidekiq server middleware to inject the current tenant information into the scope with `Rollbar.scoped!` instead of having to pass scope objects around.  We have _many_ workers that call different service objects and it's infeasible to change all that code.

We're evaluating rollbar while we're currently using honeybadger.  With their stuff I can just call `Honeybadger.context` and it works great.  I'm looking for the same experience here.

**Comment by jondeandres** [comment]
Thank you very much for the information @ryansch, we'll try to fix this as soon as possible. We'll contact you in this issue.

Thanks!

**Comment by jondeandres** [comment]
Hi @ryansch, we've fixed and closed this issue. Thank you very much for reporting this, since it was a real bug.

We hope you integration with Rollbar is successfuly, and don't doubt in open any other issue if you have questions, problems with it or you want to purpose something new, improvements, etc...

Thanks again.
