### ISSUE TITLE
Use delayed_job for asynchronous reporting

### ISSUE THREAD

**Issue by tarr11** [rollbar/rollbar-gem#419]
Is it possible to use delayed_job (instead of sidekiq, resque) or similar to process rollbar errors asynchronously?  I have a heroku app and do not want to install redis.

**Comment by jondeandres** [comment]
Hi @tarr11, if `Delayed` is loaded at the moment that Rollbar is configured, we'll wrap Delayed so the error reports as sent using it.

**Comment by tarr11** [comment]
Hi @jondeandres - I meant the other way around, so that when a message is sent to rollbar, we can use delayed_job as the queue.

**Comment by jondeandres** [comment]
Ah ok @tarr11, sorry I misunderstood. We don't support DelayedJob as async handler, give us few days and we'll work on it.

I reopen the issue so we'll contact to you again. Thanks a lot.

**Comment by jondeandres** [comment]
This is currently supported in the gem. Closing.
