### ISSUE TITLE
Prevent rollbar from reporting SEO scrawlers activities.

### ISSUE THREAD

**Issue by anocriny** [rollbar/rollbar-gem#428]
How to prevent rollbar from reporting SEO scrawlers activities. SEO scrawler can be determined by rollbar browser type (i.e Google, Baidu, findxbot, etc..). How to block rollbar from doing exception report when these SEO scrawler produces recordnotfound error when it try to access deleted record.

**Comment by jondeandres** [comment]
@anocriny take a look at https://github.com/rollbar/rollbar-gem#before-process-hook and https://github.com/rollbar/rollbar-gem#the-scope. You can raise an exception in that configuration block. So you'll need to check the request object there and raise the ignore exception if you want to skip that report.
