### ISSUE TITLE
Should use ENV.fetch instead of ENV[] when in environment variable mode

### ISSUE THREAD

**Issue by stevenpetryk** [rollbar/rollbar-gem#429]
In the generated `rollbar.rb` initializer, `ENV.fetch` should be used. `ENV.fetch` throws an exception if the environment variable isn't present, which is much easier-to-debug behavior.

**Comment by jondeandres** [comment]
@stevenpetryk we use `config.environment = ENV['ROLLBAR_ENV'] || Rails.env`, so if there is not `ROLLBAR_ENV` variable we use the Rails environment.

We can change it to `ENV.fetch('ROLLBAR_ENV', Rails.env)` but I think the behavior is the same. So at the end `fetch` will not throw any exception.

**Comment by stevenpetryk** [comment]
Ah, I see. This should be fine then.
