### ISSUE TITLE
Rollbar::Rake.rake_version returns nil [ fixed in #397 but not included in latest build ]

### ISSUE THREAD

**Issue by vasspilka** [rollbar/rollbar-gem#441]
**NOTE**
This issue is fixed in mater!!!
If you are experiencing this a solution is
`gem 'rollbar', github: 'rollbar/rollbar-gem', branch: 'master'`
**END OF NOTE** 

So in `Rollbar::Rake.patch?` I get the following error 
```
NoMethodError: undefined method `split' for nil:NilClass
```
Upon investigating the gem it seems that `Rollbar::Rake.rake_version` returns nil.
what is even more strange is the following 

```
$ bundle exec rake rollbar:test
[1] pry(Rollbar::Rake)> show-source

From: /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rollbar-2.7.1/lib/rollbar/rake.rb @ line 5:
Module name: Rollbar::Rake
Number of lines: 33

module Rake
  def self.patch!
    skip_patch && return unless patch?

    ::Rake::Application.class_eval do
      alias_method :orig_display_error_message, :display_error_message

      def display_error_message(ex)
        Rollbar.error(ex, :use_exception_level_filters => true)
        orig_display_error_message(ex)
      end
    end
  end

  def self.skip_patch
    warn('[Rollbar] Rollbar is disabled for Rake tasks since your Rake version is under 0.9.x. Please upgrade to 0.9.x or higher.')
  end

  def self.patch?
    pry
    major, minor, *_ = rake_version.split('.').map(&:to_i)

    major > 0 || major == 0 && minor > 8
  end

  def self.rake_version
    if Object.const_defined?('RAKEVERSION')
      return RAKEVERSION
    elsif Rake.const_defined?('VERSION')
      return Rake::VERSION
    end
  end
end
[2] pry(Rollbar::Rake)> rake_version
=> nil
[3] pry(Rollbar::Rake)> Object.const_defined?('RAKEVERSION')
=> false
[4] pry(Rollbar::Rake)> Rake.const_defined?('VERSION')
=> true
[5] pry(Rollbar::Rake)> Rake::VERSION
=> "11.1.2"
[6] pry(Rollbar::Rake)> if Object.const_defined?('RAKEVERSION')    
[6] pry(Rollbar::Rake)*   return RAKEVERSION      
[6] pry(Rollbar::Rake)* elsif Rake.const_defined?('VERSION')      
[6] pry(Rollbar::Rake)*   return Rake::VERSION      
[6] pry(Rollbar::Rake)* end      
LocalJumpError: unexpected return
from (pry):8:in `__binding__'

[7] pry(Rollbar::Rake)> RUBY_VERSION
=> "2.3.0"

```
Monkey patching and removing the returns fixes the problem any ideas?

**Comment by vasspilka** [comment]
On further notice the whole syntax seems to be faulty check this
```
[13] pry(Rollbar::Rake)> if false 
[13] pry(Rollbar::Rake)*   return 0
[13] pry(Rollbar::Rake)* elsif true  
[13] pry(Rollbar::Rake)*   return 1
[13] pry(Rollbar::Rake)* end  
LocalJumpError: unexpected return
from (pry):34:in `__binding__'
```

**Comment by vasspilka** [comment]
Ok seems to be fixed by #397, but the problem remains that the latest build includes this bug, could you please do a later build that includes the fix

**Comment by jondeandres** [comment]
@vasspilka I'd say this is fixed in master but we didn't release a new version yet. We are working on a couple of features and we want to release all together.

**Comment by vasspilka** [comment]
Yea I figured, I am pulling from master for the time being, should I close this?
I think it might be a good idea to keep it open until next release as it was quite confusing for me :)

**Comment by jondeandres** [comment]
Hey @vasspilka, we released v2.10.0 a couple of days ago. We hope this is fixed now for you.

Thank you very much.

**Comment by halilim** [comment]
Hi guys, I'm sorry if this is not the right place to mention this, but since I couldn't determine the canonical issue about the <code>undefined method `split' for nil:NilClass (NoMethodError)</code> error, here it goes:

[Your Heroku docs](https://devcenter.heroku.com/articles/rollbar#using-with-ruby-rails) advise installing version `~> 1.2.7`, which totally throws this error. I could only find the resolution after hopping around several issues and trying version `~> 2.11`. Maybe you'd like to fix this usability issue :) Cheers.

**Comment by jondeandres** [comment]
Hey @halilim, those heroku docs seems to be very outdated. We'll need to change them. Last gem version is 2.11.3. We recommend you to use it.
