### ISSUE TITLE
Secure headers support doesn't compatible with secure_headers 2.x

### ISSUE THREAD

**Issue by juno** [rollbar/rollbar-gem#442]
Hi,

I updated rollbar to 2.10.0 and enable RollbarJS integration but `SCRIPT` tag will not inserted in response body. 😢 

The PR #437 sets `Rollbar::Railtie.initializer` after `secure_headers.middleware` but it's not exists in secure_headers 2.x.

* `railtie.rb` in secure_headers 3.0
https://github.com/twitter/secureheaders/blob/master/lib/secure_headers/railtie.rb
* `railtie.rb` in secure_headers 2.x
https://github.com/twitter/secureheaders/blob/2.x/lib/secure_headers/railtie.rb

Although secure_headers 3.0 is a current major version, the authors says "2.x will be maintained" in README.

**Comment by jondeandres** [comment]
Hey @juno, thanks for opening this issue and explain the problem. We'll try to fix this during this week.

Thanks again.
