### ISSUE TITLE
More useful error handling

### ISSUE THREAD

**Issue by MetricMike** [rollbar/rollbar-gem#446]
[Python implementation](https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L1227) recognizes some error codes and prints useful messages accordingly. Could this feature be ported to this gem?

**Comment by jondeandres** [comment]
@MetricMike we can do that, but for now check if this works fine for you:

We print this messages everytime the response code is not 200:

```ruby
if response.code == '200'
        log_info '[Rollbar] Success'
      else
        log_warning "[Rollbar] Got unexpected status code from Rollbar api: #{response.code}"
        log_info "[Rollbar] Response: #{response.body}"
      end
```

So we print a warning message with the `response.body` attached. The response body on a 429 is something like `Over rate limit. Access token: xxxxx`.

**Comment by jondeandres** [comment]
@MetricMike was my response enough for you?
