### ISSUE TITLE
Failsafe from rollbar-gem. ArgumentError: "wrong number of arguments (1 for 0)"  .../rollbar-2.7.1/lib/rollbar/core_ext/basic_socket.rb:4:in `as_json': error in process_payload

### ISSUE THREAD

**Issue by acaporrini** [rollbar/rollbar-gem#449]
We have a Sinatra application using rollbar-gem 2.7.1 and recently we have integrated ActiveRecord support in the application.

Immediately after that we started to receive this error: 

Failsafe from rollbar-gem. ArgumentError: "wrong number of arguments (1 for 0)"  .../rollbar-2.7.1/lib/rollbar/core_ext/basic_socket.rb:4:in `as_json': error in process_payload

I understand from  the changelog that this comes from  a patch created to avoid a bug  for ActiveSupport versions prior to  4.1.0, but our ActiveSupport version is 4.2.6. 

Why is this patch active in our configuration? 

Can we safely disable it through the configuration settings? 

Is there another workaround to solve the error?

Many thanks in advance.

**Comment by jondeandres** [comment]
Hi @acaporrini, sorry for this inconvenience. We'll need to investigate what is happening exactly in your scenario.

For the moment you can use this config `config.disable_core_monkey_patch = true` in your Rollbar configuration. This will disable that monkey patch.

Do you have a backtrace of this exception? We don't send it in failsafe errors to avoid possible bugs in the backtrace parsing.

Beside this, can you tell us if you have installed any other JSON serializing library? If you can paste your Gemfile it'd be very useful, or you can send it to us using `support@rollbar.com`.

Thanks and sorry for the inconvenience.

**Comment by fguillen** [comment]
Hi @jondeandres I have sent you an email ;)

**Comment by jondeandres** [comment]
This should be already fixed. Closing
