### ISSUE TITLE
Rollbar 2.8.3 Gem Requires Multi_json 1.5.0 or 1.6.0

### ISSUE THREAD

**Issue by catherine440** [rollbar/rollbar-gem#451]
The rollbar 2.8.3 gem (and likely everything since 2.4.0) is NOT compatible with all versions of multi_json as the gem claims it to be. The gem requires 1.5.0 (according to doc) or 1.6.0 (according to code) from my research. The problem code is line 26 in lib/rollbar/json.rb -- MultiJson.with_adapter, introduced in this PR: https://github.com/rollbar/rollbar-gem/commit/e33f10e7fb9d383b5ec76d675cee68d0ae31cd84 

Interestingly, the last change to json.rb claims to make it compatible with multi_json <= 1.6.0. That seems to have failed. This is the PR: https://github.com/rollbar/rollbar-gem/commit/06c1c749894dadd7ba2413c2c09460c3bb926c5c

More references: 
Doc for 1.5.0: http://www.rubydoc.info/gems/multi_json/1.5.0/MultiJson 
Doc for 1.4.0: http://www.rubydoc.info/gems/multi_json/1.4.0/MultiJson 

Code that shows with_adapter added in 1.6.0: https://github.com/intridea/multi_json/blob/master/lib/multi_json.rb

The solution which would get me unstuck the quickest would be to change your gem to require 1.5 or 1.6, then it would be pulled in for me automatically.

**Comment by jondeandres** [comment]
@catherine440 I think the commit https://github.com/rollbar/rollbar-gem/commit/06c1c749894dadd7ba2413c2c09460c3bb926c5c was related to some issues loading the adapter. Probably we missed that `with_adapter` doesn't exist in MultiJson < 1.5.0.

You are right on the solution. We'll need to require MultiJson >= 1.5.0. We hope we can do it in next days. Sorry for the inconvenience and thank you very much for this detailed analysis.

**Comment by catherine440** [comment]
Is there any update on this?

**Comment by coryvirok** [comment]
Sorry for the delay, @catherine440. @jondeandres is there a fix for this ready to be merged and released?

**Comment by jondeandres** [comment]
@coryvirok the fix would be immediate, but we should consider https://github.com/rollbar/rollbar-gem/pull/482.

**Comment by coryvirok** [comment]
Ah yes. If we can remove the dependency that'd be a better solution.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
