### ISSUE TITLE
Sidekiq process hangs

### ISSUE THREAD

**Issue by fschwahn** [rollbar/rollbar-gem#459]
Hi,
I'm seeing an issue with sidekiq, and rollbar is the only thing which hooks into sidekiq, so my guess something is off here (also, there were some changes in the sidekiq integration recently: #422, #421, #440).

Sometimes, my sidekiq processes just die, not processing any jobs anymore. There is no exception or anything, and the dashboard is not showing any job processing, only queued jobs. However, in the console I can see that jobs are started, but never complete or even show up in the dashboard as processing. After restarting the worker job processing continues normally. This seems to happen when a lot of jobs are processed simultaneously.

I'm using `rails 5.0.0.beta4`, `rollbar 2.10.0` and `sidekiq 4.1.1`.

**Comment by jondeandres** [comment]
Hi @fschwahn, are you able to fix the problem downgrading the rollbar gem version? I'd say we didn't do any change that could add this behavior.

Can you reproduce this in localhost?

**Comment by fschwahn** [comment]
I'm currently looking into this - my guess is now that one of the dependencies I'm using is not thread safe.  I'll reopen if necessary.

**Comment by jondeandres** [comment]
nice @fschwahn, if you find something interesting and you want to share it here, please do it! :smile: 

Thanks again.
