### ISSUE TITLE
Configuration to disable Rollbar.js script tag nonce

### ISSUE THREAD

**Issue by spdawson** [rollbar/rollbar-gem#462]
Commit 984c88f4290bb914a24bed90a0e66d8afb5c6525 added a `nonce` to the Rollbar.js script tag, to work around an issue when using the `secure_headers` gem with CSP nonces enabled, and `'unsafe-inline'` disabled.

However, this has now created a problem in the case where nonces are disabled, and the CSP has `'unsafe-inline'` enabled. Many third party tools (e.g. New Relic's `newrelic_rpm` gem) inject nonce-free script tags into the page; to support these, it is necessary to add `'unsafe-inline'` to the CSP. Unfortunately, the presence of the nonce attribute on the Rollbar.js script tag causes the CSP to ignore the `'unsafe-inline'` setting, which means that any injected nonce-free script tags will not run.

I suggest the addition of a configuration flag, to enable the Rollbar.js nonce attribute to be disabled; presumably, it is a sensible default position for the nonce to be enabled.

**Comment by jondeandres** [comment]
Hi @spdawson, thanks for open this issue. I'll take a look at this in next days. Thanks again and sorry for the inconveniences.

**Comment by ajgon** [comment]
Hey @spdawson 

Maybe it's better idea to check that in SecureHeaders configuration itself? So if `'unsafe-inline'` is enabled, nonce will be disabled by default?

**Comment by spdawson** [comment]
Thanks @ajgon; that looks like a nice solution which will "just work" from the perspective of an application that uses both Rollbar and `secure_headers`
