### ISSUE TITLE
Exception from Delayed::Job not reported if job fails to deserialize

### ISSUE THREAD

**Issue by adamniedzielski** [rollbar/rollbar-gem#472]
If Delayed::Job fails to deserialize a job it throws `DeserializationError`. This happens early in the process and the hook `lifecycle.around(:invoke_job, &Delayed::invoke_job_callback)` is not called.

Looking at the code it is rescued here https://github.com/collectiveidea/delayed_job/blob/1e679174b513dc711f7d764c8bd9d4f5c6495276/lib/delayed/worker.rb#L235-L237 and the only hook it calls is "failure".

Do you have any idea how we can account correctly for this case?

**Comment by jondeandres** [comment]
@adamniedzielski do you know the reasons of the `DeserializationError`? Do you think that has a relation with the gem itself? Or is just that you'd like to report this errors?

**Comment by adamniedzielski** [comment]
@jondeandres Thanks for your response!

The ```DeserializationError``` comes from the Delayed Job and has no relation with the Rollbar gem. I would like this ezception to be reported by Rollbar, because it prevents the job from executing and this is something I definitely want to be aware of :smile:

**Comment by adamniedzielski** [comment]
Quick way to reproduce the problem:
```ruby
"abc".delay.first(->{})
Delayed::Worker.new.run(Delayed::Job.last)
```

I think that now I understand why this gem uses ```around(:invoke_job)``` rather than ```after(:error)``` or ```after(:failure)``` - the exception is not available for these callbacks.

In order to have a basic reporting for jobs which failed even before the first execution we would have to add something similar to:

```ruby
class RollbarPlugin < ::Delayed::Plugin
  callbacks do |lifecycle|
    lifecycle.around(:invoke_job, &Delayed::invoke_job_callback)
    lifecycle.after(:failure) do |job|
      ::Rollbar.error("Delayed::Job ID=#{job.id} failed to execute") if job.attempts.zero?
    end
  end
end
```

**Comment by jondeandres** [comment]
Hey @adamniedzielski, thanks for this, we'll try to release a new version with this soon.

**Comment by adamniedzielski** [comment]
Thanks @richvorp! 💚 💯 🎉

**Comment by yoonwaiyan** [comment]
Really hope to get this released asap, delayed job failure is high in a server under my monitor.
