### ISSUE TITLE
Rollbar gem 2.11.3 reporting ignored errors as critical

### ISSUE THREAD

**Issue by rdlu** [rollbar/rollbar-gem#474]
Hi!

In one of our applications (TotalCommit/Easylive), I followed the docs about "Exception level filters" in my Rails app.

But instead of ignoring the errors, now errors like RoutingErrors are being reported as critical (was warning by default).

My initializer:

config.exception_level_filters.merge!({
                                              'ActionController::RoutingError' => 'ignore',
                                              'NoMethodError' => 'critical',
                                              'AbstractController::ActionNotFound' => 'ignore',
                                              'ActionController::InvalidAuthenticityToken' => 'ignore',
                                              'ActionController::ParameterMissing' => 'ignore',
                                              'ActionController::UnknownAction' => 'ignore',
                                              'ActionController::UnknownFormat' => 'ignore',
                                              'ActionController::UnknownHttpMethod' => 'ignore',
                                              'ActiveRecord::RecordNotFound' => 'ignore',
                                              'CGI::Session::CookieStore::TamperedWithCookie' => 'ignore',
                                              'Mongoid::Errors::DocumentNotFound' => 'ignore',
                                              'SignalException' => 'ignore',
                                              'SystemExit' => 'ignore'
                                          })

Rails 4.2.6
Rollbar 2.11.3

Any advice? Thanks!

**Comment by jondeandres** [comment]
@rdlu we've not done any change related to this in lasts releases. Can you try writing to stdout `Rollbar.configuration.exception_level_filters` after your `Rollbar.configure` block and share it here?

Thanks.

**Comment by jondeandres** [comment]
Hey @rdlu!

Any news on this?

**Comment by srg2k5** [comment]
This relates to #511 .   The circumstance that I can elaborate is the 404 is an unhandled error if you don't have a route specified to catch the 404.  That error is being grabbed and ignored according to Rollbar output.   However, what I can tell is after that, if you have this enabled Rails.logger.extend(ActiveSupport::Logger.broadcast(Rollbar::Logger.new)) the error get's passed back through as now critical, and the exception is null.   So it looks like rollbar can't determine that its a RoutingError since that part of the exception has been wiped out.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
