### ISSUE TITLE
Multiple sidekiq queues

### ISSUE THREAD

**Issue by pawel2105** [rollbar/rollbar-gem#476]
Is it possible to pass an array to `config.use_sidekiq` to specify multiple queues?

**Comment by jondeandres** [comment]
@pawel2105 what would be the intention of that?

**Comment by pawel2105** [comment]
@jondeandres if I have queues 'one' and 'two' and I want both of them to be registered, how would I do that?

**Comment by jondeandres** [comment]
@pawel2105 `config.use_sidekiq` enables the Rollbar reporting using a Sidekiq worker. The default queue name is `rollbar`, so you should have a worker listening to that queue. But you can change the queue name using:

```ruby
config.use_sidekiq 'queue' => 'default'
```

But I don't understand why you'd want to pass two queues there.

If you are talking about reporting Sidekiq errors to Rollbar, that's is done by default if `Sidekiq` is defined when Rollbar loads.

**Comment by pawel2105** [comment]
"If you are talking about reporting Sidekiq errors to Rollbar, that's is done by default if Sidekiq is defined when Rollbar loads."

Yeah I was under the impression that for each queue present in my Sidekiq config I'd have to specify that queue in the Rollbar config. Sorry for the confusion.
