### ISSUE TITLE
Email errors in ActionMailer::DeliveryJob are not reported

### ISSUE THREAD

**Issue by maxim** [rollbar/rollbar-gem#487]
The docs recommend to add this to your ActiveJob jobs:

``` ruby
include Rollbar::ActiveJob
```

However, rails has a built-in job called `ActionMailer::DeliveryJob` which is used when you call `deliver_later` on your action mailer emails. Currently errors in that job are not being reported.

I think it makes sense for this gem to automatically hook into that job as part of Rails integration.

**Comment by jondeandres** [comment]
@maxim yes, we will need to add our module to `ActionMailer::DeliveryJob` class. You can do this now for yourself until we do it

```ruby
ActionMailer::DeliveryJob.class_eval do 
  include Rollbar::ActiveJob
end
```

Thanks,

**Comment by sandlerr** [comment]
@jondeandres just wondering why this was closed? It looks like this still needs to be manually included?

**Comment by jondeandres** [comment]
@sandlerr you are right, reopening. Thanks!

**Comment by defkode** [comment]
this can also written even shorter:

```ruby
ActionMailer::DeliveryJob.include Rollbar::ActiveJob
```

**Comment by grzuy** [comment]
I see this was fixed a while ago but I suspect this is no longer working for Rails v6.0+ because of Rails switching from `ActionMailer::DeliveryJob` to `ActionMailer::MailDeliveryJob`?
