### ISSUE TITLE
Broken plugins documentation

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [rollbar/rollbar-gem#491]
The link here is a 404: https://github.com/rollbar/rollbar-gem#plugins

**Comment by jessewgibbs** [comment]
Hey Maciek,
That link is working for me.  Were you referring to a link on that page?

**Comment by jessewgibbs** [comment]
Thanks, fixing this right now.

**Comment by uhoh-itsmaciek** [comment]
Yeah, that was it--sorry I wasn't clear. Thanks!
