### ISSUE TITLE
Exceptions in threads are missing

### ISSUE THREAD

**Issue by nononoy** [rollbar/rollbar-gem#492]
HI. I have a small problem with rollbar-gem. Exceptions in threads are invisible, aren't they? May be sombody know actual rollbar-gem + thread usecases? How can I catch all exceptions in threads?

**Comment by jondeandres** [comment]
Hi @nononoy, sorry for the delay. If you want your threads to raise exceptions you should use http://ruby-doc.org/core-2.2.0/Thread.html#method-c-abort_on_exception-3D.

You can then catch the exception in the main thread. If not, you can always catch the exceptions inside your thread.

Cheers.
