### ISSUE TITLE
Why not use :extra for uncaught exceptions?

### ISSUE THREAD

**Issue by sogoodday** [rollbar/rollbar-gem#500]
Rollbar allows to report message, exception object, extra hash or any combination of them.
But default middleware for Rails wants report only message. 
Is there any reason why nobody extended ExceptionReporter with simething like
```ruby
....
exception_message = exception.respond_to?(:message) ? exception.message : 'No Exception Message'
...
exception_extra = exception.respond_to?(:extra) ? exception.extra : nil
exception_data = Rollbar.log(Rollbar.configuration.uncaught_exception_level, exception, exception_extra, :use_exception_level_filters => true)

```

**Comment by jondeandres** [comment]
@sogoodday we don't plan to support that, since `Exception` doesn't have a `#extra` method by default and all of this looks too custom.

But if you want to send custom data on a certain request you can use `Rollbar.scope!(extra_data)` on any point during your request. Would this work for you?

**Comment by sogoodday** [comment]
@jondeandres , ou, sorry. I see a good method Rollbar.scoped :)

**Comment by jondeandres** [comment]
Yes, you can wrap some code with `Rollbar.scoped(data) do` or you can mutate the scope with `Rollbar.scope!(data)`. In the middleware we reset always the scope so it's clean for the next request
