### ISSUE TITLE
Rake test task depends on Rack

### ISSUE THREAD

**Issue by yock** [rollbar/rollbar-gem#504]
The task to test Rollbar in version `2.12.0` of the Ruby gem requires `rack/mock` which is not a dependency in the gemspec. The task is therefore broken in apps not using Rails or using Rack directly.

https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/rake_tasks.rb#L2

The trace when running `rake rollbar:test`

```
I, [2016-08-04T10:56:06.649947 #63292]  INFO -- : [Rollbar] Scheduling item
I, [2016-08-04T10:56:06.650004 #63292]  INFO -- : [Rollbar] Sending item
I, [2016-08-04T10:56:06.804155 #63292]  INFO -- : [Rollbar] Success
I, [2016-08-04T10:56:06.804295 #63292]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=aecb88a6-a723-4f09-99e3-d36f8f62cfb8 (only available if report was successful)
rake aborted!
LoadError: cannot load such file -- rack/mock
<$HOME>/.gem/ruby/2.3.1/gems/rollbar-2.12.0/lib/rollbar/rake_tasks.rb:2:in `require'
<$HOME>/.gem/ruby/2.3.1/gems/rollbar-2.12.0/lib/rollbar/rake_tasks.rb:2:in `<top (required)>'
<$HOME>/<$PROJECT_DIR>/Rakefile:3:in `require'
<$HOME>/<$PROJECT_DIR>/Rakefile:3:in `<top (required)>'
<$HOME>/.gem/ruby/2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by jondeandres** [comment]
Hey @yock, you are right. We thought this rake task to test the integration with a rails or rack application, although we have this manual report, https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/rake_tasks.rb#L30.

We could try to do that the first and prepare all the other stuff if rack or rails are really found.

Thanks for the report.
