### ISSUE TITLE
Please version your JS snippet

### ISSUE THREAD

**Issue by amilligan** [rollbar/rollbar-gem#506]
It's difficult to check if the minified snippet needs an update.

**Comment by jondeandres** [comment]
Hi @amenzhinsky, the snippet is updated by us in the gem if it needs to be updated. So, if the snippet in https://github.com/rollbar/rollbar.js changes, we should update it in the gem and release a new version.

If at some point it is not updated, it's our fault. If you detect at we will appreciate you warn us :smile:
