### ISSUE TITLE
Docs : Add needed 'require' statement if using Rollbar::Middleware::Sinatra

### ISSUE THREAD

**Issue by grempe** [rollbar/rollbar-gem#507]
In your README, and other docs, you show how to turn off the monkey patched adding of the Rollbar Middleware and how to specify `use Rollbar::Middleware::Sinatra` instead.  This is good info, but it is missing one piece.  You will also need to call the appropriate `require` statement before that for it to work.

```
...
require 'rollbar/middleware/sinatra'
use Rollbar::Middleware::Sinatra
...
```

**Comment by LouisStAmour** [comment]
True. And if using JS, with standard configs, it ends up like the following:

```
  require 'rollbar/middleware/sinatra'
  use Rollbar::Middleware::Sinatra
  require 'rollbar/middleware/js'
  use Rollbar::Middleware::Js, {
      :options => Rollbar.configuration.js_options,
      :enabled => Rollbar.configuration.js_enabled
  }
```

**Comment by jondeandres** [comment]
You both are right, we'll fix this soon, thanks!

**Comment by LouisStAmour** [comment]
While you're at it, I'd appreciate a "nonce" setting, or you could document the following:

```
module SecureHeaders
  def self.content_security_policy_script_nonce(request)
    request.env['app.nonce']
  end
end
```
