### ISSUE TITLE
"unsafe-eval" CSP required? "nojson" should be a JS dist option

### ISSUE THREAD

**Issue by LouisStAmour** [rollbar/rollbar-gem#508]
I'm seeing CSP reports of the following, from a Chrome webpage served with CSP reporting turned on:

```
{
    "csp-report": {
        "document-uri": "https://***/url-goes-here",
        "violated-directive": "script-src 'self' https://d37gvrvc0wt4s1.cloudfront.net 'nonce-12345****' 'unsafe-inline'",
        "effective-directive": "script-src",
        "original-policy": "default-src 'self'; connect-src 'self' https://api.rollbar.com; script-src 'self' https://d37gvrvc0wt4s1.cloudfront.net 'nonce-12345*****' 'unsafe-inline'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' https://*; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; report-uri https://***.report-uri.io/r/default/csp/reportOnly",
        "blocked-uri": "eval",
        "source-file": "https://d37gvrvc0wt4s1.cloudfront.net",
        "line-number": 1,
        "column-number": 27371,
        "status-code": 0
    }
}
```

Included using standard:

```
Rollbar.configure do |config|
  config.disable_monkey_patch = true
  config.js_enabled = true
  config.js_options = {
      accessToken: '***',
      captureUncaught: true,
      payload: {/* ... */}
  }
end
```

**Comment by LouisStAmour** [comment]
I'm suggesting `nojson` purely because of instances where Chrome blocked Rollbar from running in add-ins because unsafe-eval isn't allowed in them, so a separate dist was created. I'm not sure when JSON code would be run by Chrome, so maybe `nojson` isn't going to fix things here.

I manually created the CSP, and made the gem generate the correct header by stubbing:

```
module SecureHeaders
  def self.content_security_policy_script_nonce(request)
    request.env['nonce']
  end
end
```

I'm thinking if there's a JS file that's appropriate, I can embed it directly and turn of JS support in the gem. But this way, presumably, my JS code will stay up-to-date with the gem...

**Comment by rokob** [comment]
The new version of Rollbar JS does not have this CSP issue and did away with the nojson dist so this should be resolved by the most up to date version of the rollbar.js snippet.

**Comment by davideluque** [comment]
I have rollbar 3.4.1 and followed this https://docs.rollbar.com/docs/integration-with-rollbarjs 

I am getting the error both local and when running tests. 

<img width="887" alt="Screenshot 2023-11-02 at 16 09 27" src="https://github.com/rollbar/rollbar-gem/assets/10492210/d04a6fdf-5eed-4094-97f9-788ef38b5d84">
