### ISSUE TITLE
Not informative error message in case of Exception#message is not a string

### ISSUE THREAD

**Issue by eugene-nikolaev** [rollbar/rollbar-gem#509]
Hello! I had a custom Exception class which by mistake returned not a string but an object (actually ActiveModel::Errors).
And I had the following error:

```
API error: Invalid format. data.body.trace.exception.message object value found, but a null is required.
```

Which is in my humble opinion not very informative and might be  "object value found, but a string is required".

BTW it was exposed at Rollbar item as:

![image](https://cloud.githubusercontent.com/assets/305699/17729129/527186f8-646b-11e6-99f6-c9d91039e72c.png)

**Comment by jondeandres** [comment]
@evgeniynickolaev thanks for reporting this, this looks like a problem in our API. We'll take a look at it soon.

**Comment by fguillen** [comment]
I am facing this problem now

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
