### ISSUE TITLE
should not load rake when not needed

### ISSUE THREAD

**Issue by grosser** [rollbar/rollbar-gem#524]
https://github.com/rollbar/rollbar-gem/blob/v2.12.0/lib/rollbar/plugins/rake.rb#L2

always loads rake, which adds another .1s to our apps load time ... can we make this only patch when rake was already defined ? (for example user is actually running rake)

**Comment by grosser** [comment]
I think this was added via https://github.com/rollbar/rollbar-gem/pull/485 ... @jondeandres

**Comment by jondeandres** [comment]
@grosser thanks for reaching us and open this issue. I'm not sure what to do here. Few customers had problems cause they didn't have `Rake` loaded, so we decided to try to load it by ourself. I understand your point and we are thinking on this.

We were thinking on something like `config.disabled_plugins = ['rake']`, but you'd need maybe to detect what to add to that array and it could be complex for the users. On the other side, loading the plugin only if `Rake` is defined, will break the customer's reports on next gem releases.

**Comment by grosser** [comment]
I think the correct solution is to silently not enable the plugin ... I don't think many users load rollbar and then load a rake task and then execute it ... it looks like the issue was opened because rollbar was spamming stderr when it should have kept silent ?

**Comment by jondeandres** [comment]
@grosser well, we have several customers having long or short rake processes where they use Rollbar. And they want to identify when a rake task failed.

We are thinking on what to do here, thank you very much for your opinion.

**Comment by grosser** [comment]
... alternatively a disabled_plugins flag would also work ... just sad to see another one of these 'require everything' points ... just noticed because we have some load tracking in our app to notice them ...

**Comment by KonstantinReido** [comment]
It broke the logic of our application: `!defined?(::Rake)` now always false :(

**Comment by jondeandres** [comment]
@KonstantinReido sorry, I didn't get that. Which problem you have or you had?

**Comment by jondeandres** [comment]
@KonstantinReido I still don't understand how we broke your application. requiring `rake` broke your app?

**Comment by KonstantinReido** [comment]
We have code in initializers that shouldn't run during migration so we added next condition `if Rails.env.production? && !defined?(::Rake)` but after update of rollbar gem now `defined?(::Rake)` always true.

**Comment by grosser** [comment]
I'd guess the app checks if `defined?(Rake)` to see if it is running via
rake or not

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
