### ISSUE TITLE
Ignored errors raised in ActiveJob are reported to Rollbar

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#531]
I have config:

```ruby
Rollbar.configure do |config|
  config.exception_level_filters.merge!(
    "ApplicationJob::FrequentFailureError" => "ignore"
  )
end
```

which is not respected in AJ jobs (where they are raised)

I believe this is because (from readme):

> This behavior applies to uncaught exceptions, not direct calls to Rollbar.error(), Rollbar.warning()

and in AJ plugin there is https://github.com/rollbar/rollbar-gem/blob/c85d1b76b560f3d1e07a6be4f3e6fbbdf9fd710c/lib/rollbar/plugins/active_job.rb#L6

which is a direct call.

I would expect this filtering work in AJ as well.

**Comment by jondeandres** [comment]
Hey @morgoth, you are right. We should be using this:

```ruby
Rollbar.error(exception,
                      :job => self.class.name,
                      :job_id => job_id,
                      :use_exception_level_filters => true)
```

We'll fix this soon
