### ISSUE TITLE
Rollbar.js could not be added because undefined local variable or method `result' for #<Rollbar::Middleware::Js:0x00000008c965f0> exception

### ISSUE THREAD

**Issue by mikefarmer** [rollbar/rollbar-gem#536]
It looks like there is a bug in the 2.13.2 build of the rollbar gem at line:

https://github.com/rollbar/rollbar-gem/blob/bf6d439be15455b557886fc73304ba00303aa278/lib/rollbar/middleware/js.rb#L72

`result` should be `app_result`

I am getting an error: 
`[Rollbar] Rollbar.js could not be added because undefined local variable or method `result' for #<Rollbar::Middleware::Js:0x00000008c965f0> exception`

In my log files in production when loading the JS middleware.

**Comment by jondeandres** [comment]
Hi @mikefarmer, thank you very much for opening this issue and sorry for this bug. We'll release a new version in few minutes.

**Comment by jondeandres** [comment]
@mikefarmer we released version 2.13.3 of the gem. let me know if you have any other problem.

thanks again!

**Comment by mikefarmer** [comment]
Awesome! Thanks all!
