### ISSUE TITLE
How to raise exception in development ?

### ISSUE THREAD

**Issue by rusikf** [rollbar/rollbar-gem#538]
Hello ruby hackers!
Example:
```ruby
begin
  # some bad code
rescue => error
 Rollbar.error(error)
end
```
It works great in production, but how to raise exception in development?
I disabled rollbar in rollbar config ( initializer)

Of'course I can add `raise(error) if Rails.env == 'development'` after each Rollbar.error(error) but there are a lot of cases in project, where I use it, so I don't won't to copypast

**Comment by jondeandres** [comment]
Hi @rusikf, do you mean that in development `Rollbar.error(error` doesn't work? You has said you've disabled Rollbar in the initializer. You should enable it.

I'm not sure about what exactly do you need to do in development. It'd be awesome if you can explain a bit more.

Thanks!

**Comment by rusikf** [comment]
Ok, sure - In development mode I don't need to send stats to rollbar.com.I
want , that exception will be not catched, it will be raise as default
exception, so I will see what happened.

пт, 7 окт. 2016, 20:47 Jon <notifications@github.com>:

**Comment by jondeandres** [comment]
Hi @rusikf, this is not really a rollbar-gem related issue. In your rescue block you are swallowing the exception and you don't want to do it for development.

You can have a method likethis:

```ruby
def rollbar_raise
  yield
rescue => e
  Rollbar.error(e)
  raise if Rails.env.development?
end
```

So you can use it like this:

```ruby
rollbar_raise do 
  # some work
end
```

**Comment by gerrywastaken** [comment]
```ruby
module CoreExtensions
  module Seatbelt
    def log(level, *args)
      # Call the Rollbar's log method
      ret = super(level, *args)
      raise Exception.new([level, args]) if ret == 'disabled'
      ret
    end
  end
end

Rollbar::Notifier.prepend CoreExtensions::Seatbelt
```

The above solution won't work unless you go and edit all existing code to use the roll_bar raise and it also will only work for errors. For anybody who needs to just have exceptions in place of Rollbar in whenever rollbar is disabled the above should do the trick.
