### ISSUE TITLE
custom hostname

### ISSUE THREAD

**Issue by benprew** [rollbar/rollbar-gem#540]
We run AWS EC2 instances and their hostnames aren't very descriptive, so we have a custom hostname variable that we use for syslog logging, identification, etc.

Currently, when rollbar sends a message it uses `Socket.gethostname` to get the hostname, but I'd like to be able to set a custom hostname, when configuring rollbar: i.e.

```
Rollbar.configure do |config|
  config.hostname = 'an-alternate-hostname'
end
```

Looks like it's easy enough to change the `server_data` method to check the config for the hostname variable?  Happy to discuss alternative implementations too.

**Comment by brianr** [comment]
That seems reasonable to me. I would call it `config.host` rather than `hostname` to align more closely with our other libraries (and with the field name in the API).

@jondeandres any concerns?

**Comment by jondeandres** [comment]
@benprew that's a great idea. This would need just add a new accessor to `Rollbar::Configuration` and use it in `Rollbar::Item#server_data`.

**Comment by benprew** [comment]
Thanks for getting this added guys, sorry I haven't had a chance to reply.  We'll start using it right away.
