### ISSUE TITLE
rake rollbar:test fails, but rollbar integration is successful

### ISSUE THREAD

**Issue by ajw725** [rollbar/rollbar-gem#541]
i'm not sure whether this is an issue somewhere on our end or with rollbar itself, so i apologize if it's not a real issue, but we're running into a bit of an interesting situation. we've used rollbar successfully on several projects in the past, and this is the first time this has happened.

install and config were all normal. ```rake rollbar:test``` looked like this, however:
```
Testing manual report...
[Rollbar] Scheduling item
[Rollbar] Sending item
[Rollbar] Success
[Rollbar] Details: https://rollbar.com/instance/uuid?uuid=4f8a4bb3-d0e1-456c-ace5-760268f6b5a3 (only available if report was successful)
Setting up the controller.
Processing...


Started GET "/verify" for  at 2016-10-26 18:28:23 -0400

IPAddr::InvalidAddressError: invalid address
        from /home/andrew/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/ipaddr.rb:559:in `in6_addr'
        from /home/andrew/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/ipaddr.rb:496:in `initialize'
        from /home/andrew/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/ipaddr.rb:514:in `new'
        from /home/andrew/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/ipaddr.rb:514:in `coerce_other'
        from /home/andrew/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/ipaddr.rb:170:in `include?'
        from /home/andrew/.rvm/gems/ruby-2.2.1/gems/web-console-2.3.0/lib/web_console/whitelist.rb:17:in `block in include?'
[etc.]
```

gem info:
 * Ruby 2.2.1
 * Rails 4.2.6
 * Rollbar 2.12.0
 * Rack 1.6.4

when we trigger actual errors in the application, (e.g. visiting a nonexistent URL), rollbar reports them successfully, so it looks like it's just the test that is failing. i'm having trouble figuring out why; it looks to me like the IP address error is being triggered intentionally (via the Rack::MockRequest to www.example.com), but instead of being caught and reported, it's breaking the test.

let me know if i can provide any more info, or if i'm just missing something. thanks!

**Comment by jondeandres** [comment]
Hi @ajw725, I think we've seen something similar before. Can you try removing web-console from your Gemfile? I think it's a problem between the ruby version and web-console.

**Comment by ajw725** [comment]
interesting...that seems to have worked. web console actually wasn't working with our server setup anyway, so we probably should have ditched it a while ago.

thanks! closing the issue.

**Comment by jondeandres** [comment]
Thanks to you @ajw725, if you have any other issue please ping us.

**Comment by olegsfinest** [comment]
Hi there, I am facing the exact same problem. Removing web-console actually did the trick, but actually I would like to keep on using it, so have you guys maybe encountered, why this bug appears?
Thanks in advance!
