### ISSUE TITLE
How to disable all exceptions except one in rollbar

### ISSUE THREAD

**Issue by venkat-rg** [rollbar/rollbar-gem#543]
Hi,

We have added a rails gem for tracking N+1 queries to our development environment. We would like to track only errors that we get from this gem and want to completely ignore all other exceptions. I have come across something like this: 'config.exception_level_filters.merge!('ActiveRecord::RecordNotFound' => 'ignore'), but this is not going to be that useful as it is practically impossible to ignore all errors that we get in our app at development level.

Thanks

**Comment by jondeandres** [comment]
@venkat-rg thanks for writing here. Are you the owner of the gem you want to monitor?

First you should remove the middleware that we add into the Rails middleware chain, so automatic errors are not reported. Done this, I think you should monkey patch all the methods from that gem that you want to track.

You can write a module that will monkey patch all the methods you need, call `super` in a `begin/rescue` block, send the error to Rollbar, and then raise the exception again so you don't swallow it.

If you manage to make it work tell us. Also if you have any other doubt, ping us.

Thanks!
