### ISSUE TITLE
rollbar-rails-runner doesn't support same parameters as Rails runner

### ISSUE THREAD

**Issue by dcarral** [rollbar/rollbar-gem#551]
The suggested way to specify an environment for the runner command, according to [Rails docs](http://guides.rubyonrails.org/command_line.html#rails-runner), is:

> $ bin/rails runner -e staging "Model.long_running_method"

However, `rollbar-rails-runner` doesn't support this. In order to specify an environment, users need to set the `RAILS_ENV` environment variable.

Would be possible to support the exact same parameters as Rails runner does?

Thanks in advance for the feedback ;)

**Comment by jondeandres** [comment]
Hey @dcarral, that's a nice request. We'll try to fix that as soon as possible.

Thanks!

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
