### ISSUE TITLE
"person" incorrect for a Delayed::Job uncaught exception

### ISSUE THREAD

**Issue by Waseem-Q** [rollbar/rollbar-gem#553]
My "person" reported is incorrect - since the operation is a Delayed::Job, they cannot access the controller's `current_user` nor would that make sense. I'm not sure how this is being set to someone, but it's definitely misleading.

For example, today an error occurred for a user on the 2nd day for a notice which is explicitly sent on the 6th day (which I can see is still queued to run in 4 days).

**Comment by jondeandres** [comment]
@Waseem-Q can you give us more details about this? Are you talking about a web request that generates an error that is enqueued into to delayed_job? Or are you talking about a delayed_job job that is failing?

Thanks.

**Comment by coryvirok** [comment]
Closing this since there hasn't been any activity on it in quite a while. Please reopen as needed.
