### ISSUE TITLE
queue name when async through dj

### ISSUE THREAD

**Issue by inquisitivus** [rollbar/rollbar-gem#563]
Hi!
Is there any way to specify delayed_job queue name for async submissions? 
Something like `config.use_resque :queue => 'my_queue'` for Resque.

**Comment by jondeandres** [comment]
Hey @inquisitivus, thanks for writing. For resque you can just use `config.use_resque` for the default queue, or you can set the queue as you suggest: `config.use_resque :queue => :my_queue`.

**Comment by jondeandres** [comment]
@inquisitivus sorry, I though you were asking for resque and not delayed_job.

Currently we don't support named queues for DJ, we'll do this soon. Until we fix this and release a new version of the gem, you can have the same behavior using this snippet:

```ruby
require 'rollbar/delay/delayed_job'

ROLLBAR_DJ_QUEUE = 'rollbar'

Rollbar::Delay::DelayedJob.instance_eval do
  def call(payload)
    new.delay(:queue => ROLLBAR_DJ_QUEUE).call(payload)
  end
end
```

Ping us if you have any problem with it and we'll help you. Thanks!

**Comment by inquisitivus** [comment]
Thanks!
