### ISSUE TITLE
How to send more details about the Exception to the Rollbar interface

### ISSUE THREAD

**Issue by fguillen** [rollbar/rollbar-gem#572]
When I run this script: 

```
require "rollbar"

class CustomException < Exception
  attr_reader :details

  def initialize(message, details = {})
    super(message)
    @details = details
  end
end

Rollbar.configure do |config|
  config.access_token = "fc316ac1f7404dc28af26d5baed1416c"
end

begin
  raise CustomException.new("This is a test CustomException", { :option_1 => "value_1" })
rescue Exception => e
  puts "CustomException.details: #{e.details}"
  Rollbar.error(e)
end
```

I get a Rollbar item occurrences as this:

- https://rollbar.com/demo/demo/items/1285/occurrences/22065716012/

I see the `message` of these exceptions but I don't see the `details` what in my production App is the most important information.

I have to explicitly communicate to `Rollbar.error` to extract this `details: 

```
begin
  raise CustomException.new("This is a test CustomException with details", { :option_1 => "value_1" })
rescue Exception => e
  puts "CustomException.details: #{e.details}"
  Rollbar.error(e, :details => e.details)
end
```

This will generate occurrences as this: 

- https://rollbar.com/demo/demo/items/1285/occurrences/22065790115/

And I can see there the `body.trace.extra.details.option_1`.

But this is not working for me because in my case I don't know the type of the Exception and not the name of the `details` method. I just want to create an CustomException that is self-discoverable for Rollbar and that Rollbar can extract the `details` or whatever is the name of my extra information method. Just in the same way that Rollbar always extract `exception.message`.

**Comment by c-knowles** [comment]
Interested in the same function. Maybe slightly related to https://github.com/rollbar/rollbar-gem/issues/500. In the case of uncaught exceptions, the `scope` function doesn't seem to be the right place to embed those extra details but often the exception contains several more attributes which are useful for finding the root cause. Currently how would this be implemented? Would we have to catch uncaught exceptions ourselves, embed the info from the exception and then forward it onto rollbar?

**Comment by coryvirok** [comment]
@rivkahstandig3636 can you take a look at this?

**Comment by steveh** [comment]
I'm interested in this too. Perhaps if the exception implements `to_h`?

**Comment by rokob** [comment]
Does https://github.com/rollbar/rollbar-gem/blob/master/README.md#including-additional-runtime-data help here? The original question is hard to understand how to help. How can we self discover an arbitrary Ruby class?

**Comment by ArturMoczulski** [comment]
@fguillen suggestion from @rokob is the way to go. Such feature is very specific to your circumstances and that's exactly what we implemented `custom_data_method` for. You can use your custom logic there to dump all of the exception object data into custom data.
