### ISSUE TITLE
Reporting error "can't modify frozen SystemStackError"

### ISSUE THREAD

**Issue by simonc** [rollbar/rollbar-gem#573]
For some time now I've been facing the recurring issue of items named

```
Error processing the item: RuntimeError, can't modify frozen SystemStackError
```

I tried to track were the issue happened and found that it's located around the call to `MultiJson.dump` but I don't know if it comes from what's given to Rollbar to report or something else 😕

The issue happens with
• Rails 4.2.7.1 and 5.0.1
• Ruby 2.3.3 and 2.4.0
• Rollbar 2.13.5 and 2.14.0
• MultiJson 1.12.1
• Oj and without Oj installed

I'm available if you need any additional information or tests.

**Comment by coryvirok** [comment]
Tagging PR #482 since it's related.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
