### ISSUE TITLE
Reporter relies on ActiveSupport but it's not a dependency

### ISSUE THREAD

**Issue by sumeet** [rollbar/rollbar-gem#578]
This code calls `present?` which is from ActiveSupport (https://github.com/rollbar/rollbar-gem/blob/368445ac9c15f883cd92eb427458ff1173ae1c51/lib/rollbar/item/frame.rb#L108):

```ruby
file_lines[from_line, (to_line - from_line + 1)].select(&:present?)
```

We fixed this in our project by bundling ActiveSupport. Should rollbar-gem include this as a dependency?

**Comment by jondeandres** [comment]
Oh...sorry @sumeet. We should fix this. Our idea is not having active_support as dependency. Thanks for the report.

**Comment by ian952** [comment]
It seems that is also using `JSON` in ActiveSupport as well.

**Comment by jondeandres** [comment]
@ian952 `JSON` is not a dependency from active_support. Can you explain further that?

**Comment by ian952** [comment]
I was getting this error before requiring `active_support/all`
```
I, [2017-03-23T15:58:24.103827 #24571]  INFO -- : [Rollbar] Scheduling item
I, [2017-03-23T15:58:24.103944 #24571]  INFO -- : [Rollbar] Sending item
E, [2017-03-23T15:58:24.111841 #24571] ERROR -- : [Rollbar] Error processing the item: NameError, uninitialized constant ActiveSupport::JSON
```

**Comment by jondeandres** [comment]
Hi @ian952, that is interesting and seems that maybe something in active support has been partial loaded. Do you have a way to get that backtrace and share it? The Gemfile you are using can be also helpful.

You can write to support@rollbar.com if this information is sensible.
