### ISSUE TITLE
JS doesn't automatically include user information

### ISSUE THREAD

**Issue by dignoe** [rollbar/rollbar-gem#580]
According to the standard config (rollbar.rb)...

> By default, Rollbar will try to call the `current_user` controller method
> to fetch the logged-in user object, and then call that object's `id`,
> `username`, and `email` methods to fetch those properties.

But I'm not getting any user information in my JS errors, even though `current_user` returns the `User` object of the signed in user with access to `id`, `username`, and `email`.

How do I get this to work? Do I have to explicitly add the following JS code to each page?
`Rollbar.configure({payload: {person: {id: 12345, email: 'stewie@familyguy.com'}}});` Can I add more than one call to `Rollbar.configure()` per page?

**Comment by dignoe** [comment]
Also, is it possible to include a `proc` in the rollbar.rb config file that has access to the current controller object? So that I could do something like...

``` ruby
config.js_enabled = true
config.js_options = {
      accessToken: "my_token",
      captureUncaught: true,
      payload: {
        environment: Rails.env,
        person: -> (controller) { controller.current_user.try(:rollbar_hash) }
      }
```

**Comment by coryvirok** [comment]
@and-megan can you take a look at this?

**Comment by and-megan** [comment]
Hi @dignoe - previously you could not track people in your JS code using rollbar-gem. However, we've just updated our gem so that JS people-tracking is enabled. See our [Changelog](https://github.com/rollbar/rollbar-gem/blob/master/CHANGELOG.md#2150).

**Comment by dignoe** [comment]
@and-megan, awesome... thanks!

I looked at the pull request really quick; is this automatic or do I have to set the person config variable to true in the js options? It might be a good idea to add this to the readme file.

**Comment by dignoe** [comment]
Took another look at the pull request, and it is coming in automatically. Thanks!

**Comment by and-megan** [comment]
@dignoe It's automatic. That's a good idea - we'll change  the docs soon.
