### ISSUE TITLE
Bad grouping with variable messages

### ISSUE THREAD

**Issue by brauliobo** [rollbar/rollbar-gem#589]
Rollbar isn't grouping correctly errors based on the exception name. One example that creation thousands of items:
`Net::HTTP::Persistent::Error: too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 0 requests on 70026762533720, last used 1493038121.492723 seconds ago`

I need the message to only the class name and prefixed with a custom string. How to report an error this way?

**Comment by rivkahstandig3636** [comment]
Hi @brauliobo, can you email us at support@rollbar.com about this and link us to the items in question? Thank you!

**Comment by brauliobo** [comment]
ok, just did @rivkahstandig3636.

I also need to customize the message of the exception, how to do it?
