### ISSUE TITLE
How to explicitly use JS reporting?

### ISSUE THREAD

**Issue by gregblass** [rollbar/rollbar-gem#591]
I've got JS error reporting working as described in the readme. However, if I try to report an error explicitly, I've getting: "Uncaught ReferenceError: Rollbar is not defined"

Is there something else I need to do to be able to use the Rollbar.error type syntax in my js code in the asset pipeline?

**Comment by coryvirok** [comment]
@and-megan can you take a look at this?

**Comment by and-megan** [comment]
You should be good to go if you've integrated Rollbar.js like so:
`
Rollbar.configure do |config|
  # common gem configuration
  # ...
  config.js_enabled = true
  config.js_options = {
    accessToken: "POST_CLIENT_ITEM_ACCESS_TOKEN",
    captureUncaught: true,
    payload: {
      environment: "production"
    }
  }
end`

When navigate to a webpage where Rollbar.js is supposed to be installed and you open Dev Tools, can you see the Rollbar.js script?

**Comment by gregblass** [comment]
Sorry for leaving this open! Can't remember what the issue was but it was some noob mistake. I hadn't configured it correctly. Thanks for responding!
