### ISSUE TITLE
Keeping Rollbar.js up to date

### ISSUE THREAD

**Issue by jmberez** [rollbar/rollbar-gem#594]
Rollbar keeps warning me that rollbar.js is outdated. It's getting loaded from this gem, which apparently points to a specific version from a year ago. Any reason not to use the current version? Maybe it should be a configuration option?

**Comment by coryvirok** [comment]
Good question, @jmberez. This is actually already an option but it's not documented. Check out the `rollbarJsUrl` config option for the JS SDK.

```rb
Rollbar.configure do |config|
  # common gem configuration
  # ...
  config.js_enabled = true
  config.js_options = {
    accessToken: "POST_CLIENT_ITEM_ACCESS_TOKEN",
    captureUncaught: true,
    payload: {
      environment: "production",
      rollbarJsUrl: "https://cdn.rollbar.com/js/v1.9/rollbar.min.js"
    }
  }
end
```

**Comment by brianr** [comment]
@coryvirok I think the snippet has changed a bit though, so it's not as simple as just updating the `rollbarJsUrl`.

**Comment by coryvirok** [comment]
Right. We need to pull in the latest rollbar.js submodule and then you need to override the rollbarJsUrl config option as I mentioned above. It's not guaranteed to work across minor/major versions but at least people won't have to update rollbar-gem every time we release rollbar.js.
