### ISSUE TITLE
undefined method `connect' for nil:NilClass

### ISSUE THREAD

**Issue by Ridge2** [rollbar/rollbar-gem#603]
I'm using Rails 5.1.1
Ruby 2.4
I'm trying to follow a book called HeadFirstRails and its telling me to edit my config/routes.rb like this: 
`ActionController::Routing::Routes.draw do |map|`
 ` map.connect "/ads/:id", :controller=>"ads", :action=>"show"`
  `map.connect ":controller/:action/:id"`
  `map.connect ":controller/:action/:action/:id.:format"`
`end`

But when I look into the routes.rb folder it has this:
`Rails.application.routes.draw do`
`end`
When I try configuring it like how they want me to I get an error message:
`undefined method connect' for nil:NilClass`

Can anyone help me with that? Thanks

**Comment by brianr** [comment]
Hi @Ridge2  - this looks like a Rails question, not a Rollbar question. Maybe try asking your question on the community for HeadFirstRails?

Going to close this out; please reopen if this really is Rollbar-related. Thanks!
