### ISSUE TITLE
rollbar-rails-runner doesn't work on Rails 5.1.1

### ISSUE THREAD

**Issue by dclausen** [rollbar/rollbar-gem#606]
### Steps to reproduce

bundle exec rollbar-rails-runner "puts 'hello'"

### Expected behavior

System should output 'hello'

### Actual behavior

bundler: failed to load command: rollbar-rails-runner (/home/deployer/app/shared/bundle/ruby/2.4.0/bin/rollbar-rails-runner)
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/deployer/app/shared/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/commands/runner.rb
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:39:in `read'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:39:in `eval_runner'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:30:in `block in run'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:47:in `rollbar_managed'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rails/rollbar_runner.rb:30:in `run'
  /home/deployer/app/shared/bundle/ruby/2.4.0/gems/rollbar-2.14.1/bin/rollbar-rails-runner:5:in `<top (required)>'
  /home/deployer/app/shared/bundle/ruby/2.4.0/bin/rollbar-rails-runner:22:in `load'
  /home/deployer/app/shared/bundle/ruby/2.4.0/bin/rollbar-rails-runner:22:in `<top (required)>'

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.0

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by marcospy** [comment]
@rivkahstandig3636 I'm having the same issue here using rails 5.1.1. With a brief investigation I've figured out that the implementation of commands changed in the new Rails version. Take a look at https://github.com/rails/rails/blob/master/railties/lib/rails/commands.rb and https://github.com/rails/rails/blob/master/railties/lib/rails/commands/runner/runner_command.rb, they are very different from https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/commands/runner.rb.

I've solved the problem just changing the method [`eval_runner`](https://github.com/rollbar/rollbar-gem/blob/master/lib/rails/rollbar_runner.rb#L38) to invoke the command using the new api:
```ruby
def invoke_runner
  Rails::Command.invoke 'runner', ARGV
end
```

However, the above code is compatible with Rails 5 only, do you have any thoughts on how to keep backward compatibility?

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski Any thoughts?

**Comment by WenInCode** [comment]
I'm seeing this on an app running Rails `5.1.6`. @marcospy seems to have found the underlying issue.

**Comment by jessewgibbs** [comment]
@ArturMoczulski could you investigate this issue?

**Comment by waltjones** [comment]
This is fixed by https://github.com/rollbar/rollbar-gem/pull/803.
