### ISSUE TITLE
I cannot remove the rollbar-gem from my project 

### ISSUE THREAD

**Issue by superplussed** [rollbar/rollbar-gem#607]
I'm trying to remove rollbar from a rails 5.0.1 project and if I remove the gem and the initializer and restart the server, the project will just hang.  There is no lingering references to rollbar anywhere in my project, and yet it will hang.  If I go and add the gem back and an empty initializer: 

```
require 'rollbar/rails'
Rollbar.configure do |config|
end
```

It loads again.  Again, there aren't any references in my javascript, and to double check that I stripped my application.haml down to nothing, and it still hangs.  Both times whether it loads or doesn't load, my console looks exactly the same.  Any ideas?  I'm baffled..

**Comment by rokob** [comment]
I have no idea what could be going on here, let me see if I can dig into this a little bit and see if I can figure something out. A couple things that could be going on are if the Gemfile.lock has references to dependencies that are no longer there, bundler can do weird things. How did you remove the gem? You can also get some extra information by running bundler with the verbose flag to get more info about what is happening.

**Comment by superplussed** [comment]
Hmm, I tried switching unicorn for webrick and it gave me more verbose logging, which included this beauty: webrick No live threads left. Deadlock?  Somehow your gem was stopping this from happening for some reason :) . But upgrading a bunch of gems including rails fixed this issue.  Closing due to it not being related to your gem :)
