### ISSUE TITLE
change the Rake plugin to wrap Rake::Task#invoke

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-gem#611]
in the Rake plugin, we monkey patch the Rake application and not the Rake tasks. That means that only when running the Rake task using the regular command line do we wrap the errors. However, if you execute the Rake tasks programatically by running Task#invoke, the errors aren't wrapped. can we change the Rake plugin to wrap Rake::Task#invoke so it works everywhere, also programatically?

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
