### ISSUE TITLE
rollbar.js version 2.1.0 is now available. (This project is currently using version 2.0.4)

### ISSUE THREAD

**Issue by donni106** [rollbar/rollbar-gem#612]
I use the latest gem version and ask myself why rollbar is alerting that there is a new rollbar.js version.

![bildschirmfoto 2017-07-14 um 13 40 34](https://user-images.githubusercontent.com/1942953/28210939-56d82d26-689a-11e7-8155-4f8cb8e6d701.png)

In the rollbar-gem history I can see an update to rollbar.js 2.0.4 but no 2.1.0.
How can I update or when will the 2.1.0 be available per rollbar-gem?

Thanks!

**Comment by easybills-admin** [comment]
cc: @jondeandres @rokob

**Comment by alexmdavis** [comment]
Bump for 2.2.3 (https://github.com/rollbar/rollbar.js/commit/03c664cf4538ff4260f9e9b93ac12130f2b5a78a). Telemetry is cool! Using the version bundled in the gem would be easier.
