### ISSUE TITLE
Deal with dj_threshold > 0 causing errors not to fire in an edge case

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-gem#615]
From #592:

There is still a potential for the error to not fire if https://github.com/richvorp/rollbar-gem/blob/delayed_job_failure_hook/lib/rollbar/plugins/delayed_job/plugin.rb#L48 check fails and the dj_threshold is higher than 0.

An alternative would be to make it always error with:

```
data = Rollbar::Delayed.build_job_data(job)
::Rollbar.scope(:request => data).error(job.last_error, :use_exception_level_filters => true) if job.last_error
```

instead of https://github.com/richvorp/rollbar-gem/blob/delayed_job_failure_hook/lib/rollbar/plugins/delayed_job/plugin.rb#L14

**Comment by ArturMoczulski** [comment]
Fixed in https://github.com/rollbar/rollbar-gem/pull/692
