### ISSUE TITLE
Running "-e production" with rollbar-rails-runner doesn't work

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-gem#617]
Details in https://app.clubhouse.io/rollbar/story/12854/running-e-production-with-rollbar-rails-runner-doesn-t-work

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
