### ISSUE TITLE
Exception level filters not working

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-gem#621]
Details in https://app.clubhouse.io/rollbar/story/21869/exception-level-filters-not-working-for-one-user

**Comment by codegoalie** [comment]
I can't see the details, but I believe I'm having this issue as well. Unfortunately, I'd like to filter out 404s in my Rails apps because all the bots hitting `/wp-admin`, etc. but right now it's cluttering up my Rollbar Dashboard.

Also, I'd be happy to help submit a PR to resolve this. Would you be able to share any details you have in that story?

**Comment by rivkahstandig3636** [comment]
Hi @codegoalie, are your items caught or uncaught exceptions? If caught, you need to pass in the user_exception_level_filters keyword arg for the filters to apply. See the docs on Exception level filters [here](https://rollbar.com/docs/notifier/rollbar-gem/) for more info. If they're uncaught, you can also filter those errors out using the [before process hook](https://rollbar.com/docs/notifier/rollbar-gem/#before-process-hook) in the meantime.

**Comment by and-megan** [comment]
I think there's a bit of confusion around exception level filters. Here's an example to clarify. 

Let's say I have a bunch of `ActionController::RoutingError`s cluttering my dashboard.

I open up the raw JSON of one of these Rollbar occurrences and see that the exception looks like
```
      "exception": {
        "message": "No route matches [GET] \"/22\"", 
        "class": "ActionController::RoutingError"
      }, 
```

I add exception_level_filters to my Rollbar config file, `rollbar.rb`, like so:
```
Rollbar.configure do |config|
  ...
  config.exception_level_filters.merge!({
    'ActionController::RoutingError' => 'ignore'
  })
  ...
end
```
Now, any exception with the 'ActionController::RoutingError' class will be ignored. 
Hope that helps clear things up! 
cc @codegoalie

**Comment by codegoalie** [comment]
@and-megan Thanks! I had that in my initializer, but they were still appearing. However, the before process hook had successfully ignored them.

Thanks for all your help!

**Comment by rafaelcgo** [comment]
Is there a possibility to only ignore "ActionController::RoutingError" for specific urls (let's say, a blacklist of urls)?

**Comment by rivkahstandig3636** [comment]
@rafaelcgo You'll want to use the before process hook instead: https://docs.rollbar.com/docs/ruby#section-before-process-hook

**Comment by rafaelcgo** [comment]
@rivkahstandig3636 I would need to regex match the `message` with the blacklisted urls and then raise `Rollbar::Ignore` if needed? Is that correct?

**Comment by rafaelcgo** [comment]
@rivkahstandig3636 Actually `message` was nil, I could extract the message from the exception.

My solution:

```
BLACKLISTED_REGEX = %r{
  ^/assets/|
  ^/images/|
}x.freeze

handler = proc do |options|
  url = options[:exception].message[/.*"([^"]*)"/,1]
  if options[:exception].is_a?(ActionController::RoutingError)
    raise Rollbar::Ignore if url =~ BLACKLISTED_REGEX
  end
end

config.before_process << handler
```

**Comment by frkhssn** [comment]
Hi, exception filtering not for me as well.

I have on initialiser

```config.exception_level_filters.merge!({ 'Importer::JobManager::AlreadyRunningError' => 'warning',})
```

 Still the error is reported as `error`. Any idea why is this happening?

Please note that this error is being generated from Sidekiq process.
