### ISSUE TITLE
Remove deprecations for Rails 5.1

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-gem#643]
Story transferred from https://app.clubhouse.io/rollbar/story/10010/gem-remove-deprecations-for-rails-5-1

**Comment by rokob** [comment]
Things that need to be done:
- [ ] Add a rails51.gemfile to gemfiles/
- [ ] Run tests on travis to see what breaks and what warnings come up
- [ ] Fix any warnings
- [ ] Fix any broken tests

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
