### ISSUE TITLE
Ruby Doc update needed?

### ISSUE THREAD

**Issue by btihen** [rollbar/rollbar-gem#644]
Hello,

Why do you suggest using gem oj v2.12.14? 
That version doesn't work with Ruby 2.4.x -- however oj v2.16.1 - does. 

I'm also curious why you don't suggest oj v3.3.x. 
I've been using that version with rollbar and haven't notice any problems. 

Is there a reason you suggest using this older version of oj and why not the newest version or at least a version compatible with Ruby 2.4.x such as oj v2.16.1

If this is just out of date docs -- can they be updated?

Thanks,
Bill

**Comment by rokob** [comment]
That is just an old version recommendation, the docs just need to be updated. I will update to `2.16.1`.
