### ISSUE TITLE
Add docs for using Grape with rollbar-gem

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-gem#645]
Proper settings for capturing inside the popular API gem "Grape" for Rails applications to capture 500s

# global exception handler, used for error notifications
rescue_from :all do |e|
if Rails.env.development?
raise e
else
Rollbar.error(e)
error_response(message: "Internal server error", status: 500)
end
end

**Comment by rivkahstandig3636** [comment]
Closed via #679
