### ISSUE TITLE
Rollbar Exception: IOError: "closed stream" when using SuckerPunch

### ISSUE THREAD

**Issue by terry90** [rollbar/rollbar-gem#646]
I raise exceptions when some of my async tasks cannot be completed, Rollbar is unable to show something due to some error: 
`Failsafe from rollbar-gem. IOError: "closed stream" in /usr/local/lib/ruby/2.4.0/delegate.rb:341:in 'rewind': build_item in exception_data`

It's a bit annoying, but I'm not 100% it is because of Rollbar + SuckerPunch.
Does Rollbar need the main thread of the app ? Is it a known issue ?

**Comment by rokob** [comment]
This is a rough one, that failsafe error occurs when we are already dealing with some internal error that occurred while processing an item. We are attempting to build a minimal item with the exception that caused the first error, and that again throws an exception. Throwing a closed stream error at this point though is really odd. Those usually mean a file handle is closed and we still hold a reference to it that we are trying to use. It seems as if the exception that caused the first internal error might include a reference to something that has already been garbage collected. Rollbar does not need the main thread, but if you are trying to report an exception with a reference to an object across threads and the lifetime of those references are possibly shorter than the exception being sent, well anything could be happening at that point.
