### ISSUE TITLE
Make js_options a string instead of a hash

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-gem#648]
If we took a string instead of a hash and just inserted that string directly as `_rollbarConfig` , it would let you pass in whatever you want. It's not currently possible to pass in js functions like checkIgnore.

**Comment by tthomas7** [comment]
I would also appreciate this.

**Comment by waltjones** [comment]
@and-megan, @tthomas7, The gem writes metadata to this object (specifically `person_data`) before it is serialized, requiring it to be accessed as a hash. Can you elaborate on how you want to use this?

**Comment by and-megan** [comment]
@waltjones I wrote this up when I was working in Rollbar support so it's been awhile since I've worked with the gem!

IIRC this would be useful in the case you just wanted to solely use the rollbar-gem, rather than using the rollbar.js SDK in tandem, and you wanted to use rollbar.js functionality. For example, the `checkIgnore` function would be useful https://docs.rollbar.com/docs/reduce-noisy-javascript-errors so you could ignore all JS errors including a particular filename in the stacktrace.

**Comment by waltjones** [comment]
@and-megan,thank you for the context!
