### ISSUE TITLE
Add ability to limit the amount of errors you can send from a given session in the gem.

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-gem#655]
Moved from https://app.clubhouse.io/rollbar/story/11742.

**Comment by Laykou** [comment]
Hi, is there any idea how this could be done? We would really welcome this feature

**Comment by rivkahstandig3636** [comment]
Hi @Laykou, it's on our roadmap but not currently implemented. Follow along here for updates.

**Comment by Laykou** [comment]
Thanks. Is there any expected timeline? E.g. within a week, month, year, after 10 years :D And also what about PHP plugin? Or should I ask in a PHP rollbar project?

**Comment by rivkahstandig3636** [comment]
@Laykou I don't have a specific timeframe; it's not our next scheduled milestone. Please ask about the other notifiers in the respective repos.
