### ISSUE TITLE
rollbar.js version 2.3.1 is now available. (This project is currently using version 2.1.0).

### ISSUE THREAD

**Issue by vfonic** [rollbar/rollbar-gem#657]
I'm seeing this message in my app's Rollbar dashboard. Could it be that rollbar.js dependency in this project should be updated? Or how can I update the js script?

Thanks!

Gemfile.lock:
`rollbar (2.15.5)`

**Comment by rivkahstandig3636** [comment]
Thanks for reporting this @vfonic! I believe this is a change that we need to make on our end.

**Comment by ArturMoczulski** [comment]
Resolved and ready for merging in https://github.com/rollbar/rollbar-gem/pull/669
