### ISSUE TITLE
java.lang.Exception are reported as "Empty message" and no stack trace

### ISSUE THREAD

**Issue by thbar** [rollbar/rollbar-gem#658]
### Environment

* Ubuntu 16
* JRuby 9.1.14.0
* rollbar 2.15.0

### Description of the problem

While working with a production JRuby project, exceptions that are raised in Java parts of the code (3rd party API) during Sidekiq jobs are propagated to Rollbar, but with "Empty message" as the message, and no stack trace.

### Reproduction

I haven't got yet a reproduction mimicking this production issue exactly (while I have something close).

I will work on that and hopefully will report back with something here.

### Potential fix

I believe a potential fix (not completely tested yet) would be to adapt `extract_arguments` to whitelist java exceptions, like:

```ruby
      args.each do |arg|
        if arg.is_a?(String)
          message = arg
        elsif arg.is_a?(Exception)
          exception = arg
        elsif arg.is_a?(java.lang.Exception)
          exception = arg
```

A proper fix would have to maintain MRI compatibility, obviously.

**Comment by thbar** [comment]
Here is a reproduction as a sidekiq job, which will completely mimics the issue I've initially met:

```ruby
class JobRaisingException
  include Sidekiq::Worker
  sidekiq_options retry: false
  
  def perform
    raise java.lang.Exception.new("Hello")
  end
end
```

(then start sidekiq, and `JobRaisingException.perform_async`).

**Comment by rivkahstandig3636** [comment]
Hi @thbar, thanks for reporting this! We'll take a look into it.

**Comment by thbar** [comment]
Hi @rivkahstandig3636 and thanks for acknowledging this.

@rokob here is a more narrow reproduction:

```ruby
RSpec.describe "Rollbar behaviour" do
  it "reports java exceptions properly to rollbar" do
    begin
      raise java.lang.Exception.new("Hello")
    rescue => e
      message, exception, extra = Rollbar::Notifier.new.send(:extract_arguments, [e])
      expect(exception).to eq(e)
    end
  end
end
```

I initially wanted to make something closer from the rollbar test suite, but could not easily run it with success locally.

**Comment by thbar** [comment]
(note that the fix I proposed, although not working as is for MRI, also works to fix this smaller reproduction)

**Comment by thbar** [comment]
Once the work has started on this, I'll be able to do some testing on my side if you'd like (in particular to verify that the full content of the exception is there when they are rich).

**Comment by ArturMoczulski** [comment]
@thbar This looks good to me. Do you want to submit a pull request? You said that your solution is not working with MRI. What problems are you running into?

**Comment by thbar** [comment]
@ArturMoczulski I can submit a PR but this will take a bit of time due to my current heavy schedule, so please leave this opened in the mean time (unless someone else tackles this before).

My approach was a quick fix and needs more polishing, because of this:

```
2.5.0 :006 > arg = "hello"
 => "hello" 
2.5.0 :007 > arg.is_a?(java.lang.Exception)
Traceback (most recent call last):
        2: from /Users/thbar/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
        1: from (irb):7
NameError (undefined local variable or method `java' for main:Object)
```

You cannot refer to `java.lang.Exception` within MRI without raising an error, so the code needs to be a bit more careful than that.

**Comment by ArturMoczulski** [comment]
The fix and the test have been merged in the PR and will be included in the next tag release.
