### ISSUE TITLE
Feature request: disable logging in development if Rollbar is disabled

### ISSUE THREAD

**Issue by allspiritseve** [rollbar/rollbar-gem#66]
I have rollbar disabled in development, but any time there's an exception I get log messages like this:
```shell
[Rollbar] Reporting exception: undefined method `submissions' for nil:NilClass
[Rollbar] Exception not reported because Rollbar is disabled
```
It would be nice if there was a way to disable these as they clutter up my log file and are unnecessary if Rollbar is disabled.

**Comment by tisba** [comment]
Any news on this one? I actually would like to disable (or redirect) Rollbar logging in production as well (even if Rollbar reporting is enabled).

We are logging JSON-lines to be processed with Logstash. Rollbar's logging is quite annoying and messes up the logs.

**Comment by jondeandres** [comment]
@tisba we didn't work on this yet, but you could always set `config.logger` to an instance of NullLogger like this one, https://github.com/rack/rack/blob/master/lib/rack/nulllogger.rb.

So depending on the environment you are, you can set that logger or not. We'll try to find a configuration solution for this or perhaps adding or not the middleware to the stack.

**Comment by tam-vo** [comment]
Any progress for this issue? It's still open for long time

**Comment by fagiani** [comment]
Bump! any hope for this?
