### ISSUE TITLE
Is it possible to change where in the <head> the JS tags are placed?

### ISSUE THREAD

**Issue by chrxs** [rollbar/rollbar-gem#660]
Hi,
Is it possible to change where in the <head> the JS tags are placed?
At the moment I see they appear immediately in the <head> tag.

I have a website report that tells me:
"A charset attribute on a meta element found after the first 512 bytes."

And this is because the rollbar scripts are put above the `<meta charset="utf-8">` line in my code.

thanks
- Chris

**Comment by rokob** [comment]
Yes, this was changed in https://github.com/rollbar/rollbar-gem/pull/647 and will be available in the next release which should go out soon.

**Comment by chrxs** [comment]
Oh excellent, thanks a lot! @rokob
