### ISSUE TITLE
SSL Error when processing Rollbar items in Windows Server

### ISSUE THREAD

**Issue by augustosamame** [rollbar/rollbar-gem#662]
I am getting the following stacktrace error from a Windows environment.

The Rollbar report does get through, but this is cluttering my dev console.

Latest rollbar gem: 2.15.5
Ruby version: ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
Rails version: Rails 5.0.6
Windows version: Windows Server 2008 R2 Enterprise SP1

[Rollbar] Reporting internal error encountered while sending data to Rollbar
[Rollbar] Sending item
[Rollbar] Success
[Rollbar] Details: https://rollbar.com/instance/uuid?uuid=8b7c03b2-d662-46ca-6f7e5e331f05 (only available if report was successful)
[Rollbar] Error processing the item: OpenSSL::SSL::SSLError, SSL_connect SY returned=5 errno=0 state=SSLv2/v3 read server hello A. Item: {"access_toke4d73f464d71b416e9bf9b772cad04272", "data"=>{:timestamp=>1514559226, :enviro=>"development", :level=>"warning", :language=>"ruby", :framework=>"Rails: ", :server=>{:host=>"servidor", :root=>"C:/workspace/efact", :pid=>3816}, :ier=>{:name=>"rollbar-gem", :version=>"2.15.5"}, :body=>{:trace=>{:frames=>lename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.10.0/lib/puma/thread_poo, :lineno=>120, :method=>"block in spawn_thread"}, {:filename=>"C:/Ruby22/lby/gems/2.2.0/gems/puma-3.10.0/lib/puma/thread_pool.rb", :lineno=>120, :met"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.10.0/lib/purver.rb", :lineno=>301, :method=>"block in run"}, {:filename=>"C:/Ruby22/liy/gems/2.2.0/gems/puma-3.10.0/lib/puma/server.rb", :lineno=>437, :method=>"ss_client"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.10.0/lia/server.rb", :lineno=>605, :method=>"handle_request"}, {:filename=>"C:/Rubib/ruby/gems/2.2.0/gems/puma-3.10.0/lib/puma/configuration.rb", :lineno=>22ethod=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-5.ib/rails/engine.rb", :lineno=>522, :method=>"call"}, {:filename=>"C:/Ruby22ruby/gems/2.2.0/gems/rack-cors-1.0.2/lib/rack/cors.rb", :lineno=>97, :methoall"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/ile.rb", :lineno=>111, :method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/ge2.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/static.rb", :linen6, :method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/action5.0.6/lib/action_dispatch/middleware/executor.rb", :lineno=>12, :method=>"c, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/activesupport-5.0.6/lib/a_support/cache/strategy/local_cache_middleware.rb", :lineno=>28, :method=>"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/runtb", :lineno=>22, :method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2ms/actionpack-5.0.6/lib/action_dispatch/middleware/request_id.rb", :lineno=:method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-/lib/rails/rack/logger.rb", :lineno=>26, :method=>"call"}, {:filename=>"C:/2/lib/ruby/gems/2.2.0/gems/railties-5.0.6/lib/rails/rack/logger.rb", :linen, :method=>"call_app"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/actck-5.0.6/lib/action_dispatch/middleware/show_exceptions.rb", :lineno=>31, :d=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rollbar-2.15.5/ollbar/middleware/rails/show_exceptions.rb", :lineno=>22, :method=>"call_willbar"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/ltion_dispatch/middleware/debug_exceptions.rb", :lineno=>49, :method=>"call"filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rollbar-2.15.5/lib/rollbar/miare/rails/rollbar.rb", :lineno=>22, :method=>"call"}, {:filename=>"C:/Ruby2/ruby/gems/2.2.0/gems/rollbar-2.15.5/lib/rollbar.rb", :lineno=>145, :methodoped"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rollbar-2.15.5/lib/ar/middleware/rails/rollbar.rb", :lineno=>24, :method=>"block in call"}, {:ame=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/lib/action_dispatddleware/remote_ip.rb", :lineno=>79, :method=>"call"}, {:filename=>"C:/Rubyb/ruby/gems/2.2.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/execrb", :lineno=>12, :method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.ems/actionpack-5.0.6/lib/action_dispatch/middleware/callbacks.rb", :lineno=:method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/activesup5.0.6/lib/active_support/callbacks.rb", :lineno=>90, :method=>"run_callback{:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/activesupport-5.0.6/lib/actupport/callbacks.rb", :lineno=>750, :method=>"_run_call_callbacks"}, {:file>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/activesupport-5.0.6/lib/active_supportbacks.rb", :lineno=>97, :method=>"__run_callbacks__"}, {:filename=>"C:/Rubyb/ruby/gems/2.2.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/call.rb", :lineno=>38, :method=>"block in call"}, {:filename=>"C:/Ruby22/lib/rums/2.2.0/gems/activerecord-5.0.6/lib/active_record/migration.rb", :lineno=>:method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-2.0./rack/head.rb", :lineno=>12, :method=>"call"}, {:filename=>"C:/Ruby22/lib/rems/2.2.0/gems/rack-2.0.3/lib/rack/conditional_get.rb", :lineno=>25, :methoall"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rack-2.0.3/lib/rack/rb", :lineno=>25, :method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.ems/warden-1.2.7/lib/warden/manager.rb", :lineno=>35, :method=>"call"}, {:fme=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/warden-1.2.7/lib/warden/manager.rb"neno=>35, :method=>"catch"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gemden-1.2.7/lib/warden/manager.rb", :lineno=>36, :method=>"block in call"}, {name=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/timber-2.6.1/lib/timber/integratiack/http_context.rb", :lineno=>20, :method=>"call"}, {:filename=>"C:/Ruby22ruby/gems/2.2.0/gems/timber-2.6.1/lib/timber/current_context.rb", :lineno=>method=>"with"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/timber-2.6b/timber/current_context.rb", :lineno=>64, :method=>"with"}, {:filename=>"Cy22/lib/ruby/gems/2.2.0/gems/timber-2.6.1/lib/timber/integrations/rack/httpext.rb", :lineno=>21, :method=>"block in call"}, {:filename=>"C:/Ruby22/lib/gems/2.2.0/gems/timber-2.6.1/lib/timber/integrations/rack/session_context.:lineno=>24, :method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gimber-2.6.1/lib/timber/integrations/rack/user_context.rb", :lineno=>75, :me>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/timber-2.6.1/lib/r/integrations/rack/http_events.rb", :lineno=>166, :method=>"call"}, {:file>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/timber-2.6.1/lib/timber/integrations/rrror_event.rb", :lineno=>26, :method=>"call"}, {:filename=>"C:/Ruby22/lib/rems/2.2.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb", no=>727, :method=>"call"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/npack-5.0.6/lib/action_dispatch/journey/router.rb", :lineno=>26, :method=>""}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/lib/acdispatch/journey/router.rb", :lineno=>26, :method=>"each"}, {:filename=>"C:22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/lib/action_dispatch/journey/rorb", :lineno=>39, :method=>"block in serve"}, {:filename=>"C:/Ruby22/lib/rums/2.2.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb", :o=>32, :method=>"serve"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/apack-5.0.6/lib/action_dispatch/routing/route_set.rb", :lineno=>50, :method=patch"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/ltion_controller/metal.rb", :lineno=>262, :method=>"dispatch"}, {:filename=>uby22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/lib/action_controller/metal :lineno=>190, :method=>"dispatch"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2gems/actionpack-5.0.6/lib/abstract_controller/base.rb", :lineno=>126, :methprocess"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/activerecord-5.0b/active_record/railties/controller_runtime.rb", :lineno=>18, :method=>"proaction"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/ction_controller/metal/params_wrapper.rb", :lineno=>248, :method=>"process_n"}, {:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-5.0.6/lib/a_controller/metal/instrumentation.rb", :lineno=>30, :method=>"process_actio{:filename=>"C:/Ruby22/lib/ruby/gems/2.2.0/gems/activesupport-5.0.6/lib/actupport/notifications.rb", :lineno=>166, :method=>"instrument"}, {:filename=Ruby22/lib/ruby/gems/2.2.0/gems/
[Rollbar] Reporting internal error encountered while sending data to Rollba
[Rollbar] Sending item
[Rollbar] Success
[Rollbar] Details: https://rollbar.com/instance/uuid?uuid=8b7c03b2-d662-46ca-6f7e5e331f05 (only available if report was successful)

**Comment by rivkahstandig3636** [comment]
Hi @augustosamame, thanks for reporting this issue! We'll take a look into it.

**Comment by rokob** [comment]
This looks like a Ruby installation issue with respect to specifying where the SSL certificates live and not a Rollbar issue.
