### ISSUE TITLE
Tracing through Libs and Modules

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#671]
[USER]:
I was hoping more for a way to just do the same thing that the loggings in a controller action do. If I log three times and look at the third log on Rollbar, I’ll see the previous two as part of the history of the third. In this case I want to continue by passing in the request/current_user as a scope or transform on the logger (perhaps in a before action to simplify) and then any further calls done in lib calls in same app instance to pick it up and have it automatically join with those previous ones. I would like the Rollbar namespace pick this up “globally” to match what the current controller request is sending it already.

I was hoping for something similar to what is done with the rollbar_request_data_method in https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/rails/controller_methods.rb but for libs, specifically, modules we have written ourselves.

Internal: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/14219614455

**Comment by kevinelliott** [comment]
Thank you. Looking forward to this.
