### ISSUE TITLE
Feature Request: Configure Rollbar Logger

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#673]
add a config option to make this output configurable:

internal: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/14310092793

```I, [2018-01-27T20:11:40.717018 #29297] INFO -- : [Rollbar] Scheduling item
I, [2018-01-27T20:11:40.717163 #29297] INFO -- : [Rollbar] Sending item
I, [2018-01-27T20:11:40.789613 #29297] INFO -- : [Rollbar] Success
I, [2018-01-27T20:11:40.789822 #29297] INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=aa7d08f6-f5f7-4606-a418-f83b1db67dd8

**Comment by waltjones** [comment]
This can be disabled via the `logger_level` config setting, now documented in the Ruby configuration reference. (e.g. set to `'warn'`.)
