### ISSUE TITLE
Fix failing jruby builds

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-gem#686]

**Comment by waltjones** [comment]
Current JRuby status for RSpec test matrix:
* Travis supports these JVMs, which now load correctly: openjdk7, openjdk8, oraclejdk8, oraclejdk9
* We have been attempting to build Travis targets jruby-18mode and jruby-19mode. These currently fail on dependency version errors. I have not found any past build where they succeeded. (Not the RSpec suite, just the JRuby itself getting through bundle install.) If you know of a build that worked, please send the branch, sha, or PR.
* I'm looking into whether there are better JRubies on Travis that we could/should use.

If you are a JRuby Rollbar user and have input or suggestions on what you'd like to see supported, let us know.

**Comment by jessewgibbs** [comment]
@waltjones thanks for the update.  Unless there are further things you want to fix, I think we can close this issue.

**Comment by waltjones** [comment]
Current JRuby is now enabled in Travis for Rails 5.x. See related PR for details.
