### ISSUE TITLE
support cheaper ignore in config.before_process

### ISSUE THREAD

**Issue by grosser** [rollbar/rollbar-gem#691]
Would be nice if returning `:ignore` or something like that worked too so I don't have to raise and exception, which is kinda expensive and pollutes debug output

**Comment by rivkahstandig3636** [comment]
Thanks for the suggestion @grosser!

**Comment by ArturMoczulski** [comment]
@grosser I'm not sure I understand. You want to be able to trigger ignoring by returning `:ignore` instead of having to raise `Rollbar::Ignore`?

**Comment by grosser** [comment]
yes, since that would be far cheaper (cpu/memory) than raising+catching an
exception
