### ISSUE TITLE
failsafe: can't modify frozen NoMemoryError

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#693]
Failsafe from rollbar-gem. RuntimeError: "can't modify frozen NoMemoryError" in /home/deployer/smscontact/gems/gems/rollbar-2.15.5/lib/rollbar/notifier.rb:195:in `inspect': error in process_item

there is no orig_uuid.

internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/14873052534

**Comment by jondeandres** [comment]
This looks to be an error while logging an exception trying to send an occurrence. That action failed, it was tried to be logged and the logging action also failed. Looking at the exception what I conclude is that that server didn't have enough memory.

If there are not important consequences related to this I'd vote for closing the issue.
