### ISSUE TITLE
Can't get "person" information

### ISSUE THREAD

**Issue by vfonic** [rollbar/rollbar-gem#697]
Hi,

I'm using rollbar on my heroku app, which is also a Shopify app. I have a helper method called `current_shop`. It's defined in one of app's helpers. In every controller I have:

```rb
include MyCustomHelper # defines current_shop method
helper_method :current_shop
```

I can use my helper method `current_shop` anywhere in controller and in views. 
This is my rollbar configuration:
```rb
# ...
  config.person_method = 'current_shop'
  # config.person_id_method = "my_id"
  config.person_username_method = 'shopify_domain'
# Shop model (returned by `current_shop` method) has :id and :email columns
# ...
```

However, whenever the error gets reported to rollbar, I don't see any shop-related information.

What am I missing?

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski Could you take a look at this issue?

**Comment by ArturMoczulski** [comment]
@vfonic what are you returning from `current_shop`. Rollbar doesn't blindly add whatever you return from `person_method`. In fact it runs `person_id_method`, `person_email_method` and `person_email_method` on whatever was returned from `person_method`.

Here is the implementation:
https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/rails/controller_methods.rb#L8-L22

**Comment by vfonic** [comment]
@ArturMoczulski `current_shop` returns an instance of Shop ActiveRecord model. It contains `id` and `email` attributes. For the `username`, I edited the Rollbar configuration, as pointed out above, to return `shopify_domain`. 

I just checked in the Rollbar, and it seems to be reporting correctly now. :)

Thanks for following up!
