### ISSUE TITLE
(request) Support Rails 5.2 Content Security Policy

### ISSUE THREAD

**Issue by brian-kephart** [rollbar/rollbar-gem#698]
The current implementation for using rollbar.js with this gem uses an inline script, which requires that the CSP (if any) allows 'unsafe-inline' scripts.

[Looking through the code](https://github.com/rollbar/rollbar-gem/blob/f4c1afc9e2b269e9e5298440581e8b76f6cb5ffa/lib/rollbar/middleware/js.rb#L141), it appears that this issue is already solved using a nonce for users of the secure-headers gem, but no such fix is applied for the new built-in CSP feature of Rails 5.2.

**Comment by rivkahstandig3636** [comment]
Thanks for the report!

**Comment by waltjones** [comment]
With the linked PR, this is available on master, and in the next release.
