### ISSUE TITLE
Roll bar seems to be logging Delayed Job errors twice

### ISSUE THREAD

**Issue by RobWillison** [rollbar/rollbar-gem#699]
Hi,

We are using delayed job with a max retry of 5 after which the delayed job is marked as failed. When the job errors for the 5th time the exception is reported twice once in the injoke_job hook and once in the failure hook. https://github.com/rollbar/rollbar-gem/blob/ffd4278332cc63b6dc29cde5fc3716793c455bec/lib/rollbar/plugins/delayed_job/plugin.rb#L13-L15

Is there are way to disable error reporting on failed jobs, as this second report is not helpful to us?

Thanks

Rob

**Comment by RobWillison** [comment]
Just noticed the `::Rollbar.configuration.report_dj_data` config setting, ignore me.

Thanks

**Comment by rivkahstandig3636** [comment]
We'll take a look into this.

**Comment by ArturMoczulski** [comment]
Will address in the upcoming release

**Comment by ArturMoczulski** [comment]
@RobWillison this can be achieved by setting
```ruby
config.dj_threshold = 6
```
in your `config/initializers/rollbar.rb`

This way Rollbar will only report the error on `:failure` hook and not report on `:invoke_job` hook.

**Comment by drewB** [comment]
Is there a way to set the threshold on a per job class basis or per queue?  For example, some jobs we would want the error reported right away and others we would want to set a higher threshold.

**Comment by waltjones** [comment]
Hi @drewB, can you open a new issue for this, and describe your use case? This will also make it easier for others to comment on the proposed change.

Thank you!
