### ISSUE TITLE
Scope config.person_method to subdomain

### ISSUE THREAD

**Issue by danielbonnell** [rollbar/rollbar-gem#701]
Hello,

This may be more of a feature request than a bug. I would like to be able to change the `config.person_method` that is assigned in `/config/initializers/rollbar.rb` dynamically. For example, if a user is on `foo.example.com` I want `config.person_method = 'current_employer'`, however if they are on `bar.example.com` I want `config.person_method = 'current_contact`. I've got two user models and numerous sub domains. Currently I'm only able to capture person data for one of these user models, which is very limiting when trying to debug errors.

If this is not currently possible, can you consider adding this ability? Thanks!

**Comment by rivkahstandig3636** [comment]
Interesting feature request! We'll add it to a future release.

**Comment by ArturMoczulski** [comment]
This seems like a very project specific request and I believe an easy way to achieve that would be by putting the appropriate resolution logic based on subdomain in your business logic. Consider the following pseudo-code:

```ruby
Rollbar.configure do |config|
  config.person_method = controller.current_user
end

class Controller
  def current_user
    if (@request.original_url == 'foo.example.com')
      current_employer
    else
      current_contact
    end
  end
end
```

**Comment by danielbonnell** [comment]
I'll have to test it out but it looks like it should do the trick.

**Comment by ArturMoczulski** [comment]
I'm closing the issue for now.
