### ISSUE TITLE
Wrong IP addresses on some items

### ISSUE THREAD

**Issue by rrrodrigo** [rollbar/rollbar-gem#704]
Hello!

Some of the errors from our app on Rollbar have wrong IP addresses. By wrong I mean either 127.0.0.1 or a non-public address, in case where the request causing the error came obviously from some place on the internet with a public IP address. 

I looked at [rollbar_user_ip method in RequestDataExtractor module](https://github.com/rollbar/rollbar-gem/blob/v2.15.6/lib/rollbar/request_data_extractor.rb#L133) which returns the IP address for submission to Rollbar. I see it examines 4 possible sources of address info and returns the first available. It still might be possible that returned address is non-public while the right one is omitted, being further behind in the pipeline. For example, if `env['HTTP_X_REAL_IP']` is 10.0.0.10 (wrong) and `env['REMOTE_ADDR']` is 1.2.3.4 (right), Rollbar item will display the first, wrong IP address.

Here's an idea: let's examine **all** the available addresses together, like it is done for these inside X-Forwarded-For header and return the first public one. There's already [a method for that in the codebase](https://github.com/rollbar/rollbar-gem/blob/v2.15.6/lib/rollbar/request_data_extractor.rb#L149) but it is  used only on data from one header, not on the whole set.

I'll be testing a monkey patch implementing this idea in production environment of our app. Should anyone consider it potentially useful, I'd be happy to submit a PR in a few weeks.

**Comment by rivkahstandig3636** [comment]
Thanks for the report!

**Comment by jondeandres** [comment]
@rrrodrigo can you provide us few examples with all the available IP headers you can find in your occurrences?

It sounds pretty complicated find a solution that will work for everyone, unless we add a configuration option that takes precedence over the default behavior. Also, if you explain us a bit more about your web architecture we might be able to understand better what to do

**Comment by jessewgibbs** [comment]
I'm going to close this pending a response from @rrrodrigo.
