### ISSUE TITLE
Gem release for 2.15.6 ?

### ISSUE THREAD

**Issue by thbar** [rollbar/rollbar-gem#707]
It looks like v2.15.6 is available as a [tagged release on GitHub](https://github.com/rollbar/rollbar-gem/releases/tag/v2.15.6).

Is it an official release?

If yes, I wonder why it's not appearing in the [changelog](https://github.com/rollbar/rollbar-gem/blob/master/CHANGELOG.md) and not on [rubygems](https://rubygems.org/gems/rollbar)?

For some context, I'm willing to deploy it to get a fix for #658 - but I'd prefer to deploy an "official" release for this specific client.

Thanks!

**Comment by rivkahstandig3636** [comment]
Hi @thbar, it's an official release. We'll get that fixed! Sorry about that.

**Comment by michaelglass** [comment]
it's now released
