### ISSUE TITLE
Implementation of Rollbar Custom Fingerprinting

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#709]
User: this is for the community maintained repo - heroku/rack-timeout regarding their implementation of Rollbar Custom Fingerprinting. Their implementation was never updated for a change in the rollbar gem a while back. seems like that gem does not have a proper maintainer atm, but there is some discussion. I think it would help to have a a Rollbar developer familiar with this system recommend whether the gem should update the method calls or add a recommended custom_fingerprinting setting

internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/15493944773

**Comment by stevenjonescgm** [comment]
https://github.com/heroku/rack-timeout/issues/122 is the referenced issue that would benefit from Rollbar's attention

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by rokob** [comment]
I would advise that gem to stop monkey patching Rollbar for the custom fingerprinting and instead just advise via the docs on a custom fingerprint to add via the Rollbar UI.
