### ISSUE TITLE
Allow passing the JS checkIgnore function

### ISSUE THREAD

**Issue by alexdunae** [rollbar/rollbar-gem#710]
Hi there -- I see in [the docs](https://rollbar.com/docs/filter-or-ignore-errors-from-bots/) that there's an option to filter script errors with a `checkIgnore` option.  Would it be possible to add as a config option to the gem?

**Comment by brianr** [comment]
Have you tried https://github.com/rollbar/rollbar-gem#before-process-hook ?

**Comment by alexdunae** [comment]
That looks like it’s for ignoring server-side errors and events -- is that right?.  

I’m wanting to filter out client-side errors (specifically a bunch of `__firefox__.searchQueryForField is not a function` etc errors that Firefox is triggering)

**Comment by brianr** [comment]
Ah, yes... in that case, I think your question really is how to set `checkIgnore` via [`config.js_options`](https://github.com/rollbar/rollbar-gem#integration-with-rollbarjs).

@rokob @ArturMoczulski any ideas?

**Comment by ArturMoczulski** [comment]
Added to the upcoming release
