### ISSUE TITLE
Consider an integration with exception notifier

### ISSUE THREAD

**Issue by Startouf** [rollbar/rollbar-gem#711]
The [exception notifier](https://github.com/smartinez87/exception_notification) gem allows to wrap several notifiers (email, slack, etc.). It would be nice to have a Rollbar notifier plugin for this gem

I know this can feel like a duplicate tool since Rollbar offers to some extent the same functionalities via the web interface, exception_notifier is agnostic and but you'd be able to very easily integrate with existing systems (almost 2k likes on the exception notifier gem). Also it would make migrating much easier.

Currently if I want to integrate Rollbar, I'd have to add code everywhere, whereas if there was an exception_notifier extension I could get everything for free.

Mirror issue https://github.com/smartinez87/exception_notification/issues/413

**Comment by Startouf** [comment]
I'm in the process of writing a custom adapter but it seems all rollbar requests are sent in duplicates. If I understand well, there is a railties that already adds the Rollbar as some kind of middleware. 
Until supported, I'll need to monkeypatch to disable this integration since I want to have control of Rollbar notifications via Exception notifier

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by jessewgibbs** [comment]
Marking this as `wontfix` as we're not going to be able to consider this any time soon.
