### ISSUE TITLE
Add scrub whitelist config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-gem#722]
Similar to Rollbar-PHP's `scrub_whitelist`: an array of fields that you do NOT to be scrubbed even if they match entries in scrub_fields.

**Comment by scottyp-env** [comment]
I was looking for this too and did some digging through the closed issues, looks like this is already supported in #795. It's not added to https://docs.rollbar.com though. Can we open an issue to get the docs updated?

**Comment by waltjones** [comment]
@scottyp-env Yes, will do. Thank you for the report!

**Comment by waltjones** [comment]
Doc is updated.
