### ISSUE TITLE
Apps without assets can't be deployed anymore

### ISSUE THREAD

**Issue by roeltm** [rollbar/rollbar-gem#725]
Since v2.15.6 there is a new task being executed after the `deploy:compile_assets` task, which is defined in the [capistrano-rails gem](https://github.com/capistrano/rails):

https://github.com/rollbar/rollbar-gem/blob/7b140beed71602f620c54e9d84521ab50fc8d565/lib/rollbar/tasks/rollbar.cap#L68

First of all, this appears to create a very strong dependency on (capistrano-)rails which might be intended, but not something I expected.

Secondly, when I'm developing an app without assets I will not include the `capistrano/rails/assets` task (because it will fail) and this will, understandably, result in the following error:

```Don't know how to build task 'deploy:compile_assets' (see --tasks)```

Am I missing something, or should this task be conditional based on whether capistrano-rails is available and assets exist?

**Comment by rivkahstandig3636** [comment]
We will take a look into this.

**Comment by sixfeetover** [comment]
I just hit this as well, but the app I'm working with _does_ compile assets. I had to move the `require 'rollbar/capistrano3'` line to be _after_ `require 'capistrano/rails/assets'`.

**Comment by amasses** [comment]
We also have this issue - our App is API based, so no assets, and in order to make this work we had to add the following **before** the `require 'rollbar/capistrano3'` line:

```ruby
# Noop for Rollbar...
namespace :deploy do
  desc 'NOOP operation - rollbar needs this tho...'
  task :compile_assets do
  end
end
require 'rollbar/capistrano3'
```

**Comment by ArturMoczulski** [comment]
A solid solution for this needs to be prepared. I know that some of our users took a shot at this already, but without much success. I'm moving this to this current milestone `v2.17.0` and will come up with a fix soon.
