### ISSUE TITLE
Discarding original exception when reporting failsafe

### ISSUE THREAD

**Issue by jjb** [rollbar/rollbar-gem#733]
in these places:

* https://github.com/rollbar/rollbar-gem/blob/51b637167c26015571ecc154dac96dcadb4efe04/lib/rollbar/notifier.rb#L148-L155
* https://github.com/rollbar/rollbar-gem/blob/51b637167c26015571ecc154dac96dcadb4efe04/lib/rollbar/notifier.rb#L236-L243
* https://github.com/rollbar/rollbar-gem/blob/51b637167c26015571ecc154dac96dcadb4efe04/lib/rollbar/notifier.rb#L411-L416

When an exception happens while putting together the item, only the error that happened while doing that (`e`) is reported. The original error (`item`, `exception`) is discarded.

What do you think of writing the original error to STDOUT in these cases?

**Comment by rivkahstandig3636** [comment]
That sounds good to me. What do you think @ArturMoczulski?

**Comment by jjb** [comment]
Would you like me to take a stab at this?

**Comment by rivkahstandig3636** [comment]
That would be great @jjb!

**Comment by ArturMoczulski** [comment]
Done in `master` and will be released in `v2.18.0`.
