### ISSUE TITLE
Recursive Rollbar submission condition can crash the process

### ISSUE THREAD

**Issue by bnekolny** [rollbar/rollbar-gem#741]
We had an issue where some of our rails processes were crashing occasionally. After doing a bit of investigation we realized that it was in a code path where we were rescuing from errors within the `current_user` method.

Rollbar uses a default of `current_user` to populate `person_data`, but regardless of the `person_data_method` if an application attempts to submit an error within a rescue block of the `person_data_method` the Rollbar submission will attempt to retrieve person data, causing an infinitely recursive error state.

I haven't gotten a chance to dig into the Rollbar code to propose where to determine the stack level and escape from the recursive loop, but I do have a gist with our solution. We're ultimately past the issue, but I thought it'd be useful to share with someone the challenges we had with catching an error and submitting something to Rollbar within the `person_data_method`.

here's the gist: https://gist.github.com/bnekolny/0bfb49cf89ca9deb351cbb99c0238ff6
```
def current_user
  # do something, that might raise an exception
rescue => error
  Rollbar.with_config(person_method: 'invalid-method-name') do
    Rollbar.error('current_user error',
      error_message: error,
      person_data: {id: nil, username: '', email: ''},
    )
  end
  { 'id': nil, 'username': nil, 'email': nil }
end
```

**Comment by rivkahstandig3636** [comment]
Thanks for reporting this! We'll investigate.

**Comment by ArturMoczulski** [comment]
@bnekolny thanks for submitting. This needs to get thought through and a solution prepared. I'm moving this to milestone `v2.18.0`
