### ISSUE TITLE
CHANGELOG.md doesn't cover latest version "2.16.0"

### ISSUE THREAD

**Issue by TimStrietzel** [rollbar/rollbar-gem#748]
On the rollbar website we get the hint:
_rollbar-gem version 2.16.0 is now available. (This project is currently using version 2.15.5)._

But on the linked changelog ( https://github.com/rollbar/rollbar-gem/blob/master/CHANGELOG.md ) the latest release notes only cover v "2.15.6" and not "2.16.0" , yet.

Please add new release notes to the changelog, otherwise this discrepancy is quite confusing.

Thank you!

**Comment by rivkahstandig3636** [comment]
Thanks for the feedback! We're working on fixing this. We're moving from using Changelogs to just using release notes. This will be updated later this week.
