### ISSUE TITLE
Release notes for 2.16.0

### ISSUE THREAD

**Issue by sajmoon** [rollbar/rollbar-gem#749]
On my dashboard I am presented with a message to upgrade to 2.16.0 with a link to the release notes.

The link takes me to the Changelog.

The Changelog is not updated.

Neither in 2.16 https://github.com/rollbar/rollbar-gem/blob/v2.16.0/CHANGELOG.md nor in master https://github.com/rollbar/rollbar-gem/blob/master/CHANGELOG.md

**Comment by rivkahstandig3636** [comment]
Thanks for the feedback! We're working on fixing this. We're moving from using Changelogs to just using release notes. This will be updated later this week.
