### ISSUE TITLE
Scrubber retains password lengths

### ISSUE THREAD

**Issue by odayvhl** [rollbar/rollbar-gem#750]
The rollbar gem masks sensitive data like passwords in HTTP requests intercepted but the length of the password is still known. Instead of replacing each character with a "*" can the rollbar gem replace the whole thing with "[FILTERED]"?

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski @rokob What are your thoughts on this?

**Comment by ArturMoczulski** [comment]
This can be easily configure with `randomize_scrub_length`:

https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/scrubbers.rb#L6
