### ISSUE TITLE
Scrubbing X-Forwarded-For header when collect_user_ip = false

### ISSUE THREAD

**Issue by AbigailMcP** [rollbar/rollbar-gem#751]
As added in the most recent release, I'm setting `config.collect_user_ip = false` to turn off IP collection.

Works great! Only thing is, I would expect this option to also scrub the `X-Forwarded-For` header?

I also can't find any mention of this new config option in the documentation anywhere?

**Comment by ArturMoczulski** [comment]
I believe the `X-Forwarded-For` header should get scrubbed in this case as well. We are having a conversation about this with the team. I believe this is an urgent issue so I'm moving to the current milestone `v2.16.1`
