### ISSUE TITLE
Errors in background threads are not recorded

### ISSUE THREAD

**Issue by timoteialbu** [rollbar/rollbar-gem#753]
I looked through your open and closed issues and could not find anything similar.

Take the following code:

```
 def self.do_something()
      Thread.new do
        raise "Are async exceptions being recorded?"
      end
end
```

That 'raise' is never recorded by Rollbar. I contacted Rollbar chat support and they suggested enabling `config.use_async = true` but that did not solve our issue either, so I was told to open a issue on here. Please advise. 

Thank you!

**Comment by rivkahstandig3636** [comment]
Thanks for the report! We'll take a look into this.

**Comment by ArturMoczulski** [comment]
@timoteialbu What kind of app is this? Rails? Or simple Ruby?

If simple Ruby, are you adding Rollbar reporting to you exception handling logic?

In plain Ruby apps, uncaught exceptions will not get auto-magically reported. You have to add reporting in your exception handling logic.
