### ISSUE TITLE
Publish 2.16.1 to rubygems

### ISSUE THREAD

**Issue by petevk** [rollbar/rollbar-gem#755]
I'm not sure if this is the place to report this, but can the 2.16.1 release get pushed to rubygems? The newest version seems to be 2.16.0 right now.

Actually, it looks like the version in `lib/rollbar/version.rb` is still 2.16.0. Does this mean this is the latest version? Why are there release notes for 2.16.1?

Thanks!

**Comment by rivkahstandig3636** [comment]
Hi there, This has been released on rubygems, sorry about that!
