### ISSUE TITLE
Ignoring @app.call() in other middleware on error

### ISSUE THREAD

**Issue by n00ge** [rollbar/rollbar-gem#756]
Is there a way to "ignore" a line in Rollbar stacktrace highlights? Right now, with middleware I'm using for a project, it always highlights the @app.call(env) call even though that's not where the error occurred. I don't think I want to use [silencing](https://docs.rollbar.com/docs/ruby#section-silencing-exceptions-at-runtime) as it seems like that would ignore all errors in the app because they're running within that call. But maybe I'm wrong?

**Comment by ArturMoczulski** [comment]
Not sure if I understand correctly. Do you want to remove selected frames from the stack trace?

**Comment by jessewgibbs** [comment]
Closing this since there's been no response in nearly a month.
