### ISSUE TITLE
anonymize_user_ip persists full IP in headers

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#758]
For the Rails applications, when this options is enabled, the full IP address is still present in headers, ie `X-Forwarded-For` and `X-Real-Ip`.

I'm wondering if it should be handled by the gem or by hand by developers. Then I guess some note in docs would be helpful.

**Comment by rivkahstandig3636** [comment]
@ArturMoczulski @rokob What are your thoughts on this?

**Comment by ArturMoczulski** [comment]
We should anonymization for both. I will address this right away.

**Comment by ArturMoczulski** [comment]
Fixed. Will be released in the next tag.

**Comment by morgoth** [comment]
Thank you
