### ISSUE TITLE
Active Job adapter for delivering errors

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#759]
Would it be possible to add support for AJ adapter for delivering errors?
It's missing now https://github.com/rollbar/rollbar-gem/tree/master/lib/rollbar/delay

I think it would be a nice addition for Rails apps

**Comment by ArturMoczulski** [comment]
@morgoth I believe that's available as a plugin here https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/active_job.rb

All you have to do is include it in your `ActiveJob` implementation like so:

app/jobs/application_job.rb
```ruby
class ApplicationJob < ActiveJob::Base
  include Rollbar::ActiveJob
end
```

Let me know if this helps. If you have further questions, please comment and I'll reopen the issue.

**Comment by morgoth** [comment]
@ArturMoczulski I was thinking about a way to deliver errors by AJ and not reporting errors in AJ.
So having configuration option, something like:
`config.use_active_job` that would use any background job backend that is configured in AJ

**Comment by ArturMoczulski** [comment]
@morgoth this is available already. Here is how you enable reporting through DJ:
`config.use_delayed_job`

There are also other job handlers:
`config.use_sidekiq`
`config.use_resque`
`config.use_shoryuken`
`config.use_thread`
`config.use_sucker_punch`

Enabling any of the above will result in reporting through a background job backend.

Does this answer your question?

**Comment by ArturMoczulski** [comment]
I see. So you mean, you would like us to support ActiveJob as an abstract and not necessarily a specific implementation, is that correct? So that you don't have to reconfigure Rollbar at all and only rely on what is configured in Rails as the AJ implementation. Did I get that right?

**Comment by morgoth** [comment]
Yes, exactly :)
