### ISSUE TITLE
How do I scrub `body.trace.extra.error_message` ?

### ISSUE THREAD

**Issue by r-obert** [rollbar/rollbar-gem#770]
Hello,

`body.trace.extra.error_message` contains not just a backtrace, but also other information about the request, including its environment. The environment includes, among other things, `PASSENGER_CONNECT_PASSWORD`, which I do not want to send to rollbar.

How can I make sure `PASSENGER_CONNECT_PASSWORD` is not sent to rollbar?
Are you sure it is safe and a good idea to print all this extra information in `body.trace.extra.error_message` ? I just spotted another parameter I do not want to send to you guys, including in the same field.

**Comment by r-obert** [comment]
other data being sent is `action_dispatch.secret_key_base`, it is included in this same field: `body.trace.extra.error_message`

**Comment by r-obert** [comment]
sorry, my mistake, i was sending this extra info myself! sorry for the noise.

**Comment by rivkahstandig3636** [comment]
Glad you were able to figure it out @r-obert!
