### ISSUE TITLE
Net::ReadTimeout

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#775]
internal - https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/18369851469

When would Rollbar gem report `Net::ReadTimeout` and is this an error with the user's set up that can be fixed?

**Comment by jessewgibbs** [comment]
@jondeandres any ideas about this?

**Comment by ArturMoczulski** [comment]
@ajtran `read_timeout` threshold can be set in the configuration. Increasing it might resolve the issue. But more likely, we will need more information about the data that is being reported to Rollbar. Can you try to find out what the user is trying to report?
