### ISSUE TITLE
What would it take to use oj 3.x?

### ISSUE THREAD

**Issue by lastobelus** [rollbar/rollbar-gem#780]
oj 3 is pretty mature at this point, and offers advantages for rails projects.

**Comment by lastobelus** [comment]
(it's possible there is no issue, and the rails_51.gemspec is just out of date, as using `gem "oj"` with `gem "rollbar"` does not pin oj, we'll see if I have any reporting issues running rollbar in production)

**Comment by jessewgibbs** [comment]
Hey @lastobelus - Can you try this out as you described in your last comment and reopen the issue if you run into problems?
