### ISSUE TITLE
Fix timeouts in Travis builds on bundle install

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-gem#781]

**Comment by jessewgibbs** [comment]
@ArturMoczulski is this still an issue?

**Comment by waltjones** [comment]
@ArturMoczulski can you let us know what Ruby version you are using?

**Comment by rokob** [comment]
I think this was related to just sporadic travis build failures that were happening in the past. We can probably close this and make it part of the more general "fix the tests" issue.

**Comment by ArturMoczulski** [comment]
@waltjones in the past travis builds would sporadically fail during the `bundle install` step. However, I haven't seen it happening in a while thus we can close this issue for now and come back to this if comes up again. Especially, after the tune ups you just did to the build matrix

**Comment by waltjones** [comment]
Yes, the timeouts I saw (all JDK builds) are fixed now.
