### ISSUE TITLE
Sidekiq with failover as Delay::Thread is not working as expected

### ISSUE THREAD

**Issue by dhunnapotha** [rollbar/rollbar-gem#784]
Below is the rollbar config I have
```
  config.use_sidekiq 'queue' => 'default'
  config.failover_handlers = [Rollbar::Delay::Thread]
```
When the redis server is down, I was expecting the Delay::Thread to be called and it would send the exception to rollbar service. But, that isn't happening. 

When I looked further, I found [here](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/notifier.rb#L673-L683), that a failover handler will be called only when an exception is raised which seems good enough. 

But, the sidekiq-client isn't throwing exception this case. It outputs the below statement though:
```
 [ReliablePush] Enqueueing job locally due to Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
```

So, result being, the exceptions are not reported to Rollbar server when the default async handler is Sidekiq and when redis isn't up.

**Note:** I have been testing this out on local development setup. I'm exploring how to asynchronously report errors to rollbar.

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you take a look at this?

**Comment by ArturMoczulski** [comment]
Thanks for reporting @dhunnapotha 

This has been fixed in `master` and will be including in the upcoming release
