### ISSUE TITLE
application stack traces not appearing in Rollbar for errors in development mode

### ISSUE THREAD

**Issue by dwegman** [rollbar/rollbar-gem#787]
I've been having trouble getting application stack traces to show up in my Rollbar errors recently.  Here is an example of an error, `NoMethodError: undefined method `*' for nil:NilClass`, which was caught by Rollbar: https://rollbar.com/ValorWater/Aquifer/items/1842/occurrences/57186663629/.

This is happening in my development environment. I have noticed that in my staging environment, the same error does include a stack trace: https://rollbar.com/ValorWater/Aquifer/items/1946/occurrences/57186479861/

In my Rollbar initializer file, I am not setting `config.populate_empty_backtraces` anywhere.  I have experimented with setting `config.populate_empty_backtraces = true`, and found that it includes the non-project frames, but still no application stack trace: https://rollbar.com/ValorWater/Aquifer/items/1950/occurrences/57196108276/

**Comment by jessewgibbs** [comment]
@dwegman thanks for the detailed report.

@ArturMoczulski can you investigate?

**Comment by jessewgibbs** [comment]
@dwegman I'm closing this issue since we haven't heard back from you. If you're still encountering it, please let us know.
