### ISSUE TITLE
Rails `rails generate rollbar` fails in Rails 5

### ISSUE THREAD

**Issue by artemf** [rollbar/rollbar-gem#790]
Have just installed rollbar gem. I'm seeing an error with just running
```
rails generate rollbar
```
in a pretty fresh Rails 5.1 app.

Error:
```
/Users/artemf/.rvm/gems/ruby-2.4.5/gems/rollbar-0.12.15/lib/rollbar/railtie.rb:13:in `block in <class:Railtie>': uninitialized constant ActiveRecord::ConnectionAdapters::ConnectionManagement (NameError)
	from /Users/artemf/.rvm/gems/ruby-2.4.5/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/artemf/.rvm/gems/ruby-2.4.5/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
```

The issue is, `ActiveRecord::ConnectionAdapters::ConnectionManagement` [was removed from AR 5](https://github.com/rails/rails/pull/23807). 

Can you please help me? Maybe I'm just missing something? can't believe the gem doesn't work with rails 5.

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you take a look into this?

**Comment by artemf** [comment]
Tried with a fresh new rails app:
1. Created fresh new 5.1.6 rails app
2. Added `rollbar` and `oj` gems  to Gemfile as [per docs](https://docs.rollbar.com/docs/ruby). Then `bundle install`
3. Run `rails generate rollbar ...`

The same result as in the first post:
```
/Users/artemf/.rvm/gems/ruby-2.4.5/gems/rollbar-0.12.15/lib/rollbar/railtie.rb:13:in `block in <class:Railtie>': uninitialized constant ActiveRecord::ConnectionAdapters::ConnectionManagement (NameError)
	from /Users/artemf/.rvm/gems/ruby-2.4.5/gems/railties-5.1.6.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/artemf/.rvm/gems/ruby-2.4.5/gems/railties-5.1.6.1/lib/rails/initializable.rb:30:in `run'
	from /Users/artemf/.rvm/gems/ruby-2.4.5/gems/railties-5.1.6.1/lib/rails/initializable.rb:59:in `block in run_initializers'
```

Actually, none of the other rails tasks (like `rake routes` or `rails s`) work and fail with the same error as this code from rollbar is run in the global initialization phase.

Anyone else using rollbar gem with the Rails 5 app? That breaking change in AR was done 2+ years ago!

**Comment by ArturMoczulski** [comment]
It looks like you're using a very outdated version of the `rollbar-gem` at `0.12.15`. The file `lib/rollbar/railtie.rb` does not exist in `master` anymore.

Please, update your `rollbar-gem` to the latest release and the problem should be fixed.
