### ISSUE TITLE
Don't know how to build task 'rollbar:test' (see --tasks)

### ISSUE THREAD

**Issue by lsanchezv33** [rollbar/rollbar-gem#791]
Hi!, I have had a problem with Rollbar, I have a project in production, the automatic notifications worked perfectly and from one moment to the next they were not sent again, the project handles clients and it is necessary, if something fails, to know what happened. if i throw controlled errors with Rollbar.error(e) works normal. 

This is my Gemfile:

source 'https://rubygems.org'
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

#// Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.6'

#// Use MySQL2 as the database for Active Record
gem 'mysql2'

#// Use Puma as the app server
gem 'puma', '~> 3.0'

#// Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

#// Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

#// Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'

#// See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

#// Use jquery as the JavaScript library
gem 'jquery-rails'

#// Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

#// Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

#// use for images
gem 'paperclip'
gem 'paperclip-av-transcoder'
gem "paperclip-ffmpeg", "~> 1.2.0"
gem 'paperclip-dimension-validator'

#// use for authentication
gem 'devise', '~> 4.3'

#// use for icons 
gem 'font-awesome-rails'

#// use for user permissions 
gem 'cancancan'

#// use for PDF reports
gem 'prawn'
gem 'prawn-table'

#// use for schedule tasks 
gem 'whenever', require: false

#// use for excel reports
gem 'axlsx_rails'

#// use for communication between js and rb
gem 'gon'

#// use for pagination index
gem 'kaminari'

#// use for add styles into mailers
gem 'premailer-rails'

#// use for documentation for API's 
gem 'swagger-docs'

#// use for documentation of errors in environments
gem 'rollbar'
gem 'oj', '~> 2.12.14'

#// use for manage pictures or attached into S3
gem 'aws-sdk', '~> 3'  #, group: [:production, :test] # change version and packages 
gem 's3_direct_upload' #, group: [:production, :test]

#// use for send notifications
gem 'mailgun_rails'

#// use for push notification iOS
gem 'grocer'

#// use for generate RG codes 
gem 'rqrcode'

#// use for generate bar codes
gem 'barby'

#// use for save images and response format JS
gem 'remotipart', '~> 1.2', github: 'pedantix/remotipart', ref: '7f7989db572976816c03508c335bbc1d8230af78'

#// use for parameters validations with json schema
gem 'json-schema', require: 'json-schema'

#// use to page caching
gem 'redis'
gem 'redis-rails'
gem 'redis-namespace'
gem 'redis-rack-cache'

#// use for manage soap API
gem 'savon', '~> 2.12.0', require: 'savon'

#// use to conecction with Firebase
gem "google-cloud-firestore", require: 'google/cloud/firestore'
gem "google-cloud-storage", require: 'google/cloud/storage'

group :development, :test do
  #// Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  #// use for testing
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_bot_rails', require: false
end

group :development do
  #// Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'

  #// Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  #// use for mail open
  gem 'letter_opener'
end

#// Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'dotenv-rails', :require => 'dotenv/rails-now'
#// -------------------------------------------------------------------------------------

My rollbar.rb

Rollbar.configure do |config|
  #// Without configuration, Rollbar is enabled in all environments.
  #// To disable in specific environments, set config.enabled=false.
  config.access_token = ‘token’

  #// Here we'll disable in 'development':
  config.enabled = true 
  #// unless Rails.env.development?

  config.environment = ENV['ROLLBAR_ENV'].presence || Rails.env
end

#// -------------------------------------------------------------------------------------
versions of de gems: 

Ruby version: 2.3.0, Rails version: 5.0.6, Rollbar version: 2.15.5, Rake version: 12.3.0

When I run the command : rake rollbar:test 
Show me the following:

rake aborted!
Don't know how to build task 'rollbar:test' (see --tasks)
/Users/mi_mac/.rvm/gems/ruby-2.3.0@my_app/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/mi_mac/.rvm/gems/ruby-2.3.0@my_app/bin/ruby_executable_hooks:24:in `eval'
/Users/mi_mac/.rvm/gems/ruby-2.3.0@my_app/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

another solution is to add:  require 'rollbar/rake_tasks' into the Rakefile but this doesn't work either 

could you help me with this error?

**Comment by ArturMoczulski** [comment]
Are you running `rake rollbar:test` in your Rails app directory or the `rollbar-gem` directory? This command is intended to be run from the rails app directory.

**Comment by waltjones** [comment]
I have looked at this using all the same versions:
Ruby version: 2.3.0, Rails version: 5.0.6, Rollbar version: 2.15.5, Rake version: 12.3.0

`bundle exec rake rollbar:test` works both before and after `rails generate rollbar`.

Here are several things you can check:
* Spelling. Make sure there's not a typo in the task name.
* If you installed your gems using bundler, use `bundler exec` to run the rake task.
* Make sure you are running the task from your rails project directory
* Check your Gemfile.lock to verify the rollbar gem is there. Related to this, make sure you didn't have any `bundle install` errors or version conflicts.
