### ISSUE TITLE
sidekiq_threshold not working sometimes

### ISSUE THREAD

**Issue by jasdeepgosal** [rollbar/rollbar-gem#812]
We use the sidekiq_threshold configuration parameter to ignore temporary errors that recover automatically. We currently have it set to 3 jobs but it seems like some of these errors in our workers still end up being reported to Rollbar. 

Here's an example of the occurrence details from Rollbar for a `Net::ReadTimeout: Net::ReadTimeout` that happened once that I would've expected not to have been reported to Rollbar.

field | value
-- | --
Notifier | rollbar-gem 2.18.0
 body.trace.extra.context	| Job raised exception
body.trace.extra.job.args    | ["0cad1ead-ffac-4951-bbf3-7c33731840c3"]
body.trace.extra.job.class    | Donations::ZipCodeUpdater
body.trace.extra.job.queue|     default
body.trace.extra.job.retry   |  20
body.trace.extra.jobstr   |  {"class":"Donations::ZipCodeUpdater","args":["0cad1ead-ffac-4951-bbf3-7c33731840c3"],"retry":20,"queue":"default","jid":"7b292b178da65bd53d3a9c6b","created_at":1546773064.1527147,"enqueued_at":1546773064.1527605}
framework    | Rails: 5.2.1.1
language    | ruby
timestamp    | 1546773124 - 2019-01-06 06:12:04 am
uuid    | 3115265b-dc47-4153-8b30-c4566cf9307a

Here is our rollbar config:

```
require 'rollbar/rails'
Rollbar.configure do |config|
  config.access_token = ENV['ROLLBAR_ACCESS_TOKEN']
  config.enabled = Rails.env.production?
  config.scrub_fields |= [:card_fingerprint]
  config.environment = ENV.fetch('HEROKU_APP_NAME', 'production')
  config.exception_level_filters.merge!(
    {
      'ActiveRecord::RecordNotFound' => 'ignore',
      'ActionController::RoutingError' => 'ignore',
    },
  )
  config.use_sidekiq 'queue' => 'rollbar'
  config.sidekiq_threshold = 3
end
```

And I confirmed that ` Rollbar.configuration.sidekiq_threshold` is indeed `3`.

**Comment by jessewgibbs** [comment]
@jasdeepgosal thanks for providing such a detailed report.

@waltjones can you investigate when you get a chance?

**Comment by waltjones** [comment]
Hi @jasdeepgosal, are you using any other Sidekiq middleware or Sidekiq error handlers? It is possible for another Sidekiq middleware to modify the retry information for the job. And what version of Sidekiq are you using?

Thank you!

**Comment by jasdeepgosal** [comment]
From our Gemfile.lock: sidekiq (5.2.2) / sidekiq-pro (4.0.4)

Here is our sidekiq config: 

```ruby
Sidekiq::Logstash.setup

Sidekiq::Extensions.enable_delay!

Sidekiq.configure_server do |config|
  config.error_handlers << ->(ex, context) { Rollbar.error(ex, context) }

  config.server_middleware do |chain|
    chain.add SidekiqRetryMonitor::Middleware
  end
end

require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Sidekiq::Web.class_eval do
  disable :sessions
end
```

`SidekiqRetryMonitor::Middleware` is a custom piece of middleware that only reads the job information, [here is the source](https://gist.github.com/jasdeepgosal/1b73198cb681c9e3182e1bfda0426141). 

Running `bundle exec sidekiq -v` shows the following (reformatted for readability):

```json
{
  "severity": "DEBUG",
  "message": "Client Middleware: Sidekiq::Batch::Client",
  "@timestamp": "2019-01-30T09:34:24.462Z",
  "@version": "1"
}
{
  "severity": "DEBUG",
  "message": "Server Middleware: Sidekiq::Batch::Server, ScoutApm::BackgroundJobIntegrations::SidekiqMiddleware, Rollbar::Sidekiq::ClearScope, SidekiqRetryMonitor::Middleware",
  "@timestamp": "2019-01-30T09:34:24.463Z",
  "@version": "1"
}
```

Thanks!

**Comment by ArturMoczulski** [comment]
@jasdeepgosal I'm looking into this today. I will update you shortly

**Comment by ArturMoczulski** [comment]
@jasdeepgosal I belive that your issue is the `Rollbar.error` call in the Sidekiq's error handler. `rollbar-gem` should be reporting job failures according to the threshold out of the box. If you added `Rollbar.error` in your Sidekiq `error_handlers` I would assume Sidekiq will call it on each failure regardless of the `sidekiq_threshold` config option which would be the problem you are describing.

Can you try to remove this:
```
Sidekiq.configure_server do |config|
  config.error_handlers << ->(ex, context) { Rollbar.error(ex, context) }
end
```

I believe that's not needed unless you want it for some other reasons. `rollbar-gem` should take care of reporting failed jobs according to the threshold by itself, without having to set up custom `error_handlers`.

Does it make sense?

**Comment by jasdeepgosal** [comment]
Thanks! Yeah, it does make sense. 

I'll try it out and let you know what happens.

**Comment by jasdeepgosal** [comment]
That change appears to have resolved the issue for us. 

Thanks!
