### ISSUE TITLE
Rollbar should offer option to write payload to application log

### ISSUE THREAD

**Issue by sdhull** [rollbar/rollbar-gem#813]
Honestly I cannot for the life of me understand why #425 was merged.

There were 2 issues in the past asking for _opposite_ default behavior (#63 & #66 respectively).

A discussion should have ensued to figure out what offers the most flexibility and what is the desired default behavior. (Instead, the first group of people were told "don't worry, this is already how it works" and the second group of people were told "don't worry, we'll change how it works.")

When the default behavior was to log even when disabled, it's trivial for a developer to both set `config.enabled = false; config.default_logger = Logger.new(IO::NULL)`.
However, now that the default behavior is to suppress logging when Rollbar is disabled, it's actually impossible to get out of this behavior.

If people agree that disabling Rollbar should also set the logger to a null logger to suppress logs from rollbar, I think it's reasonable to implement that, but in a way that would allow those of us _do_ want logging still to bring it back. Maybe add `config.disable!` that also sets the default logger to `IO::NULL`.

But as it stands, this is essentially broken. I want Rollbar reporting off in development, but obviously I'm sending **important debugging info** to Rollbar and obviously _I need important debugging info_ in development. IMO the _correct_ default behavior is to log even when disabled. If people want to disable logging, there's a reasonable way to do it (set the logger to `IO::NULL`).

If maintainers agree, I'd be happy to submit a PR that unwinds #425.

**Comment by sdhull** [comment]
Ugh since we have Rollbar disabled, I wasn't even clear on _what kind of logging_ it does. After enabling it locally I realize this still isn't really what I want. I don't care about metadata about the stuff I send to Rollbar, I care about the actual content that was sent.

Basically, if I have some code

```ruby
begin
  do_something_that_might_raise
rescue => e
  Rollbar.error(e)
end
```
And I have Rollbar disabled in development, I will never know if my method raised. This hampers development & is at odds with having a single way to track errors. My expectation of this tool is that it will not get in the way of being a productive developer. Obviously I could add `raise e if Rails.env.development?` everywhere I use `Rollbar.error` but that's at odds with DRY practices & a stupid thing to have to explain to new developers.

So I guess it's going to take more discussion about good default behavior and more work to implement, since it's not exactly just about unwinding #425

**Comment by jessewgibbs** [comment]
@sdhull thanks for the detailed summary of the issue.  #425 pre-dates the current maintainer team, but the folks involved are still here so we can definitely pull them into a discussion.

@waltjones what do you think should be the best way to configure Rollbar in your dev environment such that exceptions aren't sent to Rollbar but are not suppressed either?

**Comment by sdhull** [comment]
FWIW, I added this monkeypatch yesterday to our codebase (in the rollbar initializer that also sets up config):
```ruby
if Rails.env.development? || Rails.env.test?
  class Rollbar::Notifier
    alias original_log log
    def log(level, *args)
      Rails.logger.send(level, *args)
      original_log(level, *args)
    end
  end
end
```

**Comment by waltjones** [comment]
@sdhull, I will take a look and will post here to get your feedback.

**Comment by waltjones** [comment]
@sdhull, after reviewing this, I have a few comments and a proposed solution.

It is by design that the gem doesn't try to log the payload of the notifier event. This is consistent with the other Rollbar SDK adapters, and the intended design. Instead, hooks are provided at various stages of processing of the event. The `transform` hook (at `config.transform`) is probably best for your needs. You would provide a handler there, and on each event the handler can decide whether and where to log. The app can determine its own format to log the data, as well as any filtering concerns.

However when `config.enabled == false`, these handlers will not be called. We don't want to change the behavior of the `enabled` flag, as other users expect the current behavior. Instead I am proposing a new config flag `config.disable_send` (or similar name) that allows the event to be processed but not sent. By leaving the gem enabled and setting this flag, all processing and hooks will remain enabled, but the event will not be sent to Rollbar.

Would this meet your needs?

**Comment by sdhull** [comment]
@waltjones please review my [comment](https://github.com/rollbar/rollbar-gem/issues/813#issuecomment-459099237) above.

The argument I'm making is that the current defaults in the Rollbar gem are detrimental to the developer experience. The suggestion (essentially "implement a `transform` hook that logs locally & set `enabled` to true and set `disable_send` to true") does not rectify this situation of bad defaults.

If you want to introduce a new configuration option, one that seems more reasonable to me would be `config.also_log_locally` which I could set with `config.also_log_locally = Rails.env.development?`. The implementation could be essentially

```ruby
  class Rollbar::Notifier
    def log(level, *args)
      Rollbar.configuration.logger.send(level, *args) if Rollbar.configuration.also_log_locally
      # existing log method...
    end
  end
```

And I'd argue that you should default `also_log_locally` to `true` in development & test environments.
Line of reasoning is essentially:
1. it's common for developers to disable rollbar in dev & test envs
2. developers send useful information to Rollbar (eg, information they would want to see during local development)

If you disagree with 1 or 2 then maybe makes sense to default to `also_log_locally` to false.

**Comment by waltjones** [comment]
The crux of the issue is this:
> developers send useful information to Rollbar (eg, information they would want to see during local development)

rollbar-gem doesn't log the notifier payload to the application log, even when fully enabled. And the design philosophy for the Rollbar SDKs is that the format of how to log that data is application specific and should be decided by the application.

Currently a `also_log_locally` flag wouldn't mean anything because the gem never writes any part of the payload to the application log.

**Comment by sdhull** [comment]
> rollbar-gem doesn't log the notifier payload to the application log, even when fully enabled.

Right. Because people enable Rollbar in production and presumably are essentially replacing logs with Rollbar. Because who wants to dig through production logs for errors?

However, if people are sending logs to Kibana (or similar) then writing to the application log even in production might be useful. Maybe the option name I suggested is bad. Maybe it should be `also_write_to_application_log`?

> format of how to log that data is application specific and should be decided by the application

Presumably this is why you offer a [`default_logger`](https://docs.rollbar.com/docs/gem-configuration-reference) configuration option?

> Currently a `also_log_locally` flag wouldn't mean anything because the gem never writes any part of the payload to the application log

Right. That's why I also suggested an implementation in that comment to _make_ that flag mean something (eg, to make it work). Did you miss the [code snippet](https://github.com/rollbar/rollbar-gem/issues/813#issuecomment-463406897)?

**Comment by waltjones** [comment]
@sdhull I'm turning this back over to @jessewgibbs. He'll decide on what to do.

**Comment by jessewgibbs** [comment]
This would be new behavior that we would want to add to other SDKs for the sake of consistency.  For now I'm going to flag it as an `enhancement` and stick it into the backlog for future consideration.  PRs welcome if anyone wants to build and document this!

**Comment by sdhull** [comment]
@jessewgibbs gotcha. I'm already overcommitted so unfortunately I can't offer a PR at this time. However I'll keep it on my radar and if I do get a breather I'll see what I can do. FWIW I think the docs will be more work than the implementation 😉

**Comment by philipbjorge** [comment]
@sdhull -- Thanks for opening this issue and including your monkeypatch.

This was surprising behavior for me and my team and we've used the python, nodejs, and .NET integrations -- It's possibly we weren't using them for logging non-fatal warnings and things of that nature at the time.
