### ISSUE TITLE
Malformed url

### ISSUE THREAD

**Issue by arthurio** [rollbar/rollbar-gem#818]
I'm using sinatra with `rackup`:

I added some debug logs in [`rollbar_url`](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/request_data_extractor.rb#L124):

```ruby
    def rollbar_url(env)
      forwarded_proto = env['HTTP_X_FORWARDED_PROTO'] || env['rack.url_scheme'] || ''
      puts "PROTO: #{forwarded_proto}"
      scheme = forwarded_proto.split(',').first
      puts "SCHEME: #{scheme}"

      host = env['HTTP_X_FORWARDED_HOST'] || env['HTTP_HOST'] || env['SERVER_NAME'] || ''
      host = host.split(',').first.strip unless host.empty?
      puts "HOST: #{host}"

      path = env['ORIGINAL_FULLPATH'] || env['REQUEST_URI']
      puts "PATH (REQUEST_URI): #{path}"
      unless path.nil? || path.empty?
        path = '/' + path.to_s if path.to_s.slice(0, 1) != '/'
      end
      puts "PATH After `unless path.nil? || path.empty?`: #{path}"

      port = env['HTTP_X_FORWARDED_PORT']
      if port && !(!scheme.nil? && scheme.downcase == 'http' && port.to_i == 80) && \
         !(!scheme.nil? && scheme.downcase == 'https' && port.to_i == 443) && \
         !(host.include? ':')
        host = host + ':' + port
      end

      url = [scheme, '://', host, path].join
      puts "URL: #{url}"
      url
    end
```

Result:

```
PROTO: https
SCHEME: https
HOST: www.example.com
PATH (REQUEST_URI): https://www.example.com/home
PATH After `unless path.nil? || path.empty?`: /https://www.example.com/home
URL: https://www.example.com/https://www.example.com/home
```

I think `REQUEST_URI` needs to be replaced with `REQUEST_PATH` in the [`rollbar_url` method of `request_data_extractor.rb`](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/request_data_extractor.rb#L131):

```diff
- path = env['ORIGINAL_FULLPATH'] || env['REQUEST_URI']
+ path = env['ORIGINAL_FULLPATH'] || env['REQUEST_PATH']
```

After modification locally:

```
PROTO: https
SCHEME: https
HOST: www.example.com
PATH (REQUEST_PATH): /home
PATH After `unless path.nil? || path.empty?`: /home
URL: https://www.example.com/home
```

**Comment by waltjones** [comment]
Hi @arthurio,

It is unfortunately hard to find proper documentation for `REQUEST_URI` in Rack environments. I will refer to the Rack source, because while this is covered in blog posts and such, it doesn't seem to be covered in the Rack docs as it should be.

https://github.com/rack/rack/blob/7420be230f73ed350fb0aea612d0ea98cb451778/lib/rack/handler/scgi.rb#L40

`REQUEST_URI` is the concatenation of `REQUEST_PATH` and `QUERY_STRING`, which makes it equivalent to the full path. Using `REQUEST_PATH`, while possible to do, would omit the query string. 

I expect some middleware in your application is rewriting `REQUEST_URI`. Let me know if this makes sense, or if I am missing some detail about your report.

**Comment by arthurio** [comment]
>it doesn't seem to be covered in the Rack docs as it should be

Indeed, I didn't find anything helpful... I'll admit that I'm not a Ruby expert but looking at various blog posts, the `REQUEST_URI` seems to often be the full url (e.g. `http://www.example.com/test?ok=1`) as opposed to the path + query string as you would expect.

We don't have any other middleware that would change its value and a pretty simple sinatra setup so I'm wondering if it's just the default behavior of sinatra? Could it be the `absolute` defaulted to `true` in the [`uri` function of sinatra](https://github.com/sinatra/sinatra/blob/2e368238238358538cc0e02fe900f3ea05705c0a/lib/sinatra/base.rb#L286)?

Anyway, that doesn't seem like a bug on your end so I'll close this ticket and do some more investigation.

**Comment by waltjones** [comment]
I did try this on a minimal Sinatra 2.0.5 setup and confirmed the expected value for `REQUEST_URI`. If you let me know the version of Sinatra you're using, I can try that as well.

**Comment by arthurio** [comment]
We are on `1.3.6`.

**Comment by waltjones** [comment]
Thank you, I'll take a look.

**Comment by waltjones** [comment]
@arthurio, I'm seeing your format of `REQUEST_URI` when using WEBrick. (As opposed to, for example, Puma.) As a workaround, consider Puma or another web server for your Sinatra app.

I'll look into a fix for rollbar-gem. Thank you for the report.

**Comment by arthurio** [comment]
Ok I'll take a look at that, thanks!
