### ISSUE TITLE
uninitialized constant Rollbar::Scrubbers

### ISSUE THREAD

**Issue by nijikon** [rollbar/rollbar-gem#833]
I think that we are missing `require 'rollbar/scrubbers'` in `lib/rollbar/item.rb`.

```
Failsafe from rollbar-gem. NameError: "uninitialized constant Rollbar::Scrubbers" in /app/vendor/bundle/ruby/2.5.0/gems/rollbar-2.19.1/lib/rollbar/item.rb:174:in `scrub': build_item in exception_data
```

**Comment by waltjones** [comment]
@nijikon thank you for the report. See https://github.com/rollbar/rollbar-gem/pull/834, and this will be in the next update.
