### ISSUE TITLE
how to ignore 503 errors from a rails application

### ISSUE THREAD

**Issue by umarsheikh** [rollbar/rollbar-gem#843]
I have a rails application that sometimes raises http status of 503 (internal_server_error). I want to exclude those from tracking in rollbar. Is there a way to ignore this particular error from getting tracked and counting against the quota limit?

**Comment by waltjones** [comment]
The preferred way is to rescue those exceptions where they happen, and handle accordingly. (Or fix the underlying issue, if that's appropriate.)

If this isn't possible or intended, see the **Ignoring Items** section of the docs (https://docs.rollbar.com/docs/ruby), and the description of `configuration.before_process`.

**Comment by umarsheikh** [comment]
The original code was similar to the following:
    
    x = obtain_data
    json_response({mydata: x})

but the call to obtain_data can raise some errors, which actually clog up rollbar since there are so many calls to this method. So I tried to handle it like this:


    begin
      x = obtain_data
    rescue ErrorType1 => e
    rescue ErrorType2 => e
    end
    if e
        return render :json => e.class.to_s.to_json, :status => :internal_server_error
    else
        json_response({mydata: x})
    end

but since I make the status 503 above, it still ends up showing in rollbar.

It is rather easier to raise 503 so that javascript can know that an error has occured instead of sending back an empty hash, so is there a way to tell rollbar to ignore responses with status of unprocessible_entity?

**Comment by waltjones** [comment]
The gem doesn't report based on HTTP status responses. It would require the exception to be unhandled or reraised. (I just tested to make sure my understanding of this is correct, because the gem _will_ report on `env['action_dispatch.exception']` if it exists.)

It seems like there is still an exception not being handled by your `rescue`. You should check that the exception class reported by Rollbar is one of the types you are rescuing. You can also try a broader rescue while debugging the issue, e.g. `rescue => e` and see if that picks up the unhandled exception.

**Comment by umarsheikh** [comment]
@waltjones I am sorry for the earlier message. In fact, its rescue is exactly like the one you mentioned, so my rescues actually look like:

    begin
      x = obtain_data
    rescue ErrorType1 => e
    rescue => e
    end
    if e
        return render :json => e.class.to_s.to_json, :status => :internal_server_error
    else
        json_response({mydata: x})
    end

so basically I simply trap the exception and simply return a status of :internal_server_error for js to handle it, but it still ends up in rollbar

**Comment by waltjones** [comment]
@umarsheikh  I don't think `e` will have the value you expect outside the scope of the rescue block. Also, multiple rescue blocks may not have the behavior you expect in this case.

This looks like what I think you intend to do:
```
begin
  x = obtain_data
  json_response({mydata: x})

rescue => e
  return render :json => e.class.to_s.to_json, :status => :internal_server_error
end
```

Or if you want to handle multiple specific exceptions, with the same behavior:
```
begin
  x = obtain_data
  json_response({mydata: x})

rescue ErrorType1, ErrorType2 => e
  return render :json => e.class.to_s.to_json, :status => :internal_server_error
end
```

And if you want to handle them differently, do use multiple rescue blocks, but put the behavior in each block:
```
begin
  x = obtain_data
  json_response({mydata: x})

rescue ErrorType1 => e
  return render :json => e.class.to_s.to_json, :status => :internal_server_error
rescue ErrorType2, ErrorType3 => e
  return render :json => e.class.to_s.to_json, :status => :bad_request
end
```

**Comment by brianr** [comment]
@umarsheikh have you had a chance to try what @waltjones suggested? ^

**Comment by umarsheikh** [comment]
@waltjones and @brianr sorry for absconding, i got pulled over to ohter tasks. I have just rolled out what you suggested, and will let you know tomorrow how it goes.

**Comment by umarsheikh** [comment]
@waltjones and @brianr i am really surprised that my issue got fixed once i pulled in the response within each block, so something like:

    begin
      x = obtain_data
      return json_response({mydata: x})
    rescue ErrorType1 => e
      return render :json => e.class.to_s.to_json, :status => :internal_server_error
    rescue => e
      return render :json => e.class.to_s.to_json, :status => :internal_server_error
    end
really did work!

I am not sure why my earlier code did not work, which basically was:

    e = nil
    begin
      x = obtain_data
    rescue ErrorType1 => e
      return render :json => e.class.to_s.to_json, :status => :internal_server_error
    rescue ErrorType2, ErrorType3 => e
      return render :json => e.class.to_s.to_json, :status => :bad_request
    end
    if e
      return render :json => e.class.to_s.to_json, :status => :internal_server_error
    else
      json_response({mydata: x})
    end

But after returning the response from within the appropriate block, it started working, and now this error does not show in rollbar, which was the intended behavior.

Thanks for you help, and this issue can now be closed!

**Comment by umarsheikh** [comment]
In fact, just to be clear, I had even declared e as a local variable outside the begin rescue blocks to ensure that the e is available throughout the method. But it somehow still did not work. Moving the return render response within each rescue block (magically) worked!

**Comment by rokob** [comment]
What version of Ruby is this?

**Comment by umarsheikh** [comment]
@rokob it is ruby 2.3.1p112, rails 5.1.6, and rollbar 2.16.4

**Comment by waltjones** [comment]
@umarsheikh your original code could be made to work with a couple changes. The `e` passed by `rescue` is scoped to that rescue block and never gets assigned to anything. Also when there are multiple rescue blocks, only the first matching block is executed. Because you catch everything with `rescue => e` this behavior is masked there but will show up in other situations.

```
my_e = nil
begin
  x = obtain_data
rescue ErrorType1 => e
  my_e = e
rescue ErrorType2 => e
  my_e = e
end
if my_e
  return render :json => my_e.class.to_s.to_json, :status => :internal_server_error
else
  json_response({mydata: x})
end
```
If you are handling both errors the same way, you can simplify:
```
rescue ErrorType1, ErrorType2 => e
```
The example I gave you previously is more idiomatic and preferred because the non-error case is handled in the begin block, and the rescue clauses already handle the branching logic of a failure, removing the need for extra if statements.

**Comment by rokob** [comment]
But why does this:

```ruby
def obtain_data
  raise StandardError.new('hello')
end

begin
  x = obtain_data
rescue => e
end

if e
  puts x
  puts e
else
  puts "no error"
end
```

output:

```

hello
```

**Comment by rokob** [comment]
I thought it might be some magic at the top level, so I did

```ruby
class Thing
  def obtain_data
    raise StandardError.new('hello')
  end

  def process
    begin
      obtain_data
    rescue => e
    end

    if e
      return "broken"
    else
      return "works"
    end
  end
end

puts Thing.new.process
```

which diassembles to (I removed the trace calls because they just clutter things up):

```
== disasm: #<ISeq:<main>@example.rb>====================================
0002 putspecialobject 3
0004 putnil           
0005 defineclass      :Thing, <class:Thing>, 0
0009 pop              
0012 putself          
0013 getinlinecache   20, <is:0>
0016 getconstant      :Thing
0018 setinlinecache   <is:0>
0020 opt_send_without_block <callinfo!mid:new, argc:0, ARGS_SIMPLE>, <callcache>
0023 opt_send_without_block <callinfo!mid:process, argc:0, ARGS_SIMPLE>, <callcache>
0026 opt_send_without_block <callinfo!mid:puts, argc:1, FCALL|ARGS_SIMPLE>, <callcache>
0029 leave            
== disasm: #<ISeq:<class:Thing>@example.rb>=============================
0004 putspecialobject 1
0006 putobject        :obtain_data
0008 putiseq          obtain_data
0010 opt_send_without_block <callinfo!mid:core#define_method, argc:2, ARGS_SIMPLE>, <callcache>
0013 pop              
0016 putspecialobject 1
0018 putobject        :process
0020 putiseq          process
0022 opt_send_without_block <callinfo!mid:core#define_method, argc:2, ARGS_SIMPLE>, <callcache>
0027 leave                                                            (   6)
== disasm: #<ISeq:obtain_data@example.rb>===============================
0004 putself          
0005 getinlinecache   12, <is:0>
0008 getconstant      :StandardError
0010 setinlinecache   <is:0>
0012 putstring        "hello"
0014 opt_send_without_block <callinfo!mid:new, argc:1, ARGS_SIMPLE>, <callcache>
0017 opt_send_without_block <callinfo!mid:raise, argc:1, FCALL|ARGS_SIMPLE>, <callcache>
0022 leave                                                            (   3)
== disasm: #<ISeq:process@example.rb>===================================
== catch table
| catch type: rescue st: 0004 ed: 0010 sp: 0000 cont: 0011
== disasm: #<ISeq:rescue in process@example.rb>=========================
local table (size: 2, argc: 0 [opts: 0, rest: -1, post: 0, block: -1, kw: -1@-1, kwrest: -1])
[ 2] "\#$!"     
0000 getlocal_OP__WC__0 2                                             (   9)
0002 putobject        StandardError
0004 checkmatch       3
0006 branchunless     14
0008 getlocal_OP__WC__0 2                                             (  10)
0010 setlocal_OP__WC__1 2                                             (   9)
0012 putnil           
0013 leave                                                            (   9)
0014 getlocal_OP__WC__0 2
0016 throw            0
| catch type: retry  st: 0010 ed: 0011 sp: 0000 cont: 0004
|------------------------------------------------------------------------
local table (size: 2, argc: 0 [opts: 0, rest: -1, post: 0, block: -1, kw: -1@-1, kwrest: -1])
[ 2] e          
0006 putself          
0007 opt_send_without_block <callinfo!mid:obtain_data, argc:0, FCALL|VCALL|ARGS_SIMPLE>, <callcache>
0010 nop                                                              (   7)
0011 pop              
0014 getlocal_OP__WC__0 2
0016 branchunless     24
0020 putstring        "broken"
0022 jump             28                                              (  12)
0026 putstring        "works"
0030 leave                                                            (  15)
```

You can clearly see that `e` as only defined in the rescue block is in the local table for the whole method containing the block. That is true even if you never reference `e` anywhere else, it still gets put into the locals outside of the rescue block.

**Comment by rokob** [comment]
This issue is already addressed, but I just wanna know why the original code didn't work. I get why the fixed code definitely will work.

**Comment by waltjones** [comment]
I have also taken a closer look at this, and it turns out `begin`/`end` do not create a new scope, and neither does the `rescue` in a `begin`/`end` "block". So my earlier comment about scope was incorrect. 

Based on this, I also don't know why the original code didn't work.
