### ISSUE TITLE
ERROR Unable to update deploy status in Rollbar

### ISSUE THREAD

**Issue by CodingAnarchy** [rollbar/rollbar-gem#853]
I recently updated to version 2.19.2 of the gem (from 2.18.2), and now receive an `ERROR Unable to update deploy status in Rollbar` at the end of my `bundle exec cap [env] deploy` run.  The deploy is noted as started in Rollbar, but the attempt to set the status to `succeeded` fails every time.

I've changed nothing in my configuration from the prior version.

**Comment by waltjones** [comment]
@CodingAnarchy Thanks for the report. What version of Capistrano are you using?

**Comment by CodingAnarchy** [comment]
@waltjones We've been using Capistrano 3.11.0.

**Comment by waltjones** [comment]
@CodingAnarchy Thank you, I'll take a look. Also, 2.19.3 was just released today with a Capistrano related update. (https://github.com/rollbar/rollbar-gem/pull/844) Can you try updating and see if it fixes your issue?

**Comment by CodingAnarchy** [comment]
@waltjones I have upgraded, but that only provided the error with more context:

```
01:44 rollbar:deploy_succeeded
      Setting deployment status to `succeeded` in Rollbar
      ERROR Unable to update deploy status in Rollbar: The deploy can not be updated because its status is not started.
```

The actual deploy can be found on the Rollbar site, with a status of "Timed-out": 
https://rollbar.com/deploy/11689851/

**Comment by waltjones** [comment]
@CodingAnarchy This is helpful. Thank you for trying it, and @ArturMoczulski or I will follow up.

**Comment by waltjones** [comment]
@CodingAnarchy So far I'm unable to reproduce your issue. Besides the error you posted, did you also get an "Unable to report deploy to Rollbar..." error, or any errors earlier than the one you posted? Otherwise, can you confirm that you see this:
```
00:00 rollbar:deploy_started
      Notifying Rollbar of deployment start
```

**Comment by ArturMoczulski** [comment]
@CodingAnarchy I don't think we have enough information on your situation to resolve this right now. How about we get on a video call and try to debug the problem for you? Please email me on artur.moczulski@rollbar.com and let's schedule a time to talk.

**Comment by CodingAnarchy** [comment]
I can confirm that I do see this:

```
00:17 rollbar:deploy_started
      Notifying Rollbar of deployment start
```

However, the last deploy run did successfully update Rollbar, so it seems that something has changed since yesterday.  Can I leave this here and report if I see the failed updates again?

**Comment by ArturMoczulski** [comment]
Sounds good. Let us know if you experience any further issues.

**Comment by timdown** [comment]
I see this too with 2.19.3. Capistrano version is 2.15.9.  Rake is 12.3.2. It works fine when I use Rake 11.3.0.

**Comment by alexrothenberg** [comment]
I ran into the same issue today & also see the related timeout issue #858.  My deploys take between 2-5 minutes. Is there any workaround or way to set that timeout currently?

**Comment by brianr** [comment]
Hi @alexrothenberg - there's a "deploy timeout" project setting that you can increase. In the Rollbar UI, go to the project then Settings -> Deploys; you can change it there (default value is currently 1 minute).

Docs at https://docs.rollbar.com/docs/deploy-tracking#section-deploy-timeout

**Comment by alexrothenberg** [comment]
thanks @brianr that was just what I needed 🥇
