### ISSUE TITLE
ERROR Unable to update deploy status in Rollbar: The deploy can not be updated because its status is not started.

### ISSUE THREAD

**Issue by johnmaxwell** [rollbar/rollbar-gem#857]
I'm seeing the same thing as #853. 

Early in the deploy I see:
```
00:05 rollbar:deploy_started
      Notifying Rollbar of deployment start
```

At the end of the deploy, I see:
```
03:17 rollbar:deploy_succeeded
      Setting deployment status to `succeeded` in Rollbar
      ERROR Unable to update deploy status in Rollbar: The deploy can not be updated because its status is not started.
```

* capistrano (3.11.0)
* capistrano-rails (1.1.7)
* rollbar (2.19.3)

**Comment by waltjones** [comment]
@johnmaxwell Is this intermittent or happening consistently? I think it's an issue with the Rollbar API, but I haven't seen it reproduce yet here. I'm looking to get more insight on the conditions.

**Comment by johnmaxwell** [comment]
@waltjones It happened twice yesterday, so I started googling the error and found #853 . I'll check again this morning.

![image](https://user-images.githubusercontent.com/13686/55076618-4cff4a80-506c-11e9-862d-ce6f1eb94a2e.png)

![image](https://user-images.githubusercontent.com/13686/55076585-378a2080-506c-11e9-803c-57d10025a307.png)

**Comment by johnmaxwell** [comment]
It happened again. It's important to note that before the deploy had finished, the rollbar deploy record had timed out. It takes us about 3 minutes to compile assets for our application, so we need at least 3 minutes to deploy.

See this screenshot, taken before our deployment had finished and before the rollbar:deploy_succeeded was attempted.

![image](https://user-images.githubusercontent.com/13686/55076977-1675ff80-506d-11e9-84e9-e8da49140fcf.png)

**Comment by kruglyjmax** [comment]
@johnmaxwell Hi, look at deploy-timeout setting https://docs.rollbar.com/docs/deploy-tracking#section-deploy-timeout

**Comment by johnmaxwell** [comment]
> @johnmaxwell Hi, look at deploy-timeout setting https://docs.rollbar.com/docs/deploy-tracking#section-deploy-timeout

That was it. Thanks!

**Comment by waltjones** [comment]
@kruglyjmax Thank you!

@johnmaxwell Thank you for the follow up.
