### ISSUE TITLE
Rethink the deploy timeout

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar-gem#858]
Related to https://github.com/rollbar/rollbar-gem/issues/853

We need to rethink our strategy around how we deal with timeout issues in deploy tracking

**Comment by ArturMoczulski** [comment]
Currently, the timeout is set to 60 seconds which IMHO is definitely too short. I'd suggest to bump it to at least 5 minutes

**Comment by letaniaferreira** [comment]
We also need to improve the error message. The message that customers get when the deploy times out is not helpful.
