### ISSUE TITLE
NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by kindkains** [rollbar/rollbar-gem#859]
Hi,

I am trying to install the software [pia](https://github.com/LINCnil/pia-back) and using their [Guide](https://github.com/LINCnil/pia/files/1771633/PIA.Installation.Runbook.V1.2.docx).

Unfortunatly (for me) they are working with ruby, rails, gem, rvm etc. which are all tools, I've never used before, so please forgive me my eventually noobyness in this topic.

Imho this guide is terrible, because the refered versions are too old and a lot of the used commands do not run out of the box and I had to do a lot of research to fix all the problems (and I will also give a feedback to the team @LINCnil), but at the moment I am stuck.

I did
`rake db:create`

and it ran fine.

Afterwards I did

`rake db:migrate`

and I've got an error:

> rake aborted!
> NoMethodError: undefined method `split' for nil:NilClass

Again I started to search the web and I found a lot hits about this issue, but the consens was, that there is an issue with the version and will be fixed in the next version. All of theses threads were 3 years old (or even older). So I am already using the next-next-next... version :-)

To give some more information:

- OS: Ubuntu 18.04 LTS (server, no GUI)
- ruby: 2.3.1
- ruby-rails: 5.0.6
- rvm: 1.29.7
- rake: 12.3.1-1
- gem: 1.1.1
- bundler: 2.0.1
- nodejs: 8.10.0

Any suggestions what I could do or can I add some additional information for debugging?
[logs.tar.gz](https://github.com/rollbar/rollbar-gem/files/3038493/logs.tar.gz)

**Comment by waltjones** [comment]
@kindkains Your best bet will be to follow up with LINCnil. I hope this helps.
