### ISSUE TITLE
Error reports are very verbose if payload includes an ActiveSupport::TimeWithZone

### ISSUE THREAD

**Issue by fcheung** [rollbar/rollbar-gem#876]
The root cause of this is that Oj.dump (which rollbar uses if available) is very verbose when serializing ActiveSupport::TimeWithZone because it serializes the zone object too, which includes all the timezone transition objects (for my locale that's 2 per year going back > 100 years).

For example, in my rails app

```
Oj.dump(Time.zone.now).length #=> 97702
```

For us this occurs with errors that happen inside delayed job (because the error payload includes job details including the job's created_at, locked_at and updated_at attributes) but it could happen anywhere really.

The end result is that the occurrence page becomes cumbersome to use because so much of it is taken over by the timezone data

**Comment by waltjones** [comment]
@fcheung We'll work on getting a fix into the next release.

As a workaround, if these objects are consistently at a known key name in the data, you could add that key to `config.scrub_fields` and it should not get serialized.

**Comment by jessicahsieh** [comment]
internal conversation - https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/22395286237

**Comment by waltjones** [comment]
#890 was released some time back, but didn't handle payloads that are sent async. #920 addresses this case.

**Comment by waltjones** [comment]
Fixed by https://github.com/rollbar/rollbar-gem/pull/920.
Requires setting `config.async_json_payload = true`
