### ISSUE TITLE
Non-JSON requests being identified as JSON

### ISSUE THREAD

**Issue by andykelk** [rollbar/rollbar-gem#877]
Since upgrading to v2.20.1, our test suite has started failing with errors coming from `oj`:

```
JSON::GeneratorError:
--
  | Invalid Unicode [ff d8 ff e0 00] at 480 in '------WebKitFormBoundary8V9JTAecBUIzqoO7
  | Content-Disposition: form-data; name="qquuid"
  |  
  | 1fa813ea-068e-4b34-b248-ef8e8365a629
  | ------WebKitFormBoundary8V9JTAecBUIzqoO7
  | Content-Disposition: form-data; name="qqfilename"
  |  
  | image.jpg
  | ------WebKitFormBoundary8V9JTAecBUIzqoO7
  | Content-Disposition: form-data; name="qqtotalfilesize"
  |  
  | 5887
  | ------WebKitFormBoundary8V9JTAecBUIzqoO7
  | Content-Disposition: form-data; name="qqfile"; filename="image.jpg"
  | Content-Type: image/jpeg
  |  
  | ????'
```

Tracing it back, I found this PR: https://github.com/rollbar/rollbar-gem/pull/868 which changed the way that JSON requests are identified. 

The issue appears to be that the `HTTP_ACCEPT` header is now checked and, if the browser says that it accepts JSON, the request content is marked as JSON. 

In our test suite, any request which is sent by FineUploader is sent with the following headers:
```
"CONTENT_TYPE"=>"multipart/form-data; boundary=----WebKitFormBoundaryTqg5LfeBBmaAdXDV"
"HTTP_ACCEPT"=>"application/json"
```

So, although the browser accepts JSON for the response, the content of the request is actually `multipart/form-data` (including binary content). This is causing `oj` to blow up as it's trying to read that binary content as json when it's not.

**Comment by waltjones** [comment]
Fixed in 2.20.2.
