### ISSUE TITLE
Rollbar triggers autoloading during initialization in Rails 6.0.0.rc1

### ISSUE THREAD

**Issue by pvande** [rollbar/rollbar-gem#880]
**Steps to Reproduce**
- Create a new app with Rails 6.0.0.rc1.
- Add `gem 'rollbar'` to the Gemfile.
- Run `bundle install`.
- Run `rails environment`.
- Run `cat log/development.log`.

**Expected Results**
The `development.log` file is empty.

**Actual Results**
The log file contains the following deprecation warning:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /Users/
USER/Projects/rails-app-test/config/environment.rb:5)
```

**Analysis**
The autoloaded constants in question are coming from [this initializer](https://github.com/rails/rails/blob/v6.0.0.rc1/actiontext/lib/action_text/engine.rb#L32-L34) in Action Text.  This callback expects to wait until after ActionController::Base has been loaded before running.  This would naturally happen *after* the initialization process (say, after autoloading an application controller), but Rollbar's [`RailtieMixin`](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/rails/railtie_mixin.rb#L6-L8) immediately loads the `lib/rollbar/rake_tasks.rb`.  This file only defines a simple test task to verify that Rollbar is functioning, but in the process [creates a Rails controller](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/rake_tasks.rb#L143-L153) that descends from `ActionController::Base`.  When executed, this controller declaration automatically loads `ActionController::Base`, triggering the callbacks, and causing the helpers to become loaded – all before initialization has been completed.

One potential change that would remedy this fault and simultaneously reduce the startup time impact of the Rollbar gem would be to move the entire testing setup into its own file which is then required on-demand from the Rake task.

``` ruby
namespace :rollbar do
  desc 'Verify your gem installation by sending a test exception to Rollbar'
  task :test => [:environment] do
    require './rollbar_test'
    RollbarTest.run
  end
end
```

**Comment by waltjones** [comment]
@pvande Thank you for the report!
