### ISSUE TITLE
expose Rollbar::Notifier.enabled? in Rollbar.enabled?

### ISSUE THREAD

**Issue by nijikon** [rollbar/rollbar-gem#889]
Can we expose `enabled?` from https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/notifier.rb#L195 on `Rollbar` level? Or is there a better way to check this?

**Comment by waltjones** [comment]
`Rollbar.notifier.enabled?` isn't satisfactory?

**Comment by nijikon** [comment]
OK, that works, thanks.
