### ISSUE TITLE
Do not convert ```code blocks``` in comments not be converted to <a href=""

### ISSUE THREAD

**Issue by letaniaferreira** [rollbar/rollbar-gem#892]
User requests that links in ```code blocks``` in comments not be converted to <a href=""

https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/22879893518

**Comment by waltjones** [comment]
The customer is adding comments in the Rollbar dashboard, and would like code within "```" blocks to not get decorated with html tags. This request isn't SDK related and should go to the dashboard UI team.
