### ISSUE TITLE
custom_data_method missing Sidekiq context

### ISSUE THREAD

**Issue by msxavi** [rollbar/rollbar-gem#893]
Hello there,

I'm very annoyed by this and maybe is such a simple misconfiguration.

So, I have a multi-tenant app and I set `custom_data_method` within my initializer to always send tenant info to rollbars:

```
  config.custom_data_method = lambda do
    { tenant: Tenant.current&.database }
  end
```
It turns out that "trace.extra.tenant" appears as "None" for rollbars triggered from this `Sidekiq::Worker` I've got.

Just trying to understand why I don't have this context present. Is there anything I'm missing?

Thanks, guys!

**Comment by waltjones** [comment]
@msxavi  If I'm understanding correctly, it looks like the `custom_data_method` does get called, and `Tenant.current&.database` evaluates to the string "None".

Does that match what you're seeing?

**Comment by msxavi** [comment]
@waltjones Yes, I think rollbar returns "None" instead of `nil`, but `custom_data_method ` gets called.

I'm using `apartment-sidekiq` which I believe reports "request.params.apartment" correctly. Although I can access `Tenant.current&.database` from inside my Sidekiq::Worker, it isn't reported to rollbar along with "request.params.apartment"
