### ISSUE TITLE
Rollbar 2.22.0 breaks active job

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#903]
With addition of https://github.com/rollbar/rollbar-gem/pull/897 payload now contains proc values which are not allowed on AJ.

While using `use_active_job` option, the error is thrown: `ActiveJob::SerializationError (Unsupported argument type: Proc)`
`configured_options` hash contains `:default_logger` attribute with proc value

Since it is silently swallowed, error reporting just stops working

**Comment by waltjones** [comment]
@morgoth Thank you for the report. Will fix asap.

**Comment by waltjones** [comment]
Looking to get this released today if possible.

**Comment by waltjones** [comment]
v2.22.1 is published now.
