### ISSUE TITLE
"rollbar:deploy_succeeded" task fails

### ISSUE THREAD

**Issue by mainameiz** [rollbar/rollbar-gem#914]
Hello! I have a strange error on the end of deploy using capistrano.

```
01:38 rollbar:deploy_succeeded
      Setting deployment status to `succeeded` in Rollbar
      ERROR Unable to update deploy status in Rollbar: getaddrinfo ENOTFOUND internalapi.service.rollbar.internalinternalapi internalapi.service.rollbar.internalinternalapi:80
```

```
rake 12.3.3
capistrano 3.11.2
rollbar 2.22.1
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```

Could you help me please to investigate the issue?

**Comment by waltjones** [comment]
@mainameiz This should be resolved now. (https://status.rollbar.com/incidents/kr0v1thlyn9n) Let me know if you continue to see an issue.

**Comment by mainameiz** [comment]
Everything works! Thanks for help!

**Comment by AxelTheGerman** [comment]
I don't see this task anymore, has it been removed?
