### ISSUE TITLE
Plugins loading

### ISSUE THREAD

**Issue by firec0der** [rollbar/rollbar-gem#928]
Hi there!

I'm working on an app using plain ruby. I'm using [hutch@0.27.0](https://github.com/gocardless/hutch) gem witch depends on [activesupport](https://github.com/gocardless/hutch/blob/c0754638f2d3908d0e1d7431648eb5491ebc8eb2/hutch.gemspec#L13), so it's installed.

So, when the rollbar gem loads all plugins [there](https://github.com/rollbar/rollbar-gem/blob/691b96bad182d9bd488c6c385d66e4521ea88969/lib/rollbar.rb#L197), `active job` fails.

[That condition](https://github.com/rollbar/rollbar-gem/blob/691b96bad182d9bd488c6c385d66e4521ea88969/lib/rollbar/plugins/active_job.rb#L17) works and my app crashes on the next line, it complains that
```
NoMethodError: undefined method `on_load' for ActiveSupport:Module
```
and was fixed only after I added `activemodel` to the app's `Gemfile`.

I would not want to do that manually because:
1. I have more than 20 apps with the similar gem set.
2. It acts as it's a rails app.
3. It's not obvious.

So, the condition should be different, a lot of other gems depend on `activesupport`. Or the way plugins are loaded should be changed.

**Comment by firec0der** [comment]
With the version 2.22.1 everything works fine, the code check for an `ActionMailer`
https://github.com/rollbar/rollbar-gem/blob/5d492b00908fa9a79747008e39f9afd15eb5e9a8/lib/rollbar/plugins/active_job.rb#L18
But it crashes in 2.23.1

**Comment by waltjones** [comment]
@firec0der All makes sense, and thank you for the report.

I'll get an update out as soon as possible and will reply here.

**Comment by firec0der** [comment]
@waltjones thanks!
