### ISSUE TITLE
"Spec" directory rejected in latest version

### ISSUE THREAD

**Issue by KeiSakam** [rollbar/rollbar-gem#930]
I have used [`rollbar_api.rb`](https://github.com/rollbar/rollbar-gem/blob/master/spec/support/rollbar_api.rb) for testing personally like [`rails_helper.rb in my minimum application "rollbar_search"`](https://github.com/KeiSakam/rollbar_search/commit/bf104258cc602dd8177d1d1983636fe1b87e8851/spec/rails_helper.rb) .
But, now I can no longer call the `rollbar_api.rb` because of the rejection in updating .

The corresponding Pull Request: [Update gemspec to not include test files to reduce gem byte size #789](https://github.com/rollbar/rollbar-gem/pull/789)

If possible, I'd like to keep using that file `spec/support/rollbar_api.rb` even as updating rollbar from now on .
What would be best thing to do ?

[minimum application "rollbar_search" in my repository](https://github.com/KeiSakam/rollbar_search)

[rails_helper.rb :L25-26](https://github.com/KeiSakam/rollbar_search/blob/9643184ae77bb3de537cafd2d552d31174c9ba39/spec/rails_helper.rb#L25-L26)
[rails_helper.rb :L46-49](https://github.com/KeiSakam/rollbar_search/blob/9643184ae77bb3de537cafd2d552d31174c9ba39/spec/rails_helper.rb#L46-L49)
[Gemfile.lock :L133](https://github.com/KeiSakam/rollbar_search/blob/9643184ae77bb3de537cafd2d552d31174c9ba39/Gemfile.lock#L133)

**Comment by waltjones** [comment]
@KeiSakam Yes I think we can add that back in. Good to hear it's been useful for you.

**Comment by KeiSakam** [comment]
Thank you for dealing with my request.  🙇 
Then, I'll take that in again .

**Comment by KeiSakam** [comment]
I appliciate your kindness to reinclude api helpers .
I think that commit will be released within rollbar 2.23.**3**
Is my understanding correct ?
