### ISSUE TITLE
Scrub headers is unexpectedly case-sensitive

### ISSUE THREAD

**Issue by pmen** [rollbar/rollbar-gem#934]
Scrub headers transforms header names in an unexpected manner. Namely it splits the headers on underscores and title-cases each word of the header. This means that if a user of the rollbar gem fails to list their headers to be scrubbed in that same casing, their headers will end up unscrubbed.

Request header name transform:
https://github.com/rollbar/rollbar-gem/blob/29533772e47cac32acc7818657d6c9bbd9f551fa/lib/rollbar/request_data_extractor.rb#L105

Membership check in sensitive headers list:
https://github.com/rollbar/rollbar-gem/blob/29533772e47cac32acc7818657d6c9bbd9f551fa/lib/rollbar/request_data_extractor.rb#L108

**Example** 
An `X-API-Secret` header would need to be listed in the scrub headers config as `X-Api-Secret` in order to get appropriately scrubbed, and otherwise would appear unfiltered in rollbar.

**Expected behavior**
Given HTTP headers are case-insensitive, a case-insensitive match of request headers to the scrub headers config would seem like the more appropriate behavior. Rollbar already has appropriate behavior here for params, so can likely borrow the same logic.

**Comment by waltjones** [comment]
Agreed. This should be case insensitive.
