### ISSUE TITLE
rollbar-rails-runner fails on Rails 5.1 with uninitialized constant Rails::Command (NameError)

### ISSUE THREAD

**Issue by bf4** [rollbar/rollbar-gem#935]
Copied over from https://github.com/rollbar/rollbar-gem/pull/878#issuecomment-554184970

versions
- ruby cruby 2.6.2
- rollbar: 2.22.1, 2.23.2
- rails 5.1.7 (not 5.0.7)

code to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem_version = ENV.fetch("RAILS_VERSION")
  gem 'rails', gem_version
  gem 'actionpack', gem_version
  gem 'activemodel', gem_version
  gem 'activerecord', gem_version
  gem 'activesupport', gem_version
  gem 'actionmailer', gem_version
  gem 'railties', gem_version
  gem "rollbar", "= #{ENV.fetch("ROLLBAR_VERSION")}"
end

if ENV["REQUIRE_RAILS_COMMAND"] == 'true'
  p `bundle exec ruby -rbundler/setup -rrails/command -S rollbar-rails-runner 'p "it works with the command"'`
else
  p `bundle exec rollbar-rails-runner 'p "it works without the command"'`
end
```

with error
```sh
( export ROLLBAR_VERSION=2.23.2; export RAILS_VERSION=5.1.7;  ruby rollbar_rails.rb )
```

without error
```sh
( export ROLLBAR_VERSION=2.23.2; export RAILS_VERSION=5.1.7; export REQUIRE_RAILS_COMMAND=true; ruby rollbar_rails.rb )
```

can be fixed in the binstub by adding a require

```diff
+++ b/bin/rollbar-rails-runner
@@ -14,5 +14,4 @@ ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
 require "rubygems"
 require "bundler/setup"

+ require "rails/command"
load Gem.bin_path("rollbar", "rollbar-rails-runner")
```

related-ish #606

**Comment by waltjones** [comment]
@bf4 Thank you for the test setup. I'm using your test, and using Rails 5.1.7 on Ruby 2.6.2. I'm not able to get this to fail. 

I am running the test from the root dir of a Rails 5.1.7 project. (Otherwise it will fail looking for ./config/environment) Does this match what you're doing? Any other thoughts about what might be different?

**Comment by bf4** [comment]
@waltjones the test file  rollbar_rails.rb I provided should be sufficient.   You mention a rails app. Did you run something different?

**Comment by bf4** [comment]
ah, I see I made some assumptions when I tested that in my app root...

**Comment by bf4** [comment]
seems to be related to bootsnap. I made a test repo based on rails 5.1.7 https://github.com/bf4/rollbar_bootsnap_command_fail

minimally run `bin/test_bug` to make it fail and `bin/test_bug pass` to make it pass

**Comment by waltjones** [comment]
That project doesn't actually `require 'bootsnap'` anywhere, but that's OK. Just using the minimal Gemfile provided, without bootsnap, will repro the issue.

The default Gemfile generated by `rails new` masks this issue, which is why I wasn't seeing it.

Thanks again for the legwork on this.
