### ISSUE TITLE
[Rollbar] Error processing the item: NameError, uninitialized constant JSON.

### ISSUE THREAD

**Issue by patricksimpson** [rollbar/rollbar-gem#943]
Running within a docker container, using Ruby version 2.7.0. 

`ruby rollbar-test.rb`

`Error processing the item: NameError, uninitialized constant JSON.`

rollbar-test.rb: 
```
require 'rollbar'

Rollbar.configure do |config|
  config.access_token = '...' #filtered out token
end

Rollbar.info("Script ran successfully")
```

Added `require 'json'` to the top of that file and it works. 
Shouldn't this be a require dependency already? 

I am not running this with `rake`.

**Comment by waltjones** [comment]
@patricksimpson Thank you for the report, and the test.

I'm not able to reproduce this on 2.5.3, 2.6.3 or 2.7.0. I'm using exactly your test file, with a valid access token. No bundler, local rollbar-gem (2.24.0).

I don't imagine the docker container would make a difference. I'm thinking there must be some other difference between my test and yours.

**Comment by patricksimpson** [comment]
@waltjones thanks for the reply. Yeah, this is strange for sure. Locally, (MacOS) using the same ruby version, it works fine. Only in this docker container. I am going to try a few different images and see if that makes a difference. Sorry I will close this out if I can't find anything other than my lonely custom image.

**Comment by patricksimpson** [comment]
@waltjones Ok using the 2.7.0 Docker:
`FROM ruby:slim-buster `
https://hub.docker.com/layers/ruby/library/ruby/slim-buster/images/sha256-33d1e540c826b75d69f841da3321fe1958735f7233d7818cf1099dd93ea191f9?context=explore

Doing a `bundle install` and running the above file without the `require 'json'` 

`E, [2020-02-25T04:07:13.209017 #1] ERROR -- : [Rollbar] Sending failsafe response due to NameError: "uninitialized constant JSON" in /usr/local/bundle/gems/rollbar-2.24.0/lib/rollbar/json.rb:11:in `block in dump': error in process_item`

**Comment by waltjones** [comment]
@patricksimpson Thank you for the followup. I'm able to reproduce this with your linked docker image, and with non-slim images as well.

I'll get a fix into the next release.
