### ISSUE TITLE
Failsafe from rollbar-gem. Net::ReadTimeout: "Net::ReadTimeout with #<TCPSocket:(closed)>" in /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': error in process_item

### ISSUE THREAD

**Issue by TTD93** [rollbar/rollbar-gem#952]
Hi, we've lately had quite a lot of issues related to Rollbar. It seems that after your last update we now get quite a few Rollbars with this Net::ReadTimeout error

Failsafe from rollbar-gem. Net::ReadTimeout: "Net::ReadTimeout with #<TCPSocket:(closed)>" in /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': error in process_item

**Comment by mauro-oto** [comment]
@TTD93 same as https://github.com/rollbar/rollbar-gem/issues/950 and https://github.com/rollbar/rollbar-gem/issues/953, the PR for it is pending merge in https://github.com/rollbar/rollbar-gem/pull/951.

**Comment by TTD93** [comment]
Ah, kk. I'll close this then.
