### ISSUE TITLE
Provide convenient method to js snippet

### ISSUE THREAD

**Issue by morgoth** [rollbar/rollbar-gem#957]
Js error reporting can be enbabled by `enbable_js` option, which injects middleware to provide js snippet. This however does not always work correctly. In my case it is `que-web` UI which is broken by this middleware (I didn't debug it too much why it happens).
Also sometimes you don't want to include it on all pages.

To workaround this we're doing:
```erb
  <% rollbar_gem_dir = Gem::Specification.find_by_name("rollbar").gem_dir %>
  <script type="text/javascript">
    // https://docs.rollbar.com/docs/javascript
    var _rollbarConfig = {
      accessToken: 'post-client-access-token',
      payload: {
        environment: '<%= Rails.env %>'
      }
    };
    // Rollbar Snippet
    <%= raw File.read("#{rollbar_gem_dir}/data/rollbar.snippet.js") %>
  </script>
```

It would be nice to have something lie `Rollbar.js_snippet` or similar to not have to dig into gem internals to get this file.

**Comment by waltjones** [comment]
The most straightforward way is to add it directly to your front end code, described in the Quick Start here. https://docs.rollbar.com/docs/browser-js

Your example is the ERB version of this.

**Comment by morgoth** [comment]
Loading it from gem makes possible to change it in the future, when there is such a need. When copy pasting from docs, it will stay like this forever.

Anyway, it is only the suggestion. Feel free to close.

**Comment by waltjones** [comment]
Makes sense. I'll keep it open.
