### ISSUE TITLE
Support report_level configuration to filter reporting below certain configured level

### ISSUE THREAD

**Issue by v-kumar** [rollbar/rollbar-gem#959]
[Rollbar.js](https://docs.rollbar.com/docs/rollbarjs-configuration-reference) supports such a configuration. (Search for `reportLevel`)

I [created a PR here](https://github.com/rollbar/rollbar-gem/pull/958) to support the option.

**Comment by v-kumar** [comment]
Any update on this?

**Comment by waltjones** [comment]
Hi @v-kumar I expect to be looking at Rollbar-gem issues/PRs around the week of May 25. Apologies for the delay.

**Comment by v-kumar** [comment]
Hi @waltjones Were you able to [look at this PR](https://github.com/rollbar/rollbar-gem/pull/958) ?

**Comment by waltjones** [comment]
@v-kumar Not yet. When I get the next https://github.com/rollbar/rollbar-sf-apex release out, rollbar-gem is next on my list. Running a little later than I forecast.
