### ISSUE TITLE
access_token is missing in v2.25.1

### ISSUE THREAD

**Issue by thaivz** [rollbar/rollbar-gem#971]
After update to `v2.25.1` we experienced these log messages:

```shell
irb(main):001:0> e = StandardError.new('Test error')
irb(main):002:0> e
=> #<StandardError: Test error>
irb(main):003:0> Rollbar.error(e, 'Report test error')
I, [2020-06-18T09:24:00.029770 #116]  INFO -- : [Rollbar] Scheduling item
I, [2020-06-18T09:24:00.029845 #116]  INFO -- : [Rollbar] Sending item
I, [2020-06-18T09:24:00.030041 #116]  INFO -- : [Rollbar] Sending json
W, [2020-06-18T09:24:00.057820 #116]  WARN -- : [Rollbar] Got unexpected status code from Rollbar api: 422
I, [2020-06-18T09:24:00.057878 #116]  INFO -- : [Rollbar] Response: {
  "err": 1,
  "message": "Invalid format. access_token is missing and it is required."
}
I, [2020-06-18T09:24:00.057921 #116]  INFO -- : [Rollbar] Details: https://xxxxx (only available if report was successful)
=> {..., :notifier=>{:name=>"rollbar-gem", :version=>"2.25.1", :configured_options=>{:access_token=>"******", ... :body=>{:trace=>{:frames=>[], :exception=>{:class=>"StandardError", :message=>"Test error", :description=>"Report test error"}}}, :uuid=>"xxxxx"}
```

Although the log contained only infos and warnings, this new update made **all calls to Rollbar failed. No error reported to Rollbar.** Until we rolled back to `v2.25.0`, then things returned to normal.

In this log, the `access_token` is redacted to `******`.

**Comment by waltjones** [comment]
@thaivz Are you using a non-default API endpoint at `config.endpoint`, or is there anything in your network that would strip http request headers? The token should be present in a request header.

BTW, the redaction in the log is expected.

**Comment by waltjones** [comment]
@thaivz What is the value of `config.web_base`?

v2.25.1 no longer puts the token in the request body. It looks like you're using an endpoint that doesn't support using the http header, and I'm trying to determine where your requests are getting sent.

**Comment by thaivz** [comment]
@waltjones we are an on-prem rollbar customer, they has just suggested us to lock to `v2.25.0`.

**Comment by waltjones** [comment]
@thaivz Based on that feedback I'm closing this.
