### ISSUE TITLE
Capistrano 2: rollbar reports incorrect revision

### ISSUE THREAD

**Issue by mrchucho** [rollbar/rollbar-gem#972]
I know Capistrano 2 has fallen out of fashion, so I'm sure this is a long shot. But rollbar's Capistrano 2 deploy integration reports the wrong revision when deploying. It looks like rollbar uses Capistrano's [current_revision](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/capistrano.rb#L38) to report the revision being deployed. Unfortunately `current_revision` is actually the _currently deployed revision_ not the revision being deployed. In other words, rollbar reports a deployment of what is already deployed not what is being deployed.

**Comment by waltjones** [comment]
Released in v2.26.1 https://github.com/rollbar/rollbar-gem/releases/tag/v2.26.1
