### ISSUE TITLE
rollbar.js snippet not up to date

### ISSUE THREAD

**Issue by hashwin** [rollbar/rollbar-gem#985]
I would expect the rollbar.js version to be regularly updated along with the gem version, but it seems to be several minor versions back. 

<img width="868" alt="stark-peak-26561_-_Dashboard_-_Rollbar" src="https://user-images.githubusercontent.com/406115/88263955-87bcd580-cce8-11ea-8060-67a8e3635423.png">

**Comment by waltjones** [comment]
@hashwin There's a Rollbar.js release scheduled for this week. This will be updated when that release becomes available.

**Comment by waltjones** [comment]
This is updated now in v2.27.0. https://github.com/rollbar/rollbar-gem/releases/tag/v2.27.0
